/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Throw if a required parameter is missing
 */
export function assertParamExists(functionName: string, paramName: string, paramValue: unknown): void {
    if (paramValue === null || paramValue === undefined) {
        throw new RequiredError(paramName, `Required parameter ${paramName} was null or undefined when calling ${functionName}.`);
    }
}

/**
 * Error class for missing required parameters
 */
export class RequiredError extends Error {
    name: 'RequiredError' = 'RequiredError';
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * API error with status code and response body
 */
export class ApiError extends Error {
    public status: number;
    public body: any;
    public headers: Record<string, string>;

    constructor(status: number, body: any, headers: Record<string, string> = {}) {
        const message = `API Error: ${status}${body ? ' - ' + (typeof body === 'string' ? body : JSON.stringify(body)) : ''}`;
        super(message);
        this.name = 'ApiError';
        this.status = status;
        this.body = body;
        this.headers = headers;
    }
}

/**
 * Bad request (400)
 */
export class BadRequestError extends ApiError {
    constructor(body: any, headers: Record<string, string> = {}) {
        super(400, body, headers);
        this.name = 'BadRequestError';
    }
}

/**
 * Unauthorized (401)
 */
export class UnauthorizedError extends ApiError {
    constructor(body: any, headers: Record<string, string> = {}) {
        super(401, body, headers);
        this.name = 'UnauthorizedError';
    }
}

/**
 * Forbidden (403)
 */
export class ForbiddenError extends ApiError {
    constructor(body: any, headers: Record<string, string> = {}) {
        super(403, body, headers);
        this.name = 'ForbiddenError';
    }
}

/**
 * Not Found (404)
 */
export class NotFoundError extends ApiError {
    constructor(body: any, headers: Record<string, string> = {}) {
        super(404, body, headers);
        this.name = 'NotFoundError';
    }
}

/**
 * Server Error (5xx)
 */
export class ServerError extends ApiError {
    constructor(status: number, body: any, headers: Record<string, string> = {}) {
        super(status, body, headers);
        this.name = 'ServerError';
    }
}
