/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfigurationParameters {
    apiKey?: string;
    basePath?: string;
    baseOptions?: any;
    serverIndex?: number;
    serverVariables?: { [key: string]: string };
}

export class Configuration {
    /**
     * API key for authentication via X-API-Key header
     */
    apiKey?: string;
    /**
     * Override base path
     */
    basePath?: string;
    /**
     * Base options for axios calls
     */
    baseOptions?: any;
    /**
     * The index of the server to use from the server list
     */
    serverIndex?: number;
    /**
     * Server variables for URL template substitution
     */
    serverVariables?: { [key: string]: string };

    constructor(param: ConfigurationParameters = {}) {
        this.apiKey = param.apiKey;
        this.basePath = param.basePath;
        this.baseOptions = param.baseOptions;
        this.serverIndex = param.serverIndex;
        this.serverVariables = param.serverVariables;
    }
}

/**
 * Server variable information
 */
export interface ServerVariable {
    description: string;
    defaultValue: string;
    enumValues?: string[];
}

/**
 * Server configuration
 */
export interface ServerConfiguration {
    url: string;
    description: string;
    variables?: { [key: string]: ServerVariable };
}

/**
 * Available server configurations
 */
export const ServerConfigurations: ServerConfiguration[] = [
    {
        url: "",
        description: "No description provided",
    },
];

/**
 * Get the URL for a server configuration, substituting variables
 */
export function getServerUrl(index: number, variables?: { [key: string]: string }): string {
    const server = ServerConfigurations[index];
    if (!server) {
        throw new Error(`Server index ${index} is out of range. Must be between 0 and ${ServerConfigurations.length - 1}`);
    }
    let url = server.url;
    if (server.variables) {
        for (const [name, variable] of Object.entries(server.variables)) {
            const value = variables?.[name] ?? variable.defaultValue;
            if (variable.enumValues && !variable.enumValues.includes(value)) {
                throw new Error(
                    `The variable '${name}' has invalid value '${value}'. Must be one of ${JSON.stringify(variable.enumValues)}`
                );
            }
            url = url.replace(`{${name}}`, value);
        }
    }
    return url;
}
