/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';
import globalAxios from 'axios';
import { Configuration, getServerUrl } from '../configuration';
import { assertParamExists } from '../common';
// @ts-ignore
import type { AuditResult } from '../models';
// @ts-ignore
import type { StandardResponseAuditLogPage } from '../models';
// @ts-ignore
import type { WrappedValidationError } from '../models';

export class AuditApi {
    private basePath: string;
    private axios: AxiosInstance;
    private configuration?: Configuration;

    constructor(configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
        this.configuration = configuration;
        this.basePath = basePath ?? configuration?.basePath ?? getServerUrl(configuration?.serverIndex ?? 0, configuration?.serverVariables);
        this.axios = axios ?? globalAxios;
    }

    /**
     * Get default request headers including auth
     */
    private getHeaders(): Record<string, string> {
        const headers: Record<string, string> = {};
        if (this.configuration?.apiKey) {
            headers['X-API-Key'] = this.configuration.apiKey;
        }
        return headers;
    }

    /**
     * List audit logs
     * This operation retrieves audit logs for the authenticated principal. You can filter by wallet, principal, action, result, or time range. Use cursor-based pagination with `after` and `before`. The `cursor` query parameter is deprecated (alias for `after`; use `after` instead). Prefer `meta.after` / `meta.before` / `meta.has_more` for pagination; `result.next_cursor` is deprecated.
     * @param wallet_id Filter audit logs by wallet ID. The wallet ID can be retrieved by calling the List all wallets operation.
     * @param principal_id Filter audit logs by the principal that performed the action. The principal ID can be retrieved by calling the List all principals operation.
     * @param action Filter audit logs by action name (for example, &#x60;transfer.initiate&#x60;, &#x60;delegation.create&#x60;).
     * @param result Filter audit logs by result. Possible values: &#x60;allowed&#x60;, &#x60;denied&#x60;, &#x60;pending&#x60;, &#x60;error&#x60;. If omitted, all results are returned.
     * @param start_time Filter audit logs created at or after this timestamp (ISO 8601 format).
     * @param end_time Filter audit logs created before this timestamp (ISO 8601 format).
     * @param after A cursor for forward pagination. Pass the &#x60;after&#x60; value from &#x60;meta&#x60; in a previous response to retrieve the next page.
     * @param before A cursor for backward pagination. Pass the &#x60;before&#x60; value from &#x60;meta&#x60; in a previous response to retrieve the preceding page.
     * @param cursor Deprecated. Use &#x60;after&#x60; instead (same semantics).
     * @param limit The maximum number of items to return. Range: [1, 200].
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async listAuditLogs(wallet_id?: string, principal_id?: string, action?: string, result?: AuditResult, start_time?: string, end_time?: string, after?: string, before?: string, cursor?: string, limit?: number, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseAuditLogPage>> {
        let localVarPath = '/api/v1/audit-logs';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (wallet_id !== undefined) {
            localVarQueryParameter['wallet_id'] = wallet_id;
        }

        if (principal_id !== undefined) {
            localVarQueryParameter['principal_id'] = principal_id;
        }

        if (action !== undefined) {
            localVarQueryParameter['action'] = action;
        }

        if (result !== undefined) {
            localVarQueryParameter['result'] = result;
        }

        if (start_time !== undefined) {
            localVarQueryParameter['start_time'] = (start_time as any instanceof Date) ?
                (start_time as any).toISOString() :
                start_time;
        }

        if (end_time !== undefined) {
            localVarQueryParameter['end_time'] = (end_time as any instanceof Date) ?
                (end_time as any).toISOString() :
                end_time;
        }

        if (after !== undefined) {
            localVarQueryParameter['after'] = after;
        }

        if (before !== undefined) {
            localVarQueryParameter['before'] = before;
        }

        if (cursor !== undefined) {
            localVarQueryParameter['cursor'] = cursor;
        }

        if (limit !== undefined) {
            localVarQueryParameter['limit'] = limit;
        }

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }
}
