/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';
import globalAxios from 'axios';
import { Configuration, getServerUrl } from '../configuration';
import { assertParamExists } from '../common';
// @ts-ignore
import type { StandardResponseListBalanceRead } from '../models';
// @ts-ignore
import type { WrappedValidationError } from '../models';

export class BalanceApi {
    private basePath: string;
    private axios: AxiosInstance;
    private configuration?: Configuration;

    constructor(configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
        this.configuration = configuration;
        this.basePath = basePath ?? configuration?.basePath ?? getServerUrl(configuration?.serverIndex ?? 0, configuration?.serverVariables);
        this.axios = axios ?? globalAxios;
    }

    /**
     * Get default request headers including auth
     */
    private getHeaders(): Record<string, string> {
        const headers: Record<string, string> = {};
        if (this.configuration?.apiKey) {
            headers['X-API-Key'] = this.configuration.apiKey;
        }
        return headers;
    }

    /**
     * List token balances
     * This operation retrieves cached token balances across all wallets accessible to the authenticated principal. Balances are synchronized from on-chain data and may be slightly delayed. You can filter by wallet, chain, address, or token. Use cursor-based pagination with `after`/`before`. Set `force_refresh=true` together with `address` to force a fresh sync from on-chain before returning.
     * @param wallet_uuid Filter balances by wallet ID. The wallet ID can be retrieved by calling the List all wallets operation.
     * @param chain_id Filter balances by chain ID (for example, &#x60;SETH&#x60;, &#x60;BASE_ETH&#x60;).
     * @param address Filter balances by on-chain address.
     * @param token_id Filter balances by token ID (for example, &#x60;SETH&#x60;, &#x60;SETH_USDC&#x60;).
     * @param force_refresh When &#x60;true&#x60; and &#x60;address&#x60; is provided, force a fresh sync of balances from on-chain before returning results.
     * @param limit The maximum number of items to return. Range: [1, 200].
     * @param after A cursor for forward pagination. Pass the &#x60;after&#x60; value from a previous response to retrieve the next page.
     * @param before A cursor for backward pagination. Pass the &#x60;before&#x60; value from a previous response to retrieve the preceding page.
     * @param offset Deprecated. Use &#x60;after&#x60;/&#x60;before&#x60; cursors instead.
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async listBalances(wallet_uuid?: string, chain_id?: string, address?: string, token_id?: string, force_refresh?: boolean, limit?: number, after?: string, before?: string, offset?: number, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseListBalanceRead>> {
        let localVarPath = '/api/v1/wallets/balances';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (wallet_uuid !== undefined) {
            localVarQueryParameter['wallet_uuid'] = wallet_uuid;
        }

        if (chain_id !== undefined) {
            localVarQueryParameter['chain_id'] = chain_id;
        }

        if (address !== undefined) {
            localVarQueryParameter['address'] = address;
        }

        if (token_id !== undefined) {
            localVarQueryParameter['token_id'] = token_id;
        }

        if (force_refresh !== undefined) {
            localVarQueryParameter['force_refresh'] = force_refresh;
        }

        if (limit !== undefined) {
            localVarQueryParameter['limit'] = limit;
        }

        if (after !== undefined) {
            localVarQueryParameter['after'] = after;
        }

        if (before !== undefined) {
            localVarQueryParameter['before'] = before;
        }

        if (offset !== undefined) {
            localVarQueryParameter['offset'] = offset;
        }

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }
}
