/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';
import globalAxios from 'axios';
import { Configuration, getServerUrl } from '../configuration';
import { assertParamExists } from '../common';
// @ts-ignore
import type { FaucetDepositRequest } from '../models';
// @ts-ignore
import type { StandardResponseFaucetDepositResult } from '../models';
// @ts-ignore
import type { StandardResponseListFaucetTokenItem } from '../models';
// @ts-ignore
import type { WrappedValidationError } from '../models';

export class FaucetApi {
    private basePath: string;
    private axios: AxiosInstance;
    private configuration?: Configuration;

    constructor(configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
        this.configuration = configuration;
        this.basePath = basePath ?? configuration?.basePath ?? getServerUrl(configuration?.serverIndex ?? 0, configuration?.serverVariables);
        this.axios = axios ?? globalAxios;
    }

    /**
     * Get default request headers including auth
     */
    private getHeaders(): Record<string, string> {
        const headers: Record<string, string> = {};
        if (this.configuration?.apiKey) {
            headers['X-API-Key'] = this.configuration.apiKey;
        }
        return headers;
    }

    /**
     * Request faucet deposit
     * This operation sends testnet tokens to the specified wallet address. Provide `address` (an on-chain address registered to one of your wallets) and `token_id` (a token available from the faucet). Call the List faucet tokens operation to see available tokens.  <Note>Daily deposit limits apply per token. The operation returns HTTP 429 if the daily limit has been reached.</Note>
     * @param FaucetDepositRequest 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async deposit(FaucetDepositRequest: FaucetDepositRequest, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseFaucetDepositResult>> {
        let localVarPath = '/api/v1/faucet/deposit';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'FaucetDepositRequest' is not null or undefined
        assertParamExists('deposit', 'FaucetDepositRequest', FaucetDepositRequest);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = FaucetDepositRequest;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * List faucet tokens
     * This operation retrieves the list of testnet tokens available from the faucet, grouped by chain.
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async listTokens(X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseListFaucetTokenItem>> {
        let localVarPath = '/api/v1/faucet/tokens';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }
}
