/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';
import globalAxios from 'axios';
import { Configuration, getServerUrl } from '../configuration';
import { assertParamExists } from '../common';
// @ts-ignore
import type { ApiKeyCreate } from '../models';
// @ts-ignore
import type { PrincipalCreate } from '../models';
// @ts-ignore
import type { PrincipalType } from '../models';
// @ts-ignore
import type { PrincipalUpdate } from '../models';
// @ts-ignore
import type { ProvisionRequest } from '../models';
// @ts-ignore
import type { StandardResponseAgentStatusResponse } from '../models';
// @ts-ignore
import type { StandardResponseApiKeyCreateResult } from '../models';
// @ts-ignore
import type { StandardResponseDictStrBool } from '../models';
// @ts-ignore
import type { StandardResponseListApiKeyRead } from '../models';
// @ts-ignore
import type { StandardResponseListPrincipalRead } from '../models';
// @ts-ignore
import type { StandardResponsePrincipalCreateResult } from '../models';
// @ts-ignore
import type { StandardResponsePrincipalRead } from '../models';
// @ts-ignore
import type { StandardResponseProvisionResponse } from '../models';
// @ts-ignore
import type { WrappedValidationError } from '../models';

export class IdentityApi {
    private basePath: string;
    private axios: AxiosInstance;
    private configuration?: Configuration;

    constructor(configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
        this.configuration = configuration;
        this.basePath = basePath ?? configuration?.basePath ?? getServerUrl(configuration?.serverIndex ?? 0, configuration?.serverVariables);
        this.axios = axios ?? globalAxios;
    }

    /**
     * Get default request headers including auth
     */
    private getHeaders(): Record<string, string> {
        const headers: Record<string, string> = {};
        if (this.configuration?.apiKey) {
            headers['X-API-Key'] = this.configuration.apiKey;
        }
        return headers;
    }

    /**
     * Create API key
     * This operation creates a new API key for a principal.  When authenticated with a principal API key, the new key is created for the authenticated principal. When authenticated with a service credential, `principal_id` is required.  Use `scopes` to restrict what the key can access. The default scope `[\"*\"]` grants full access. Individual scopes use the format `resource:action` where action is `read`, `write`, or `status`. For example: `[\"wallet:read\", \"wallet:write\"]`.  Supply `expires_at` to set an expiry time. If omitted, the key does not expire.  <Note>The raw API key value is only returned once in the response. Store it securely — it cannot be retrieved again.</Note>
     * @param ApiKeyCreate 
     * @param X_API_Key 
     * @param X_Assistant_Service_Key 
     * @param options Override http request option.
     */
    public async createApiKey(ApiKeyCreate: ApiKeyCreate, X_API_Key?: string, X_Assistant_Service_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseApiKeyCreateResult>> {
        let localVarPath = '/api/v1/api-keys';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'ApiKeyCreate' is not null or undefined
        assertParamExists('createApiKey', 'ApiKeyCreate', ApiKeyCreate);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        if (X_Assistant_Service_Key !== undefined && X_Assistant_Service_Key !== null) {
            localVarHeaderParameter['X-Assistant-Service-Key'] = String(X_Assistant_Service_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = ApiKeyCreate;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Create principal
     * This operation creates a new principal (a human or agent identity). Requires service credential authentication via `X-Service-Auth-Key`. If a principal with the same `external_id` already exists, the existing record is returned with `created=false` and HTTP 200.
     * @param PrincipalCreate 
     * @param X_Assistant_Service_Key 
     * @param options Override http request option.
     */
    public async createPrincipal(PrincipalCreate: PrincipalCreate, X_Assistant_Service_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponsePrincipalCreateResult>> {
        let localVarPath = '/api/v1/principals';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'PrincipalCreate' is not null or undefined
        assertParamExists('createPrincipal', 'PrincipalCreate', PrincipalCreate);

        if (X_Assistant_Service_Key !== undefined && X_Assistant_Service_Key !== null) {
            localVarHeaderParameter['X-Assistant-Service-Key'] = String(X_Assistant_Service_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = PrincipalCreate;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Get agent status
     * This operation retrieves the provisioning and activation status of a specific agent. The agent ID is returned as `agent_id` in the Provision agent response. Accepts either the internal UUID or the external ID. Requires authentication with the agent\'s own API key.
     * @param agent_id The agent\&#39;s unique identifier. Accepts either the internal UUID (returned as &#x60;id&#x60; by the Provision agent operation) or the external ID (&#x60;external_id&#x60;).
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async getAgentStatus(agent_id: string, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseAgentStatusResponse>> {
        let localVarPath = '/api/v1/principals/{agent_id}/status'
            .replace(`{${"agent_id"}}`, encodeURIComponent(String(agent_id)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * List API keys
     * This operation retrieves all API keys for the authenticated principal. Requires principal API key authentication. Use cursor-based pagination with `after`/`before`.
     * @param after A cursor for forward pagination. Pass the &#x60;after&#x60; value from a previous response to retrieve the next page.
     * @param before A cursor for backward pagination. Pass the &#x60;before&#x60; value from a previous response to retrieve the preceding page.
     * @param offset Deprecated. Use &#x60;after&#x60;/&#x60;before&#x60; cursors instead.
     * @param limit The maximum number of items to return. Range: [1, 200].
     * @param X_API_Key 
     * @param X_Assistant_Service_Key 
     * @param options Override http request option.
     */
    public async listApiKeys(after?: string, before?: string, offset?: number, limit?: number, X_API_Key?: string, X_Assistant_Service_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseListApiKeyRead>> {
        let localVarPath = '/api/v1/api-keys';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (after !== undefined) {
            localVarQueryParameter['after'] = after;
        }

        if (before !== undefined) {
            localVarQueryParameter['before'] = before;
        }

        if (offset !== undefined) {
            localVarQueryParameter['offset'] = offset;
        }

        if (limit !== undefined) {
            localVarQueryParameter['limit'] = limit;
        }

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        if (X_Assistant_Service_Key !== undefined && X_Assistant_Service_Key !== null) {
            localVarHeaderParameter['X-Assistant-Service-Key'] = String(X_Assistant_Service_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * List my agents
     * This operation retrieves all agent principals owned by the authenticated principal. Use cursor-based pagination with `after`/`before`.
     * @param after A cursor for forward pagination. Pass the &#x60;after&#x60; value from a previous response to retrieve the next page.
     * @param before A cursor for backward pagination. Pass the &#x60;before&#x60; value from a previous response to retrieve the preceding page.
     * @param offset Deprecated. Use &#x60;after&#x60;/&#x60;before&#x60; cursors instead.
     * @param limit The maximum number of items to return. Range: [1, 200].
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async listMyAgents(after?: string, before?: string, offset?: number, limit?: number, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseListPrincipalRead>> {
        let localVarPath = '/api/v1/principals/agents';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (after !== undefined) {
            localVarQueryParameter['after'] = after;
        }

        if (before !== undefined) {
            localVarQueryParameter['before'] = before;
        }

        if (offset !== undefined) {
            localVarQueryParameter['offset'] = offset;
        }

        if (limit !== undefined) {
            localVarQueryParameter['limit'] = limit;
        }

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * List all principals
     * This operation retrieves all principals in the system. Requires service credential authentication via `X-Service-Auth-Key`. You can filter by principal type and use cursor-based pagination with `after`/`before`.
     * @param after A cursor for forward pagination. Pass the &#x60;after&#x60; value from a previous response to retrieve the next page.
     * @param before A cursor for backward pagination. Pass the &#x60;before&#x60; value from a previous response to retrieve the preceding page.
     * @param offset Deprecated. Use &#x60;after&#x60;/&#x60;before&#x60; cursors instead.
     * @param limit The maximum number of items to return. Range: [1, 200].
     * @param type Filter principals by type. Possible values: &#x60;human&#x60;, &#x60;agent&#x60;. If omitted, all types are returned.
     * @param X_Assistant_Service_Key 
     * @param options Override http request option.
     */
    public async listPrincipals(after?: string, before?: string, offset?: number, limit?: number, type?: PrincipalType, X_Assistant_Service_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseListPrincipalRead>> {
        let localVarPath = '/api/v1/principals';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (after !== undefined) {
            localVarQueryParameter['after'] = after;
        }

        if (before !== undefined) {
            localVarQueryParameter['before'] = before;
        }

        if (offset !== undefined) {
            localVarQueryParameter['offset'] = offset;
        }

        if (limit !== undefined) {
            localVarQueryParameter['limit'] = limit;
        }

        if (type !== undefined) {
            localVarQueryParameter['type'] = type;
        }

        if (X_Assistant_Service_Key !== undefined && X_Assistant_Service_Key !== null) {
            localVarHeaderParameter['X-Assistant-Service-Key'] = String(X_Assistant_Service_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Provision agent
     * This operation provisions an agent by creating an API key. In token-based flows it also binds the agent to an owner.  Supply `token` to use the pairing code from the Cobo Agentic Wallet app (token-based provisioning). If `token` is omitted, provisioning runs in agent-first mode and returns an active agent credential.
     * @param ProvisionRequest 
     * @param options Override http request option.
     */
    public async provisionAgent(ProvisionRequest: ProvisionRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseProvisionResponse>> {
        let localVarPath = '/api/v1/principals/provision';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'ProvisionRequest' is not null or undefined
        assertParamExists('provisionAgent', 'ProvisionRequest', ProvisionRequest);

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = ProvisionRequest;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Revoke API key
     * This operation permanently revokes a specific API key. The API key ID can be retrieved by calling the List API keys operation. Once revoked, the key cannot be used for authentication.  <Warning>This action cannot be undone.</Warning>
     * @param api_key_id The UUID of the API key to revoke. You can retrieve this value by calling the List API keys operation.
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async revokeApiKey(api_key_id: string, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseDictStrBool>> {
        let localVarPath = '/api/v1/api-keys/{api_key_id}'
            .replace(`{${"api_key_id"}}`, encodeURIComponent(String(api_key_id)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Update principal
     * This operation updates the display name of a principal. A principal can update its own name, or a human principal can update the name of an agent it owns.
     * @param principal_id The UUID of the principal to update. You can retrieve this value from the List all principals or List my agents operations.
     * @param PrincipalUpdate 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async updatePrincipal(principal_id: string, PrincipalUpdate: PrincipalUpdate, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponsePrincipalRead>> {
        let localVarPath = '/api/v1/principals/{principal_id}'
            .replace(`{${"principal_id"}}`, encodeURIComponent(String(principal_id)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'PATCH', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'PrincipalUpdate' is not null or undefined
        assertParamExists('updatePrincipal', 'PrincipalUpdate', PrincipalUpdate);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = PrincipalUpdate;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }
}
