/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';
import globalAxios from 'axios';
import { Configuration, getServerUrl } from '../configuration';
import { assertParamExists } from '../common';
// @ts-ignore
import type { EthCallRequest } from '../models';
// @ts-ignore
import type { StandardResponseChainInfo } from '../models';
// @ts-ignore
import type { StandardResponseEthCallResult } from '../models';
// @ts-ignore
import type { StandardResponseListTokenCandidate } from '../models';
// @ts-ignore
import type { StandardResponseWaasPaginatedResponseChainMetadata } from '../models';
// @ts-ignore
import type { StandardResponseWaasPaginatedResponseTokenMetadata } from '../models';
// @ts-ignore
import type { WalletType } from '../models';
// @ts-ignore
import type { WrappedValidationError } from '../models';

export class MetadataApi {
    private basePath: string;
    private axios: AxiosInstance;
    private configuration?: Configuration;

    constructor(configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
        this.configuration = configuration;
        this.basePath = basePath ?? configuration?.basePath ?? getServerUrl(configuration?.serverIndex ?? 0, configuration?.serverVariables);
        this.axios = axios ?? globalAxios;
    }

    /**
     * Get default request headers including auth
     */
    private getHeaders(): Record<string, string> {
        const headers: Record<string, string> = {};
        if (this.configuration?.apiKey) {
            headers['X-API-Key'] = this.configuration.apiKey;
        }
        return headers;
    }

    /**
     * Call a view/pure function on an EVM contract
     * Proxies an `eth_call` JSON-RPC request to the configured EVM node for the given chain. Suitable for calling view or pure contract functions without creating a transaction. Returns the raw hex result.
     * @param EthCallRequest 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async ethCall(EthCallRequest: EthCallRequest, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseEthCallResult>> {
        let localVarPath = '/api/v1/metadata/eth-call';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'EthCallRequest' is not null or undefined
        assertParamExists('ethCall', 'EthCallRequest', EthCallRequest);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = EthCallRequest;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Get chain info
     * This operation retrieves configuration details for a specific chain by its Cobo chain ID (for example, `ETH`, `BASE_ETH`, `SOL`). Returns the chain identifier, RPC URL, and other chain-level metadata stored locally. Obtain the full list of supported chain IDs by calling the List supported chains operation (`GET /metadata/chains`).
     * @param chain_id The Cobo chain ID to look up (for example, &#x60;ETH&#x60;, &#x60;BASE_ETH&#x60;, &#x60;SOL&#x60;). Obtain supported chain IDs by calling the List supported chains operation (&#x60;GET /metadata/chains&#x60;).
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async getChainInfoByChainId(chain_id: string, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseChainInfo>> {
        let localVarPath = '/api/v1/metadata/chains/{chain_id}/info'
            .replace(`{${"chain_id"}}`, encodeURIComponent(String(chain_id)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * List supported assets
     * This operation retrieves the list of tokens supported by the Cobo WaaS platform for a given wallet type. Results support cursor-based pagination using `before` and `after`. Pagination cursors are also returned in `meta.after` / `meta.before` (aligned with other list endpoints).
     * @param wallet_type The wallet type to retrieve tokens for. Use &#x60;MPC&#x60;.
     * @param chain_ids A comma-separated list of Cobo chain IDs to filter by (for example, &#x60;SETH,BASE_ETH&#x60;). If omitted, tokens for all chains are returned.
     * @param token_ids A comma-separated list of token IDs to filter by (for example, &#x60;SETH,SETH_USDC&#x60;). If omitted, all tokens are returned.
     * @param limit The maximum number of items to return. Range: [1, 500].
     * @param before A cursor for backward pagination. Pass the &#x60;before&#x60; value from a previous response to retrieve the preceding page.
     * @param after A cursor for forward pagination. Pass the &#x60;after&#x60; value from a previous response to retrieve the next page.
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async listAssets(wallet_type?: WalletType, chain_ids?: string, token_ids?: string, limit?: number, before?: string, after?: string, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseWaasPaginatedResponseTokenMetadata>> {
        let localVarPath = '/api/v1/metadata/assets';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (wallet_type !== undefined) {
            localVarQueryParameter['wallet_type'] = wallet_type;
        }

        if (chain_ids !== undefined) {
            localVarQueryParameter['chain_ids'] = chain_ids;
        }

        if (token_ids !== undefined) {
            localVarQueryParameter['token_ids'] = token_ids;
        }

        if (limit !== undefined) {
            localVarQueryParameter['limit'] = limit;
        }

        if (before !== undefined) {
            localVarQueryParameter['before'] = before;
        }

        if (after !== undefined) {
            localVarQueryParameter['after'] = after;
        }

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * List supported chains
     * This operation retrieves the list of chains supported by the Cobo WaaS platform for a given wallet type. Results support cursor-based pagination using `before` and `after`. Pagination cursors are also returned in `meta.after` / `meta.before` (aligned with other list endpoints).
     * @param wallet_type The wallet type to retrieve chains for. Use &#x60;MPC&#x60;.
     * @param chain_ids A comma-separated list of Cobo chain IDs to filter by (for example, &#x60;SETH,BASE_ETH&#x60;). If omitted, all chains are returned.
     * @param limit The maximum number of items to return. Range: [1, 500].
     * @param before A cursor for backward pagination. Pass the &#x60;before&#x60; value from a previous response to retrieve the preceding page.
     * @param after A cursor for forward pagination. Pass the &#x60;after&#x60; value from a previous response to retrieve the next page.
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async listChains(wallet_type?: WalletType, chain_ids?: string, limit?: number, before?: string, after?: string, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseWaasPaginatedResponseChainMetadata>> {
        let localVarPath = '/api/v1/metadata/chains';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (wallet_type !== undefined) {
            localVarQueryParameter['wallet_type'] = wallet_type;
        }

        if (chain_ids !== undefined) {
            localVarQueryParameter['chain_ids'] = chain_ids;
        }

        if (limit !== undefined) {
            localVarQueryParameter['limit'] = limit;
        }

        if (before !== undefined) {
            localVarQueryParameter['before'] = before;
        }

        if (after !== undefined) {
            localVarQueryParameter['after'] = after;
        }

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Search tokens by symbol
     * This operation searches for tokens by their symbol (for example, `USDC`, `ETH`). Returns a list of matching tokens with their `token_id`, `chain_id`, and `chain_name`. Use the returned `token_id` in transfer and balance operations. The search is case-insensitive.
     * @param symbol The token symbol to search for (for example, &#x60;USDC&#x60;, &#x60;ETH&#x60;). Case-insensitive.
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async searchTokens(symbol: string, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseListTokenCandidate>> {
        let localVarPath = '/api/v1/metadata/tokens/search';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'symbol' is not null or undefined
        assertParamExists('searchTokens', 'symbol', symbol);

        if (symbol !== undefined) {
            localVarQueryParameter['symbol'] = symbol;
        }

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }
}
