/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';
import globalAxios from 'axios';
import { Configuration, getServerUrl } from '../configuration';
import { assertParamExists } from '../common';
// @ts-ignore
import type { PendingOperationStatus } from '../models';
// @ts-ignore
import type { RejectPendingOperationRequest } from '../models';
// @ts-ignore
import type { StandardResponsePendingOperationActionResult } from '../models';
// @ts-ignore
import type { StandardResponsePendingOperationListResponse } from '../models';
// @ts-ignore
import type { StandardResponsePendingOperationRead } from '../models';
// @ts-ignore
import type { WrappedValidationError } from '../models';

export class PendingOperationsApi {
    private basePath: string;
    private axios: AxiosInstance;
    private configuration?: Configuration;

    constructor(configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
        this.configuration = configuration;
        this.basePath = basePath ?? configuration?.basePath ?? getServerUrl(configuration?.serverIndex ?? 0, configuration?.serverVariables);
        this.axios = axios ?? globalAxios;
    }

    /**
     * Get default request headers including auth
     */
    private getHeaders(): Record<string, string> {
        const headers: Record<string, string> = {};
        if (this.configuration?.apiKey) {
            headers['X-API-Key'] = this.configuration.apiKey;
        }
        return headers;
    }

    /**
     * Approve pending operation
     * This operation approves a pending operation and triggers its execution. The pending operation ID can be retrieved by calling the List pending operations operation. Only the wallet owner principal can approve pending operations. For unpaired agent-owned wallets, the same agent principal is also the wallet owner.
     * @param pending_operation_id The unique identifier of the pending operation to approve. Obtain this ID from the List pending operations operation.
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async approvePendingOperation(pending_operation_id: string, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponsePendingOperationActionResult>> {
        let localVarPath = '/api/v1/pending-operations/{pending_operation_id}/approve'
            .replace(`{${"pending_operation_id"}}`, encodeURIComponent(String(pending_operation_id)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Get pending operation
     * This operation retrieves a specific pending approval operation by its ID. The pending operation ID is returned in the `pending_operation_id` field when a transfer, contract call, or message sign returns `status=pending_approval`. Both human owners and the agent that initiated the operation can read it.
     * @param pending_operation_id The unique identifier of the pending operation to retrieve. Obtain this ID from the List pending operations operation or from the &#x60;pending_operation_id&#x60; field returned when a transaction enters &#x60;pending_approval&#x60; status.
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async getPendingOperation(pending_operation_id: string, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponsePendingOperationRead>> {
        let localVarPath = '/api/v1/pending-operations/{pending_operation_id}'
            .replace(`{${"pending_operation_id"}}`, encodeURIComponent(String(pending_operation_id)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * List pending operations
     * This operation retrieves pending approval operations for the authenticated principal. Human owners see all operations on their wallets. Agents see operations they initiated. Use cursor-based pagination with `after`/`before`.
     * @param status Filter by operation status. Possible values: &#x60;pending&#x60;, &#x60;approved&#x60;, &#x60;rejected&#x60;, &#x60;expired&#x60;. If omitted, all statuses are returned.
     * @param after A cursor for forward pagination. Pass the &#x60;after&#x60; value from a previous response to retrieve the next page.
     * @param before A cursor for backward pagination. Pass the &#x60;before&#x60; value from a previous response to retrieve the preceding page.
     * @param offset Deprecated. Use &#x60;after&#x60;/&#x60;before&#x60; cursors instead.
     * @param limit The maximum number of items to return. Range: [1, 200].
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async listPendingOperations(status?: PendingOperationStatus, after?: string, before?: string, offset?: number, limit?: number, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponsePendingOperationListResponse>> {
        let localVarPath = '/api/v1/pending-operations';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (status !== undefined) {
            localVarQueryParameter['status'] = status;
        }

        if (after !== undefined) {
            localVarQueryParameter['after'] = after;
        }

        if (before !== undefined) {
            localVarQueryParameter['before'] = before;
        }

        if (offset !== undefined) {
            localVarQueryParameter['offset'] = offset;
        }

        if (limit !== undefined) {
            localVarQueryParameter['limit'] = limit;
        }

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Reject pending operation
     * This operation rejects a pending operation, preventing it from being executed. The pending operation ID can be retrieved by calling the List pending operations operation. Only the wallet owner principal can reject pending operations. For unpaired agent-owned wallets, the same agent principal is also the wallet owner. Optionally supply `reason` (max 500 characters) to record why the operation was rejected.
     * @param pending_operation_id The unique identifier of the pending operation to reject. Obtain this ID from the List pending operations operation.
     * @param RejectPendingOperationRequest 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async rejectPendingOperation(pending_operation_id: string, RejectPendingOperationRequest: RejectPendingOperationRequest, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponsePendingOperationActionResult>> {
        let localVarPath = '/api/v1/pending-operations/{pending_operation_id}/reject'
            .replace(`{${"pending_operation_id"}}`, encodeURIComponent(String(pending_operation_id)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'RejectPendingOperationRequest' is not null or undefined
        assertParamExists('rejectPendingOperation', 'RejectPendingOperationRequest', RejectPendingOperationRequest);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = RejectPendingOperationRequest;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }
}
