/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';
import globalAxios from 'axios';
import { Configuration, getServerUrl } from '../configuration';
import { assertParamExists } from '../common';
// @ts-ignore
import type { StandardResponseSuggestionResponse } from '../models';
// @ts-ignore
import type { SuggestionKey } from '../models';
// @ts-ignore
import type { WrappedValidationError } from '../models';

export class SuggestionsApi {
    private basePath: string;
    private axios: AxiosInstance;
    private configuration?: Configuration;

    constructor(configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
        this.configuration = configuration;
        this.basePath = basePath ?? configuration?.basePath ?? getServerUrl(configuration?.serverIndex ?? 0, configuration?.serverVariables);
        this.axios = axios ?? globalAxios;
    }

    /**
     * Get default request headers including auth
     */
    private getHeaders(): Record<string, string> {
        const headers: Record<string, string> = {};
        if (this.configuration?.apiKey) {
            headers['X-API-Key'] = this.configuration.apiKey;
        }
        return headers;
    }

    /**
     * Get Suggestion
     * Return the suggestion message for a given key.  Looks up Redis hash ``cli_suggestions`` field ``{key}`` first; falls back to the built-in default if Redis is unavailable or the field is not set. Returns empty string if the key has no built-in default. Returns 422 automatically for unrecognised keys (enforced by SuggestionKey enum).
     * @param key 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async getSuggestion(key: SuggestionKey, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseSuggestionResponse>> {
        let localVarPath = '/api/v1/suggestions/{key}'
            .replace(`{${"key"}}`, encodeURIComponent(String(key)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }
}
