/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';
import globalAxios from 'axios';
import { Configuration, getServerUrl } from '../configuration';
import { assertParamExists } from '../common';
// @ts-ignore
import type { ContractCallCreate } from '../models';
// @ts-ignore
import type { DropTransactionRequest } from '../models';
// @ts-ignore
import type { EstimateContractCallFeeRequest } from '../models';
// @ts-ignore
import type { EstimateTransferFeeRequest } from '../models';
// @ts-ignore
import type { MessageSignCreate } from '../models';
// @ts-ignore
import type { PaymentCreate } from '../models';
// @ts-ignore
import type { SpeedupTransactionRequest } from '../models';
// @ts-ignore
import type { StandardResponseContractCallSubmitResult } from '../models';
// @ts-ignore
import type { StandardResponseEstimateTransferFeeRead } from '../models';
// @ts-ignore
import type { StandardResponseListRecentAddressRead } from '../models';
// @ts-ignore
import type { StandardResponseMessageSignResult } from '../models';
// @ts-ignore
import type { StandardResponsePaymentResult } from '../models';
// @ts-ignore
import type { StandardResponseTransactionRbfResult } from '../models';
// @ts-ignore
import type { StandardResponseTransferSubmitResult } from '../models';
// @ts-ignore
import type { StandardResponseWebhookProcessResult } from '../models';
// @ts-ignore
import type { TransferCreate } from '../models';
// @ts-ignore
import type { WrappedValidationError } from '../models';

export class TransactionsApi {
    private basePath: string;
    private axios: AxiosInstance;
    private configuration?: Configuration;

    constructor(configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
        this.configuration = configuration;
        this.basePath = basePath ?? configuration?.basePath ?? getServerUrl(configuration?.serverIndex ?? 0, configuration?.serverVariables);
        this.axios = axios ?? globalAxios;
    }

    /**
     * Get default request headers including auth
     */
    private getHeaders(): Record<string, string> {
        const headers: Record<string, string> = {};
        if (this.configuration?.apiKey) {
            headers['X-API-Key'] = this.configuration.apiKey;
        }
        return headers;
    }

    /**
     * Call contract
     * This operation submits a smart contract call from the specified wallet.  For EVM chains, provide `contract_addr`, `value`, and `calldata`. For Solana, provide `instructions` and optionally `address_lookup_table_accounts`.  Supply `request_id` to enable idempotency. If a contract call with the same `request_id` already exists for the same principal, the existing record is returned with `idempotent=true`.  The operation returns `status=200` (`PENDING_APPROVAL`) when an approval policy requires review. Use the `pending_operation_id` to track and resolve the approval.  <Note>Policy evaluation runs before submission. The operation returns an error if a policy denies the contract call.</Note>
     * @param wallet_uuid The UUID of the wallet from which to execute the contract call. Retrieve this value from the &#x60;id&#x60; field returned when the wallet was created.
     * @param ContractCallCreate 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async contractCall(wallet_uuid: string, ContractCallCreate: ContractCallCreate, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseContractCallSubmitResult>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}/contract-call'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'ContractCallCreate' is not null or undefined
        assertParamExists('contractCall', 'ContractCallCreate', ContractCallCreate);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = ContractCallCreate;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Drop transaction
     * This operation cancels or drops a pending transaction.  The behavior depends on the current transaction status: - `submitted`, `pending_screening`, `pending_authorization`, `pending_signature`: the transaction is cancelled directly (no fee required). - `broadcasting`: the transaction is replaced via RBF (Replace-By-Fee). You must supply the `fee` field in the request body.  Provide `cobo_transaction_id` in the request body to identify the transaction by its provider-assigned ID instead of the local UUID in the path.  <Note>A transaction can only be dropped before it reaches `success` or `failed` status. RBF drop is not supported on VET, TRON, TVET, SOL, TON chains or gasless (paymaster) transactions.</Note>
     * @param wallet_uuid The UUID of the wallet that owns the transaction. Retrieve this value from the &#x60;id&#x60; field returned when the wallet was created.
     * @param transaction_uuid The UUID of the user transaction to drop, returned as &#x60;id&#x60; by the transfer or contract-call endpoints.
     * @param DropTransactionRequest 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async dropTransaction(wallet_uuid: string, transaction_uuid: string, DropTransactionRequest: DropTransactionRequest, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseTransactionRbfResult>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}/transactions/{transaction_uuid}/drop'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)))
            .replace(`{${"transaction_uuid"}}`, encodeURIComponent(String(transaction_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'DropTransactionRequest' is not null or undefined
        assertParamExists('dropTransaction', 'DropTransactionRequest', DropTransactionRequest);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = DropTransactionRequest;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Estimate contract call fee
     * This operation estimates the network fee for a contract call without submitting a transaction. You can use the returned `recommended`, `slow`, and `fast` fee options when constructing the contract call request.
     * @param wallet_uuid The UUID of the wallet for which to estimate the contract call fee. Retrieve this value from the &#x60;id&#x60; field returned when the wallet was created.
     * @param EstimateContractCallFeeRequest 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async estimateContractCallFee(wallet_uuid: string, EstimateContractCallFeeRequest: EstimateContractCallFeeRequest, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseEstimateTransferFeeRead>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}/estimate-contract-call-fee'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'EstimateContractCallFeeRequest' is not null or undefined
        assertParamExists('estimateContractCallFee', 'EstimateContractCallFeeRequest', EstimateContractCallFeeRequest);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = EstimateContractCallFeeRequest;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Estimate transfer fee
     * This operation estimates the network fee for a token transfer without submitting a transaction. You can use the returned `recommended`, `slow`, and `fast` fee options when constructing the transfer request.
     * @param wallet_uuid The UUID of the wallet for which to estimate the transfer fee. Retrieve this value from the &#x60;id&#x60; field returned when the wallet was created.
     * @param EstimateTransferFeeRequest 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async estimateTransferFee(wallet_uuid: string, EstimateTransferFeeRequest: EstimateTransferFeeRequest, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseEstimateTransferFeeRead>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}/estimate-transfer-fee'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'EstimateTransferFeeRequest' is not null or undefined
        assertParamExists('estimateTransferFee', 'EstimateTransferFeeRequest', EstimateTransferFeeRequest);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = EstimateTransferFeeRequest;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Handle WaaS webhook
     * This endpoint receives webhook events from the Cobo WaaS platform and processes transaction status updates and balance changes. Requests must include valid `biz-timestamp` and `biz-resp-signature` headers for signature verification.
     * @param body 
     * @param biz_timestamp Unix timestamp (milliseconds) from the Cobo WaaS webhook request, used for signature verification and replay-attack prevention.
     * @param biz_resp_signature ECDSA signature from the Cobo WaaS webhook request, used to verify that the payload originated from Cobo. Compute verification using the &#x60;biz-timestamp&#x60; and raw request body.
     * @param options Override http request option.
     */
    public async handleWaasWebhook(body: object, biz_timestamp?: string, biz_resp_signature?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseWebhookProcessResult>> {
        let localVarPath = '/api/v1/wallets/webhook';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'body' is not null or undefined
        assertParamExists('handleWaasWebhook', 'body', body);

        if (biz_timestamp !== undefined && biz_timestamp !== null) {
            localVarHeaderParameter['biz-timestamp'] = String(biz_timestamp);
        }

        if (biz_resp_signature !== undefined && biz_resp_signature !== null) {
            localVarHeaderParameter['biz-resp-signature'] = String(biz_resp_signature);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = body;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * List recent addresses
     * This operation retrieves the most recently used recipient addresses for a specific wallet, derived from transfer history. Results are ordered from most to least recent.
     * @param wallet_uuid The UUID of the wallet whose recent recipient addresses to retrieve. Retrieve this value from the &#x60;id&#x60; field returned when the wallet was created.
     * @param limit The maximum number of addresses to return. Range: [1, 50].
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async listRecentAddresses(wallet_uuid: string, limit?: number, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseListRecentAddressRead>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}/recent-addresses'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (limit !== undefined) {
            localVarQueryParameter['limit'] = limit;
        }

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Sign a message
     * This operation signs a message using the specified wallet via the Cobo WaaS platform. Currently supports EIP-712 structured data signing, with future support planned for raw hash signing, BTC signatures, and other schemes.  Set `destination_type` to select the signing method: - `eip712` (default): EIP-712 typed structured data signing. Requires an EVM-compatible chain and the `eip712_typed_data` payload field.  Set `sync=true` (default) to wait synchronously for the signing result before responding. Set `sync=false` to return immediately after submission; poll the transaction record to retrieve the signature later.  Supply `request_id` to enable idempotency. If a message-sign transaction with the same `request_id` already exists for the same principal, the existing record is returned with `idempotent=true`.  The operation returns an error if a policy denies the signing request.
     * @param wallet_uuid The UUID of the wallet that will sign the message. Retrieve this value from the &#x60;id&#x60; field returned when the wallet was created.
     * @param MessageSignCreate 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async messageSign(wallet_uuid: string, MessageSignCreate: MessageSignCreate, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseMessageSignResult>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}/message-sign'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'MessageSignCreate' is not null or undefined
        assertParamExists('messageSign', 'MessageSignCreate', MessageSignCreate);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = MessageSignCreate;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Create payment
     * Signs and submits a payment on behalf of the specified wallet using either the x402 or MPP protocol.  **Protocol selection** (required `protocol` field in the request body): - `x402`: provide the `x402_payment_required` challenge object received from the payee server. - `mpp`: provide the `mpp_www_authenticate` challenge string and, optionally, an `mpp_session` token.  **Idempotency**: if you supply a `request_id`, the endpoint checks for a previously completed transaction with the same `request_id` for this wallet. When a match is found the original result is returned immediately (`idempotent: true`) together with the original response headers (`retry_headers`) so you can replay the HTTP payment call without re-signing.  The wallet must be active (non-archived) and your principal must hold the `WALLET_TRANSFER` permission for the target wallet.
     * @param wallet_uuid UUID of the wallet to sign and submit the payment from. Obtain this value from the wallet creation or list-wallets response. The wallet must be active (not archived).
     * @param PaymentCreate 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async payment(wallet_uuid: string, PaymentCreate: PaymentCreate, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponsePaymentResult>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}/payment'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'PaymentCreate' is not null or undefined
        assertParamExists('payment', 'PaymentCreate', PaymentCreate);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = PaymentCreate;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Speed up transaction
     * This operation accelerates a broadcasting transaction by submitting a Replace-By-Fee (RBF) transaction with higher fees.  The transaction must be in `broadcasting` status. You must supply the `fee` field with higher fee parameters than the original transaction.  Provide `cobo_transaction_id` in the request body to identify the transaction by its provider-assigned ID instead of the local UUID in the path.  <Note>RBF speedup is not supported on VET, TRON, TVET, SOL, TON chains or gasless (paymaster) transactions.</Note>
     * @param wallet_uuid The UUID of the wallet that owns the transaction. Retrieve this value from the &#x60;id&#x60; field returned when the wallet was created.
     * @param transaction_uuid The UUID of the user transaction to speed up, returned as &#x60;id&#x60; by the transfer or contract-call endpoints.
     * @param SpeedupTransactionRequest 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async speedupTransaction(wallet_uuid: string, transaction_uuid: string, SpeedupTransactionRequest: SpeedupTransactionRequest, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseTransactionRbfResult>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}/transactions/{transaction_uuid}/speedup'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)))
            .replace(`{${"transaction_uuid"}}`, encodeURIComponent(String(transaction_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'SpeedupTransactionRequest' is not null or undefined
        assertParamExists('speedupTransaction', 'SpeedupTransactionRequest', SpeedupTransactionRequest);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = SpeedupTransactionRequest;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Transfer tokens
     * This operation initiates a token transfer from the specified wallet.  You need to provide `dst_addr`, `amount`, and `token_id`. The `chain_id` is automatically resolved from `token_id`. Gas fees are covered automatically — you do not need to prepare gas tokens.  Supply `request_id` to enable idempotency. If a transfer with the same `request_id` already exists for the same principal, the existing record is returned with `idempotent=true`.  The operation returns `status=200` (`PENDING_APPROVAL`) when an approval policy requires review before execution. Use the `pending_operation_id` in the response to track and resolve the approval.  <Note>Policy evaluation runs before submission. The operation returns an error if a policy denies the transfer.</Note>
     * @param wallet_uuid The UUID of the wallet to transfer tokens from. Retrieve this value from the &#x60;id&#x60; field returned when the wallet was created.
     * @param TransferCreate 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async transferTokens(wallet_uuid: string, TransferCreate: TransferCreate, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseTransferSubmitResult>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}/transfer'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'TransferCreate' is not null or undefined
        assertParamExists('transferTokens', 'TransferCreate', TransferCreate);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = TransferCreate;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }
}
