/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';
import globalAxios from 'axios';
import { Configuration, getServerUrl } from '../configuration';
import { assertParamExists } from '../common';
// @ts-ignore
import type { StandardResponseListTransactionRecordRead } from '../models';
// @ts-ignore
import type { StandardResponseTransactionRecordRead } from '../models';
// @ts-ignore
import type { WrappedValidationError } from '../models';

export class TransactionRecordsApi {
    private basePath: string;
    private axios: AxiosInstance;
    private configuration?: Configuration;

    constructor(configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
        this.configuration = configuration;
        this.basePath = basePath ?? configuration?.basePath ?? getServerUrl(configuration?.serverIndex ?? 0, configuration?.serverVariables);
        this.axios = axios ?? globalAxios;
    }

    /**
     * Get default request headers including auth
     */
    private getHeaders(): Record<string, string> {
        const headers: Record<string, string> = {};
        if (this.configuration?.apiKey) {
            headers['X-API-Key'] = this.configuration.apiKey;
        }
        return headers;
    }

    /**
     * Get transaction record
     * This operation retrieves a specific on-chain transaction record by its ID. The record ID can be retrieved by calling the List transaction records operation.
     * @param wallet_uuid The UUID of the wallet that owns the transaction record.
     * @param record_uuid The UUID of the transaction record to retrieve.
     * @param ext When &#x60;true&#x60;, the response includes an &#x60;ext_transactions&#x60; list with associated downstream transactions.
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async getTransactionRecord(wallet_uuid: string, record_uuid: string, ext?: boolean, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseTransactionRecordRead>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}/transactions/{record_uuid}'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)))
            .replace(`{${"record_uuid"}}`, encodeURIComponent(String(record_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (ext !== undefined) {
            localVarQueryParameter['ext'] = ext;
        }

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Get transaction record by request id
     * This operation retrieves a transaction record using the client-supplied idempotency key (`request_id`) scoped to the given wallet.
     * @param wallet_uuid The UUID of the wallet that owns the transaction.
     * @param request_id The same &#x60;request_id&#x60; passed when submitting the transfer or contract call.
     * @param ext When &#x60;true&#x60;, the response includes an &#x60;ext_transactions&#x60; list with associated downstream transactions.
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async getTransactionRecordByRequestId(wallet_uuid: string, request_id: string, ext?: boolean, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseTransactionRecordRead>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}/transactions/by-request-id/{request_id}'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)))
            .replace(`{${"request_id"}}`, encodeURIComponent(String(request_id)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (ext !== undefined) {
            localVarQueryParameter['ext'] = ext;
        }

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Get transaction record by record id
     * Retrieve a specific on-chain transaction record by its UUID without supplying the owning wallet. The authenticated principal must have view permission on the wallet that owns the record.
     * @param record_uuid The UUID of the transaction record to retrieve.
     * @param ext When &#x60;true&#x60;, the response includes an &#x60;ext_transactions&#x60; list with associated downstream transactions.
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async getTransactionRecordByUuid(record_uuid: string, ext?: boolean, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseTransactionRecordRead>> {
        let localVarPath = '/api/v1/wallets/transactions/{record_uuid}'
            .replace(`{${"record_uuid"}}`, encodeURIComponent(String(record_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (ext !== undefined) {
            localVarQueryParameter['ext'] = ext;
        }

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * List transaction records
     * This operation retrieves on-chain transaction records, including transfers, contract calls, and deposits. When `wallet_uuid` is provided, records are scoped to that wallet (with permission enforcement). When omitted, records across all wallets visible to the authenticated principal are returned. Use cursor-based pagination with `after`/`before`.
     * @param wallet_uuid Filter records by wallet ID. When omitted, records from all wallets visible to the authenticated principal are returned.
     * @param after A cursor for forward pagination. Pass the &#x60;after&#x60; value from a previous response to retrieve the next page.
     * @param before A cursor for backward pagination. Pass the &#x60;before&#x60; value from a previous response to retrieve the preceding page.
     * @param offset Deprecated. Use &#x60;after&#x60;/&#x60;before&#x60; cursors instead.
     * @param limit The maximum number of items to return. Range: [1, 200].
     * @param status Filter records by transaction status. Accepts UserTransactionStatus integer values (e.g. &#x60;900&#x60; for success, &#x60;901&#x60; for failed) or label strings (e.g. &#x60;success&#x60;, &#x60;processing&#x60;). If omitted, all statuses are returned.
     * @param type Filter records by transaction type. Possible values: &#x60;transfer&#x60;, &#x60;contract_call&#x60;, &#x60;deposit&#x60;, &#x60;message_sign&#x60;. If omitted, all types are returned.
     * @param token_id Filter records by token ID (for example, &#x60;SETH&#x60;, &#x60;SETH_USDC&#x60;). Use the Cobo token ID format. If omitted, all tokens are returned.
     * @param chain_id Filter records by Cobo chain ID (for example, &#x60;ETH&#x60;, &#x60;BASE_ETH&#x60;, &#x60;SOL&#x60;). If omitted, all chains are returned.
     * @param address_id Filter records by blockchain address. Matches source or destination address. If omitted, records for all addresses are returned.
     * @param ext When &#x60;true&#x60;, each record includes an &#x60;ext_transactions&#x60; list with the associated downstream (external) transactions.
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async listTransactionRecords(wallet_uuid?: string, after?: string, before?: string, offset?: number, limit?: number, status?: string, type?: string, token_id?: string, chain_id?: string, address_id?: string, ext?: boolean, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseListTransactionRecordRead>> {
        let localVarPath = '/api/v1/wallets/transactions';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (wallet_uuid !== undefined) {
            localVarQueryParameter['wallet_uuid'] = wallet_uuid;
        }

        if (after !== undefined) {
            localVarQueryParameter['after'] = after;
        }

        if (before !== undefined) {
            localVarQueryParameter['before'] = before;
        }

        if (offset !== undefined) {
            localVarQueryParameter['offset'] = offset;
        }

        if (limit !== undefined) {
            localVarQueryParameter['limit'] = limit;
        }

        if (status !== undefined) {
            localVarQueryParameter['status'] = status;
        }

        if (type !== undefined) {
            localVarQueryParameter['type'] = type;
        }

        if (token_id !== undefined) {
            localVarQueryParameter['token_id'] = token_id;
        }

        if (chain_id !== undefined) {
            localVarQueryParameter['chain_id'] = chain_id;
        }

        if (address_id !== undefined) {
            localVarQueryParameter['address_id'] = address_id;
        }

        if (ext !== undefined) {
            localVarQueryParameter['ext'] = ext;
        }

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }
}
