/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';
import globalAxios from 'axios';
import { Configuration, getServerUrl } from '../configuration';
import { assertParamExists } from '../common';
// @ts-ignore
import type { StandardResponseListWalletAddressRead } from '../models';
// @ts-ignore
import type { StandardResponseListWalletRead } from '../models';
// @ts-ignore
import type { StandardResponseNodeStatusRead } from '../models';
// @ts-ignore
import type { StandardResponseWalletAddressRead } from '../models';
// @ts-ignore
import type { StandardResponseWalletDetailRead } from '../models';
// @ts-ignore
import type { StandardResponseWalletPairInfoRead } from '../models';
// @ts-ignore
import type { StandardResponseWalletPairInitiateRead } from '../models';
// @ts-ignore
import type { StandardResponseWalletPairRead } from '../models';
// @ts-ignore
import type { StandardResponseWalletRead } from '../models';
// @ts-ignore
import type { StandardResponseWalletReshareResponse } from '../models';
// @ts-ignore
import type { StandardResponseWalletTssCallbackResponse } from '../models';
// @ts-ignore
import type { WalletAddressCreate } from '../models';
// @ts-ignore
import type { WalletCreate } from '../models';
// @ts-ignore
import type { WalletPairConfirm } from '../models';
// @ts-ignore
import type { WalletPairInitiate } from '../models';
// @ts-ignore
import type { WalletReshareRequest } from '../models';
// @ts-ignore
import type { WalletTssCallbackRequest } from '../models';
// @ts-ignore
import type { WalletUpdate } from '../models';
// @ts-ignore
import type { WrappedValidationError } from '../models';

export class WalletsApi {
    private basePath: string;
    private axios: AxiosInstance;
    private configuration?: Configuration;

    constructor(configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
        this.configuration = configuration;
        this.basePath = basePath ?? configuration?.basePath ?? getServerUrl(configuration?.serverIndex ?? 0, configuration?.serverVariables);
        this.axios = axios ?? globalAxios;
    }

    /**
     * Get default request headers including auth
     */
    private getHeaders(): Record<string, string> {
        const headers: Record<string, string> = {};
        if (this.configuration?.apiKey) {
            headers['X-API-Key'] = this.configuration.apiKey;
        }
        return headers;
    }

    /**
     * Confirm wallet pairing
     * This operation allows a human principal to confirm ownership pairing of an agent\'s wallet using the 8-digit pairing code generated by the Initiate wallet pairing operation. Pairing transfers wallet ownership to the human, creates a delegation granting the agent access, and links the agent to the human as its owner.
     * @param WalletPairConfirm 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async confirmWalletPair(WalletPairConfirm: WalletPairConfirm, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseWalletPairRead>> {
        let localVarPath = '/api/v1/wallets/pairs/confirm';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'WalletPairConfirm' is not null or undefined
        assertParamExists('confirmWalletPair', 'WalletPairConfirm', WalletPairConfirm);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = WalletPairConfirm;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Create wallet
     * This operation creates a new wallet for the authenticated principal.  You need to provide `name` and `main_node_id` (the agent\'s TSS node ID).  Set `group_type` to control the MPC key share scheme: - `agent` (2-of-2): Agent TSS node + Cobo. Default for agent-controlled wallets. - `human` (2-of-2): Mobile TSS node + Cobo.  Set `for_owner=true` to create the wallet on behalf of the principal\'s linked owner. If no linked owner exists, the wallet is created for the principal itself. Defaults to `false`.  <Note>Wallet provisioning is asynchronous. The initial response returns `status=preparing`; the wallet transitions to `status=active` once key generation completes.</Note>
     * @param WalletCreate 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async createWallet(WalletCreate: WalletCreate, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseWalletRead>> {
        let localVarPath = '/api/v1/wallets';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'WalletCreate' is not null or undefined
        assertParamExists('createWallet', 'WalletCreate', WalletCreate);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = WalletCreate;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Create wallet address
     * This operation derives a new on-chain address for the specified wallet and chain. The wallet ID can be retrieved by calling the List all wallets operation. Provide `chain_id` (Cobo metadata id, e.g. `SETH`) and/or `chain_type` (WaaS id such as `ETH`/`SOL`, or a resolvable Cobo id). If only `chain_id` is set, the server resolves the WaaS chain type. If only `chain_type` is set, behavior matches the previous API. If both are set, `chain_id` is used.
     * @param wallet_uuid 
     * @param WalletAddressCreate 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async createWalletAddress(wallet_uuid: string, WalletAddressCreate: WalletAddressCreate, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseWalletAddressRead>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}/addresses'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'WalletAddressCreate' is not null or undefined
        assertParamExists('createWalletAddress', 'WalletAddressCreate', WalletAddressCreate);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = WalletAddressCreate;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Get pair info by token
     * This operation retrieves pairing information by the 8-digit pairing code, including the agent and wallet details. No authentication is required - the code itself serves as the access credential.
     * @param token 
     * @param options Override http request option.
     */
    public async getPairInfo(token: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseWalletPairInfoRead>> {
        let localVarPath = '/api/v1/wallets/pairs/{token}'
            .replace(`{${"token"}}`, encodeURIComponent(String(token)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Get pair info by wallet
     * This operation retrieves the most recent pairing record for the specified wallet, including the associated agent and wallet details. Authentication is required. Use the wallet UUID obtained from the List all wallets operation.
     * @param wallet_uuid 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async getPairInfoByWallet(wallet_uuid: string, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseWalletPairInfoRead>> {
        let localVarPath = '/api/v1/wallets/pairs/info/{wallet_uuid}'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Get wallet
     * This operation retrieves detailed information about a specific wallet by its ID. The wallet ID can be retrieved by calling the List all wallets operation. When the caller is the wallet owner, the response includes a `spend_summary` array showing spending totals per delegation.
     * @param wallet_uuid 
     * @param include_spend_summary Whether to include per-delegation spending summaries in the response. Only populated when the authenticated principal is the wallet owner. &#x60;true&#x60;: include spend summaries. &#x60;false&#x60;: omit spend summaries.
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async getWallet(wallet_uuid: string, include_spend_summary?: boolean, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseWalletDetailRead>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (include_spend_summary !== undefined) {
            localVarQueryParameter['include_spend_summary'] = include_spend_summary;
        }

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Get node status
     * This operation retrieves the online status of the TSS node associated with a specific wallet. The wallet ID can be retrieved by calling the List all wallets operation. The response indicates whether the node is currently online and available for signing.
     * @param wallet_uuid 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async getWalletNodeStatus(wallet_uuid: string, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseNodeStatusRead>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}/node-status'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Initiate wallet pairing
     * This operation generates an 8-digit pairing code that allows a human principal to pair ownership of an agent\'s wallet. The agent must own the wallet.  <Note>The pairing code expires after 30 minutes. Only one pending pairing exists per wallet and agent; each new initiate rotates the code and invalidates the previous one.</Note>
     * @param WalletPairInitiate 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async initiateWalletPair(WalletPairInitiate: WalletPairInitiate, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseWalletPairInitiateRead>> {
        let localVarPath = '/api/v1/wallets/pairs/initiate';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'WalletPairInitiate' is not null or undefined
        assertParamExists('initiateWalletPair', 'WalletPairInitiate', WalletPairInitiate);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = WalletPairInitiate;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * List wallet addresses
     * This operation retrieves all on-chain addresses associated with a specific wallet. The wallet ID can be retrieved by calling the List all wallets operation.
     * @param wallet_uuid 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async listWalletAddresses(wallet_uuid: string, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseListWalletAddressRead>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}/addresses'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * List all wallets
     * This operation retrieves all wallets accessible to the authenticated principal. Use cursor-based pagination with `after`/`before`, or the deprecated `offset` parameter.
     * @param after A cursor for forward pagination. Pass the &#x60;after&#x60; value from a previous response to retrieve the next page.
     * @param before A cursor for backward pagination. Pass the &#x60;before&#x60; value from a previous response to retrieve the preceding page.
     * @param offset Deprecated. Use &#x60;after&#x60;/&#x60;before&#x60; cursors instead. The number of items to skip before returning results.
     * @param limit The maximum number of items to return. Range: [1, 200].
     * @param include_archived Whether to include archived wallets in the results. &#x60;true&#x60;: include archived wallets. &#x60;false&#x60;: exclude archived wallets. Defaults to &#x60;false&#x60;.
     * @param main_node_id Filter wallets by the TSS main node ID of their underlying vault. When set, only wallets whose vault\&#39;s &#x60;main_node_id&#x60; matches this value are returned. Useful for finding all wallets controlled by a specific TSS node.
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async listWallets(after?: string, before?: string, offset?: number, limit?: number, include_archived?: boolean, main_node_id?: string, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseListWalletRead>> {
        let localVarPath = '/api/v1/wallets';
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        if (after !== undefined) {
            localVarQueryParameter['after'] = after;
        }

        if (before !== undefined) {
            localVarQueryParameter['before'] = before;
        }

        if (offset !== undefined) {
            localVarQueryParameter['offset'] = offset;
        }

        if (limit !== undefined) {
            localVarQueryParameter['limit'] = limit;
        }

        if (include_archived !== undefined) {
            localVarQueryParameter['include_archived'] = include_archived;
        }

        if (main_node_id !== undefined) {
            localVarQueryParameter['main_node_id'] = main_node_id;
        }

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Update wallet
     * This operation updates the name or metadata of a specific wallet. The wallet ID can be retrieved by calling the List all wallets operation. All fields are optional; only provided fields are updated.  <Note>Archived wallets cannot be updated.</Note>
     * @param wallet_uuid 
     * @param WalletUpdate 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async updateWallet(wallet_uuid: string, WalletUpdate: WalletUpdate, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseWalletRead>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'PATCH', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'WalletUpdate' is not null or undefined
        assertParamExists('updateWallet', 'WalletUpdate', WalletUpdate);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = WalletUpdate;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Initiate wallet reshare
     * This operation initiates a key reshare for the specified wallet. Only the **wallet owner** may call this endpoint (for example, after completing wallet pairing).  The operation creates a WaaS **Signing** key share holder group for the provided TSS `node_id`, binds that node to the owner principal, then submits a `KeyGenFromKeyGroup` TSS request to derive a new signing group from the vault\'s existing main group.  <Note>Reshare is asynchronous. Poll the wallet TSS callback endpoint or the WaaS TSS request status to track completion.</Note>
     * @param wallet_uuid 
     * @param WalletReshareRequest 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async walletReshare(wallet_uuid: string, WalletReshareRequest: WalletReshareRequest, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseWalletReshareResponse>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}/reshare'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'WalletReshareRequest' is not null or undefined
        assertParamExists('walletReshare', 'WalletReshareRequest', WalletReshareRequest);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = WalletReshareRequest;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }

    /**
     * Report TSS request callback
     * This operation is called by your app after the UCW SDK reports a TSS request event (for example, from polling the TSS node). The server fetches the authoritative TSS request state from WaaS and updates the local record. On success, the vault group cache may be refreshed if the request has reached a terminal state.
     * @param wallet_uuid 
     * @param WalletTssCallbackRequest 
     * @param X_API_Key 
     * @param options Override http request option.
     */
    public async walletTssCallback(wallet_uuid: string, WalletTssCallbackRequest: WalletTssCallbackRequest, X_API_Key?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StandardResponseWalletTssCallbackResponse>> {
        let localVarPath = '/api/v1/wallets/{wallet_uuid}/tss/callback'
            .replace(`{${"wallet_uuid"}}`, encodeURIComponent(String(wallet_uuid)));
        const localVarUrlObj = new URL(localVarPath, this.basePath);
        const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...options };
        const localVarHeaderParameter: Record<string, string> = { ...this.getHeaders() };
        const localVarQueryParameter: Record<string, any> = {};

        // verify required parameter 'WalletTssCallbackRequest' is not null or undefined
        assertParamExists('walletTssCallback', 'WalletTssCallbackRequest', WalletTssCallbackRequest);

        if (X_API_Key !== undefined && X_API_Key !== null) {
            localVarHeaderParameter['X-API-Key'] = String(X_API_Key);
        }

        localVarHeaderParameter['Content-Type'] = 'application/json';
        localVarHeaderParameter['Accept'] = 'application/json';

        const queryString = new URLSearchParams(
            Object.entries(localVarQueryParameter).reduce((acc, [key, value]) => {
                if (Array.isArray(value)) {
                    value.forEach(v => acc.push([key, String(v)]));
                } else {
                    acc.push([key, String(value)]);
                }
                return acc;
            }, [] as [string, string][])
        ).toString();
        if (queryString) {
            localVarUrlObj.search = queryString;
        }

        localVarRequestOptions.headers = { ...localVarHeaderParameter, ...options?.headers };
        localVarRequestOptions.data = WalletTssCallbackRequest;
        localVarRequestOptions.url = localVarUrlObj.toString();

        return this.axios.request(localVarRequestOptions);
    }
}
