/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Agent status payload used by ``/principals/{id}/status``.
 * @export
 * @interface AgentStatusResponse
 */
export interface AgentStatusResponse {
    /**
     * The agent\'s principal ID.
     * @type {string}
     * @memberof AgentStatusResponse
     */
    'agent_id': string;
    /**
     * The agent\'s current status. `active`: the agent is ready for use. `temporary`: deprecated legacy value kept for backward compatibility and planned for removal in a future major release.
     * @type {string}
     * @memberof AgentStatusResponse
     */
    'status': AgentStatusResponseStatusEnum;
    /**
     * Whether the agent has been linked to an owner. `true`: linked. `false`: not linked.
     * @type {boolean}
     * @memberof AgentStatusResponse
     */
    'owner_linked': boolean;
    /**
     * The onboarding session ID associated with this agent, if set.
     * @type {string}
     * @memberof AgentStatusResponse
     */
    'onboarding_session_id'?: string;
}

export const AgentStatusResponseStatusEnum = {
    active: 'active' as const,
    temporary: 'temporary' as const,
} as const;

export type AgentStatusResponseStatusEnum = typeof AgentStatusResponseStatusEnum[keyof typeof AgentStatusResponseStatusEnum];

