/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Public API key response payload without delegation internals.
 * @export
 * @interface ApiKeyPublicRead
 */
export interface ApiKeyPublicRead {
    /**
     * The API key ID.
     * @type {string}
     * @memberof ApiKeyPublicRead
     */
    'id': string;
    /**
     * The ID of the principal this key belongs to.
     * @type {string}
     * @memberof ApiKeyPublicRead
     */
    'principal_id': string;
    /**
     * Optional pact binding for this key. When set, requests made with this key are executed within the context of the specified pact.
     * @type {string}
     * @memberof ApiKeyPublicRead
     */
    'pact_id'?: string;
    /**
     * The display name of this API key.
     * @type {string}
     * @memberof ApiKeyPublicRead
     */
    'name': string;
    /**
     * The first few characters of the API key, for identification purposes.
     * @type {string}
     * @memberof ApiKeyPublicRead
     */
    'key_prefix': string;
    /**
     * The access scopes granted to this key.
     * @type {Array<string>}
     * @memberof ApiKeyPublicRead
     */
    'scopes': Array<string>;
    /**
     * The expiry timestamp for this key, in ISO 8601 format. Null if no expiry.
     * @type {string}
     * @memberof ApiKeyPublicRead
     */
    'expires_at': string;
    /**
     * The timestamp when this key was last used, in ISO 8601 format. Null if never used.
     * @type {string}
     * @memberof ApiKeyPublicRead
     */
    'last_used_at': string;
    /**
     * Whether this key has been revoked. `true`: revoked. `false`: active.
     * @type {boolean}
     * @memberof ApiKeyPublicRead
     */
    'is_revoked': boolean;
    /**
     * The timestamp when this key was revoked, in ISO 8601 format. Null if not revoked.
     * @type {string}
     * @memberof ApiKeyPublicRead
     */
    'revoked_at': string;
    /**
     * The timestamp when the key was created, in ISO 8601 format.
     * @type {string}
     * @memberof ApiKeyPublicRead
     */
    'created_at': string;
    /**
     * The timestamp when the key was last updated, in ISO 8601 format.
     * @type {string}
     * @memberof ApiKeyPublicRead
     */
    'updated_at': string;
}

