/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * API key response payload.
 * @export
 * @interface ApiKeyRead
 */
export interface ApiKeyRead {
    /**
     * The API key ID.
     * @type {string}
     * @memberof ApiKeyRead
     */
    'id': string;
    /**
     * The ID of the principal this key belongs to.
     * @type {string}
     * @memberof ApiKeyRead
     */
    'principal_id': string;
    /**
     * Optional delegation binding for this key. When set, requests must execute within this delegation context.
     * @type {string}
     * @memberof ApiKeyRead
     */
    'delegation_id'?: string;
    /**
     * Optional pact binding for this key. When set, requests made with this key are executed within the context of the specified pact.
     * @type {string}
     * @memberof ApiKeyRead
     */
    'pact_id'?: string;
    /**
     * The display name of this API key.
     * @type {string}
     * @memberof ApiKeyRead
     */
    'name': string;
    /**
     * The first few characters of the API key, for identification purposes.
     * @type {string}
     * @memberof ApiKeyRead
     */
    'key_prefix': string;
    /**
     * The access scopes granted to this key.
     * @type {Array<string>}
     * @memberof ApiKeyRead
     */
    'scopes': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyRead
     */
    'expires_at': string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyRead
     */
    'last_used_at': string | null;
    /**
     * Whether this key has been revoked. `true`: revoked. `false`: active.
     * @type {boolean}
     * @memberof ApiKeyRead
     */
    'is_revoked': boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyRead
     */
    'revoked_at': string | null;
    /**
     * The timestamp when the key was created, in ISO 8601 format.
     * @type {string}
     * @memberof ApiKeyRead
     */
    'created_at': string;
    /**
     * The timestamp when the key was last updated, in ISO 8601 format.
     * @type {string}
     * @memberof ApiKeyRead
     */
    'updated_at': string;
}

