/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Represents a spending limit that applies to a given operation, returned in dry-run and pending operation responses.
 * @export
 * @interface ApplicableLimitRead
 */
export interface ApplicableLimitRead {
    /**
     * The subject type for this limit (for example, `principal`, `delegation`).
     * @type {string}
     * @memberof ApplicableLimitRead
     */
    'subject_type': string;
    /**
     * The subject ID this limit applies to.
     * @type {string}
     * @memberof ApplicableLimitRead
     */
    'subject_id': string;
    /**
     * The operation type this limit governs (for example, `transfer`, `contract_call`).
     * @type {string}
     * @memberof ApplicableLimitRead
     */
    'operation_type': string;
    /**
     * The rolling time window for this limit (for example, `rolling_1h`, `rolling_24h`).
     * @type {string}
     * @memberof ApplicableLimitRead
     */
    'window': string;
    /**
     * The metric being limited (for example, `amount`, `tx_count`).
     * @type {string}
     * @memberof ApplicableLimitRead
     */
    'metric': string;
    /**
     * The limit threshold as a decimal string.
     * @type {string}
     * @memberof ApplicableLimitRead
     */
    'limit_value': string;
    /**
     * The amount this operation would contribute toward the limit, as a decimal string.
     * @type {string}
     * @memberof ApplicableLimitRead
     */
    'increment': string;
    /**
     * The ID of the policy that defined this limit.
     * @type {string}
     * @memberof ApplicableLimitRead
     */
    'source_policy_id': string;
}

