/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { ApprovalRead } from './approval-read';




/**
 * ApprovalListResponse
 * @export
 * @interface ApprovalListResponse
 */
export interface ApprovalListResponse {
    /**
     * 
     * @type {Array<ApprovalRead>}
     * @memberof ApprovalListResponse
     */
    'approvals': Array<ApprovalRead>;
}

