/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Evidence or delivery artifact reference.
 * @export
 * @interface Artifact
 */
export interface Artifact {
    /**
     * 
     * @type {string}
     * @memberof Artifact
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof Artifact
     */
    'reference': string;
    /**
     * 
     * @type {string}
     * @memberof Artifact
     */
    'description'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Artifact
     */
    'metadata'?: { [key: string]: string; };
}

