/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Audit action.
 * @export
 * @enum {string}
 */
export const AuditAction = {
    unknown: 'unknown' as const,
    authz_check: 'authz.check' as const,
    authz_owner_check: 'authz.owner_check' as const,
    delegation_freeze: 'delegation.freeze' as const,
    delegation_unfreeze: 'delegation.unfreeze' as const,
    approval_approved: 'approval.approved' as const,
    approval_rejected: 'approval.rejected' as const,
    sign_approval_created: 'sign_approval.created' as const,
    sign_approval_approved: 'sign_approval.approved' as const,
    sign_approval_rejected: 'sign_approval.rejected' as const,
    wallet_read: 'wallet.read' as const,
    wallet_update: 'wallet.update' as const,
    wallet_archive: 'wallet.archive' as const,
    wallet_address_create: 'wallet.address.create' as const,
    wallet_address_list: 'wallet.address.list' as const,
    wallet_balances: 'wallet.balances' as const,
    wallet_node_status: 'wallet.node_status' as const,
    transfer_initiate: 'transfer.initiate' as const,
    transfer_estimate_fee: 'transfer.estimate_fee' as const,
    transfer_allowed: 'transfer.allowed' as const,
    transfer_denied: 'transfer.denied' as const,
    transfer_approval_required: 'transfer.approval_required' as const,
    transfer_approval_approved: 'transfer.approval.approved' as const,
    transfer_approval_rejected: 'transfer.approval.rejected' as const,
    transfer_approval_expired: 'transfer.approval.expired' as const,
    transfer_approval_executed: 'transfer.approval.executed' as const,
    transfer_approval_execution_failed: 'transfer.approval.execution_failed' as const,
    contract_call_initiate: 'contract_call.initiate' as const,
    contract_call_estimate_fee: 'contract_call.estimate_fee' as const,
    contract_call_allowed: 'contract_call.allowed' as const,
    contract_call_denied: 'contract_call.denied' as const,
    contract_call_approval_required: 'contract_call.approval_required' as const,
    contract_call_approval_approved: 'contract_call.approval.approved' as const,
    contract_call_approval_rejected: 'contract_call.approval.rejected' as const,
    contract_call_approval_expired: 'contract_call.approval.expired' as const,
    contract_call_approval_executed: 'contract_call.approval.executed' as const,
    contract_call_approval_execution_failed: 'contract_call.approval.execution_failed' as const,
    message_sign_initiate: 'message_sign.initiate' as const,
    message_sign_allowed: 'message_sign.allowed' as const,
    message_sign_denied: 'message_sign.denied' as const,
    message_sign_approval_required: 'message_sign.approval_required' as const,
    message_sign_approval_approved: 'message_sign.approval.approved' as const,
    message_sign_approval_rejected: 'message_sign.approval.rejected' as const,
    message_sign_approval_expired: 'message_sign.approval.expired' as const,
    message_sign_approval_executed: 'message_sign.approval.executed' as const,
    message_sign_approval_execution_failed: 'message_sign.approval.execution_failed' as const,
    transaction_list: 'transaction.list' as const,
    transaction_list_recent_addresses: 'transaction.list_recent_addresses' as const,
    transaction_read: 'transaction.read' as const,
    transaction_drop: 'transaction.drop' as const,
    transaction_speedup: 'transaction.speedup' as const,
    transaction_record_list: 'transaction_record.list' as const,
    transaction_record_read: 'transaction_record.read' as const,
    policy_create: 'policy.create' as const,
    policy_list: 'policy.list' as const,
    policy_get: 'policy.get' as const,
    policy_update: 'policy.update' as const,
    policy_deactivate: 'policy.deactivate' as const,
    policy_dry_run: 'policy.dry_run' as const,
    faucet_deposit: 'faucet.deposit' as const,
} as const;

export type AuditAction = typeof AuditAction[keyof typeof AuditAction];

