/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Automated verification rule.
 * @export
 * @interface AutomatedCheck
 */
export interface AutomatedCheck {
    /**
     * 
     * @type {string}
     * @memberof AutomatedCheck
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof AutomatedCheck
     */
    'threshold'?: string;
    /**
     * 
     * @type {string}
     * @memberof AutomatedCheck
     */
    'script_url'?: string;
}

