/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Single chain info from get_chains_by_chain_coins.  All optional fields use ``str | None`` because the upstream Blockchain API may return ``null`` for any non-essential attribute.
 * @export
 * @interface ChainInfo
 */
export interface ChainInfo {
    /**
     * 
     * @type {string}
     * @memberof ChainInfo
     */
    'unique_chain_id': string;
    /**
     * 
     * @type {string}
     * @memberof ChainInfo
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ChainInfo
     */
    'chain_coin': string;
    /**
     * 
     * @type {string}
     * @memberof ChainInfo
     */
    'icon_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof ChainInfo
     */
    'confirming_threshold'?: number;
    /**
     * The address standard shared across chains — chains with the same chain_type share one wallet address. E.g. ETH, BASE, ARB, OP, BSC, MATIC, AVAXC, and SETH are all chain_type: ETH, so they all use the same 0x... address.
     * @type {string}
     * @memberof ChainInfo
     */
    'chain_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChainInfo
     */
    'explorer_tx_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChainInfo
     */
    'explorer_address_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChainInfo
     */
    'supported_fee_models'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChainInfo
     */
    'supported_address_encodings'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChainInfo
     */
    'supported_address_encodings_by_ksr'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ChainInfo
     */
    'enable_smart_contract_op'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ChainInfo
     */
    'is_nonce_mandatory'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ChainInfo
     */
    'is_case_sensitive'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ChainInfo
     */
    'is_testnet'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ChainInfo
     */
    'use_memo_to_deposit'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ChainInfo
     */
    'use_memo_to_withdraw'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ChainInfo
     */
    'coinbase_maturity'?: number;
    /**
     * 
     * @type {number}
     * @memberof ChainInfo
     */
    'input_utxo_limit'?: number;
    /**
     * 
     * @type {string}
     * @memberof ChainInfo
     */
    'caip2_chain_id'?: string;
}

