/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { KeyExportStatus } from './key-export-status';




/**
 * Response after marking export as complete.
 * @export
 * @interface CompleteExportResponse
 */
export interface CompleteExportResponse {
    /**
     * Final state of the key export request after it has been marked as complete.
     * @type {KeyExportStatus}
     * @memberof CompleteExportResponse
     */
    'status': KeyExportStatus;
}

