/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Supported pact completion condition types.
 * @export
 * @enum {string}
 */
export const CompletionConditionType = {
    time_elapsed: 'time_elapsed' as const,
    tx_count: 'tx_count' as const,
    amount_spent: 'amount_spent' as const,
    amount_spent_usd: 'amount_spent_usd' as const,
    manual: 'manual' as const,
} as const;

export type CompletionConditionType = typeof CompletionConditionType[keyof typeof CompletionConditionType];

