/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { Fee } from './fee';

// @ts-ignore
import type { SolAddressLookupTableAccount } from './sol-address-lookup-table-account';

// @ts-ignore
import type { SolInstruction } from './sol-instruction';




/**
 * Request payload for contract call (EVM or Solana).
 * @export
 * @interface ContractCallCreate
 */
export interface ContractCallCreate {
    /**
     * The Cobo chain ID for this contract call (for example, `SETH`, `BASE_ETH`, `SOL`). Use the List supported chains operation to retrieve all supported chain IDs.
     * @type {string}
     * @memberof ContractCallCreate
     */
    'chain_id': string;
    /**
     * The EVM contract address to call. Required for EVM chains.
     * @type {string}
     * @memberof ContractCallCreate
     */
    'contract_addr'?: string;
    /**
     * The ETH value to send with the call, in whole token units (not wei), as a decimal string. Defaults to `0`.
     * @type {string}
     * @memberof ContractCallCreate
     */
    'value'?: string;
    /**
     * The ABI-encoded calldata for the EVM function call, as a hex string.
     * @type {string}
     * @memberof ContractCallCreate
     */
    'calldata'?: string;
    /**
     * The Solana instructions for this call. Required for Solana chains.
     * @type {Array<SolInstruction>}
     * @memberof ContractCallCreate
     */
    'instructions'?: Array<SolInstruction>;
    /**
     * Optional Solana address lookup table accounts for this call.
     * @type {Array<SolAddressLookupTableAccount>}
     * @memberof ContractCallCreate
     */
    'address_lookup_table_accounts'?: Array<SolAddressLookupTableAccount>;
    /**
     * A client-supplied identifier for idempotency. If a contract call with the same `request_id` already exists for the same principal, the existing record is returned.
     * @type {string}
     * @memberof ContractCallCreate
     */
    'request_id'?: string;
    /**
     * Optional custom fee parameters. If omitted, the network default is used.
     * @type {Fee}
     * @memberof ContractCallCreate
     */
    'fee'?: Fee;
    /**
     * The source address to call from. If omitted, the server auto-selects the wallet address on this chain with the highest available native token balance for this chain (explicit `src_addr` always takes precedence).
     * @type {string}
     * @memberof ContractCallCreate
     */
    'src_addr'?: string;
    /**
     * Whether to use Cobo Gasless (Fee Station) to cover gas fees. `true`: gas fees are sponsored. `false`: gas fees are paid from the wallet. Defaults to `true` for human-owned wallets.
     * @type {boolean}
     * @memberof ContractCallCreate
     */
    'sponsor'?: boolean;
    /**
     * The gas provider to use for sponsored transactions. If omitted, the server default is used.
     * @type {string}
     * @memberof ContractCallCreate
     */
    'gas_provider'?: string;
    /**
     * Optional note stored locally and sent to WaaS as the transaction `description` (contract call).
     * @type {string}
     * @memberof ContractCallCreate
     */
    'description'?: string;
}

