/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { KeyExportStatus } from './key-export-status';




/**
 * Response after creating a key export.
 * @export
 * @interface CreateExportResponse
 */
export interface CreateExportResponse {
    /**
     * Unique identifier assigned to the newly created key export request.
     * @type {string}
     * @memberof CreateExportResponse
     */
    'export_id': string;
    /**
     * URL the wallet owner must visit to approve or reject the export request.
     * @type {string}
     * @memberof CreateExportResponse
     */
    'authorization_url': string;
    /**
     * Initial state of the key export request immediately after creation.
     * @type {KeyExportStatus}
     * @memberof CreateExportResponse
     */
    'status': KeyExportStatus;
    /**
     * Timestamp after which this key export request is no longer valid.
     * @type {string}
     * @memberof CreateExportResponse
     */
    'expires_at': string;
}

