/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { HireParticipantRole } from './hire-participant-role';




/**
 * Reviewed custody rules for the pact vault.
 * @export
 * @interface CustodyTerms
 */
export interface CustodyTerms {
    /**
     * 
     * @type {string}
     * @memberof CustodyTerms
     */
    'model': string;
    /**
     * 
     * @type {number}
     * @memberof CustodyTerms
     */
    'threshold': number;
    /**
     * 
     * @type {Array<HireParticipantRole>}
     * @memberof CustodyTerms
     */
    'participants': Array<HireParticipantRole>;
    /**
     * 
     * @type {string}
     * @memberof CustodyTerms
     */
    'vault_address': string;
    /**
     * 
     * @type {Array<HireParticipantRole>}
     * @memberof CustodyTerms
     */
    'normal_settlement_signers': Array<HireParticipantRole>;
    /**
     * 
     * @type {Array<HireParticipantRole>}
     * @memberof CustodyTerms
     */
    'refund_or_dispute_signers': Array<HireParticipantRole>;
}

