/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { DelegationStatus } from './delegation-status';




/**
 * Delegation response payload.
 * @export
 * @interface DelegationRead
 */
export interface DelegationRead {
    /**
     * The delegation ID.
     * @type {string}
     * @memberof DelegationRead
     */
    'id': string;
    /**
     * The ID of the principal that created this delegation (the wallet owner).
     * @type {string}
     * @memberof DelegationRead
     */
    'owner_id': string;
    /**
     * The ID of the principal that received access.
     * @type {string}
     * @memberof DelegationRead
     */
    'operator_id': string;
    /**
     * The wallet this delegation grants access to.
     * @type {string}
     * @memberof DelegationRead
     */
    'wallet_id': string;
    /**
     * The list of permissions granted by this delegation.
     * @type {Array<string>}
     * @memberof DelegationRead
     */
    'permissions': Array<string>;
    /**
     * Delegation-scoped policies associated with this delegation.
     * @type {Array<{ [key: string]: any; }>}
     * @memberof DelegationRead
     */
    'policies'?: Array<{ [key: string]: any; }>;
    /**
     * The delegation status. Possible values: `active`, `revoked`, `expired`.
     * @type {DelegationStatus}
     * @memberof DelegationRead
     */
    'status': DelegationStatus;
    /**
     * Whether this delegation is currently frozen. `true`: the operator cannot perform any actions. `false`: the delegation is active.
     * @type {boolean}
     * @memberof DelegationRead
     */
    'frozen'?: boolean;
    /**
     * The reason the delegation was frozen, if set.
     * @type {string}
     * @memberof DelegationRead
     */
    'freeze_reason'?: string;
    /**
     * The timestamp when the delegation was frozen, in ISO 8601 format. Null if not frozen.
     * @type {string}
     * @memberof DelegationRead
     */
    'frozen_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof DelegationRead
     */
    'expires_at': string | null;
    /**
     * 
     * @type {string}
     * @memberof DelegationRead
     */
    'revoked_at': string | null;
    /**
     * The timestamp when the delegation was created, in ISO 8601 format.
     * @type {string}
     * @memberof DelegationRead
     */
    'created_at': string;
    /**
     * The timestamp when the delegation was last updated, in ISO 8601 format.
     * @type {string}
     * @memberof DelegationRead
     */
    'updated_at': string;
}

