/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { DelegationPermission } from './delegation-permission';

// @ts-ignore
import type { InlinePolicyCreate } from './inline-policy-create';




/**
 * Request payload for creating a delegation.
 * @export
 * @interface DelegationCreate
 */
export interface DelegationCreate {
    /**
     * The ID of the principal receiving wallet access.
     * @type {string}
     * @memberof DelegationCreate
     */
    'operator_id': string;
    /**
     * The wallet to delegate access to. The wallet ID can be retrieved by calling the List all wallets operation.
     * @type {string}
     * @memberof DelegationCreate
     */
    'wallet_id': string;
    /**
     * The permissions to grant. At least one is required. Valid values: `read:wallet`, `operator`, `write:transaction`, `write:transfer`, `write:contract_call`, `write:manage`, `write:policy`.
     * @type {Array<DelegationPermission>}
     * @memberof DelegationCreate
     */
    'permissions': Array<DelegationPermission>;
    /**
     * Optional delegation-scoped policies to create alongside the delegation.
     * @type {Array<InlinePolicyCreate>}
     * @memberof DelegationCreate
     */
    'policies'?: Array<InlinePolicyCreate>;
    /**
     * The expiry timestamp for this delegation, in ISO 8601 format. If omitted, the delegation does not expire.
     * @type {string}
     * @memberof DelegationCreate
     */
    'expires_at'?: string;
}

