/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { DelegationUsageLimitSummary } from './delegation-usage-limit-summary';




/**
 * DelegationSpendSummary
 * @export
 * @interface DelegationSpendSummary
 */
export interface DelegationSpendSummary {
    /**
     * The delegation ID.
     * @type {string}
     * @memberof DelegationSpendSummary
     */
    'delegation_id': string;
    /**
     * The operator\'s principal ID.
     * @type {string}
     * @memberof DelegationSpendSummary
     */
    'operator_id': string;
    /**
     * Whether the delegation is currently frozen. `true`: frozen. `false`: active.
     * @type {boolean}
     * @memberof DelegationSpendSummary
     */
    'frozen': boolean;
    /**
     * The total amount spent today by this delegation, as a decimal string.
     * @type {string}
     * @memberof DelegationSpendSummary
     */
    'daily_spent': string;
    /**
     * The daily spending limit for this delegation. Null if no daily limit is set.
     * @type {string}
     * @memberof DelegationSpendSummary
     */
    'daily_limit'?: string;
    /**
     * The total amount spent this month by this delegation, as a decimal string.
     * @type {string}
     * @memberof DelegationSpendSummary
     */
    'monthly_spent': string;
    /**
     * The monthly spending limit for this delegation. Null if no monthly limit is set.
     * @type {string}
     * @memberof DelegationSpendSummary
     */
    'monthly_limit'?: string;
    /**
     * Per-window usage limit snapshots for delegation policies, including used/limit/remaining.
     * @type {Array<DelegationUsageLimitSummary>}
     * @memberof DelegationSpendSummary
     */
    'usage_limits_summary'?: Array<DelegationUsageLimitSummary>;
}

