/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Delegation permission vocabulary.
 * @export
 * @enum {string}
 */
export const DelegationPermission = {
    operator: 'operator' as const,
    readwallet: 'read:wallet' as const,
    writetransaction: 'write:transaction' as const,
    writetransfer: 'write:transfer' as const,
    writecontract_call: 'write:contract_call' as const,
    writemessage_sign: 'write:message_sign' as const,
    writemanage: 'write:manage' as const,
    writepolicy: 'write:policy' as const,
} as const;

export type DelegationPermission = typeof DelegationPermission[keyof typeof DelegationPermission];

