/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Lifecycle states for a delegation.
 * @export
 * @enum {string}
 */
export const DelegationStatus = {
    active: 'active' as const,
    revoked: 'revoked' as const,
    expired: 'expired' as const,
} as const;

export type DelegationStatus = typeof DelegationStatus[keyof typeof DelegationStatus];

