/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { DelegationPermission } from './delegation-permission';




/**
 * Request payload for updating a delegation.  Note: policies cannot be updated via delegation APIs. Use the policy APIs (PATCH /policies/{id}) to manage delegation-scoped policies individually.
 * @export
 * @interface DelegationUpdate
 */
export interface DelegationUpdate {
    /**
     * The updated list of permissions to grant. Replaces the existing permissions. At least one is required if provided.
     * @type {Array<DelegationPermission>}
     * @memberof DelegationUpdate
     */
    'permissions'?: Array<DelegationPermission>;
    /**
     * The updated expiry timestamp for this delegation, in ISO 8601 format. Set to null to remove the expiry.
     * @type {string}
     * @memberof DelegationUpdate
     */
    'expires_at'?: string;
}

