/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Deliverable required for a milestone.
 * @export
 * @interface DeliverableSpec
 */
export interface DeliverableSpec {
    /**
     * 
     * @type {string}
     * @memberof DeliverableSpec
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof DeliverableSpec
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof DeliverableSpec
     */
    'format'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeliverableSpec
     */
    'delivery_method': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DeliverableSpec
     */
    'quality_criteria'?: Array<string>;
}

