/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { Fee } from './fee';




/**
 * Request payload for cancelling a transaction.  fee is required for Broadcasting (RBF drop); omit for pre-broadcast cancel.
 * @export
 * @interface DropTransactionRequest
 */
export interface DropTransactionRequest {
    /**
     * A client-supplied identifier for the replacement transaction.
     * @type {string}
     * @memberof DropTransactionRequest
     */
    'request_id'?: string;
    /**
     * Custom fee parameters for the replacement transaction. Required when the transaction is broadcasting (RBF drop).
     * @type {Fee}
     * @memberof DropTransactionRequest
     */
    'fee'?: Fee;
    /**
     * The provider-side transaction ID to cancel. The transaction ID can be retrieved from the transfer or contract call response.
     * @type {string}
     * @memberof DropTransactionRequest
     */
    'cobo_transaction_id'?: string;
}

