/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { FeeRequest } from './fee-request';




/**
 * Request payload for cancelling a transaction.  fee is required for Broadcasting (RBF drop); omit for pre-broadcast cancel.
 * @export
 * @interface DropTransactionRequest
 */
export interface DropTransactionRequest {
    /**
     * A client-supplied identifier for the replacement transaction.
     * @type {string}
     * @memberof DropTransactionRequest
     */
    'request_id'?: string;
    /**
     * 
     * @type {FeeRequest}
     * @memberof DropTransactionRequest
     */
    'fee'?: FeeRequest | null;
    /**
     * The provider-side transaction ID to cancel. The transaction ID can be retrieved from the transfer or contract call response.
     * @type {string}
     * @memberof DropTransactionRequest
     */
    'cobo_transaction_id'?: string;
}

