/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Request payload for transfer fee estimation.
 * @export
 * @interface EstimateTransferFeeRequest
 */
export interface EstimateTransferFeeRequest {
    /**
     * The destination on-chain address.
     * @type {string}
     * @memberof EstimateTransferFeeRequest
     */
    'dst_addr': string;
    /**
     * The transfer amount as a decimal string.
     * @type {string}
     * @memberof EstimateTransferFeeRequest
     */
    'amount': string;
    /**
     * The Cobo token ID (for example, `ETH`, `SETH`). Defaults to `SETH`.
     * @type {string}
     * @memberof EstimateTransferFeeRequest
     */
    'token_id'?: string;
    /**
     * The chain ID. Automatically resolved from `token_id` if omitted.
     * @type {string}
     * @memberof EstimateTransferFeeRequest
     */
    'chain_id'?: string;
    /**
     * The source address. If omitted, the wallet\'s most recently created address for this chain is used.
     * @type {string}
     * @memberof EstimateTransferFeeRequest
     */
    'src_addr'?: string;
}

