/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Request body for the eth_call proxy endpoint.
 * @export
 * @interface EthCallRequest
 */
export interface EthCallRequest {
    /**
     * Cobo chain ID (e.g. `SETH`, `BASE_ETH`).
     * @type {string}
     * @memberof EthCallRequest
     */
    'chain_id': string;
    /**
     * Contract address to call.
     * @type {string}
     * @memberof EthCallRequest
     */
    'to': string;
    /**
     * ABI-encoded calldata as a hex string (with or without `0x` prefix).
     * @type {string}
     * @memberof EthCallRequest
     */
    'data': string;
    /**
     * Optional msg.sender override.
     * @type {string}
     * @memberof EthCallRequest
     */
    'from'?: string;
    /**
     * Block tag or hex block number (default: `latest`).
     * @type {string}
     * @memberof EthCallRequest
     */
    'block'?: string;
}

