/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Optional EVM Legacy fee parameters for transfers.
 * @export
 * @interface EVMLegacyFeeRequest
 */
export interface EVMLegacyFeeRequest {
    /**
     * The fee type. Must be `EVM_Legacy`.
     * @type {string}
     * @memberof EVMLegacyFeeRequest
     */
    'fee_type'?: string;
    /**
     * The gas price, in wei.
     * @type {string}
     * @memberof EVMLegacyFeeRequest
     */
    'gas_price': string;
    /**
     * The gas limit for this transaction.
     * @type {string}
     * @memberof EVMLegacyFeeRequest
     */
    'gas_limit'?: string;
    /**
     * The token ID for fee payment.
     * @type {string}
     * @memberof EVMLegacyFeeRequest
     */
    'token_id': string;
}

