/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Request body for executing a script.
 * @export
 * @interface ExecuteScriptRequest
 */
export interface ExecuteScriptRequest {
    /**
     * 脚本方法名称
     * @type {string}
     * @memberof ExecuteScriptRequest
     */
    'func_name': string;
    /**
     * 脚本参数 (JSON 对象)
     * @type {{ [key: string]: any; }}
     * @memberof ExecuteScriptRequest
     */
    'params'?: { [key: string]: any; };
}

