/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Public representation of an ExternalTransaction (Layer 3 downstream operation).
 * @export
 * @interface ExternalTransactionRead
 */
export interface ExternalTransactionRead {
    /**
     * The external transaction UUID.
     * @type {string}
     * @memberof ExternalTransactionRead
     */
    'id': string;
    /**
     * The parent UserTransaction UUID.
     * @type {string}
     * @memberof ExternalTransactionRead
     */
    'user_transaction_uuid': string;
    /**
     * The operation type (transfer, contract_call, deposit, message_sign).
     * @type {string}
     * @memberof ExternalTransactionRead
     */
    'operation_type': string;
    /**
     * Stage within the UT lifecycle (original, drop, speedup).
     * @type {string}
     * @memberof ExternalTransactionRead
     */
    'stage'?: string;
    /**
     * Downstream provider (waas, pimlico, alchemy).
     * @type {string}
     * @memberof ExternalTransactionRead
     */
    'provider'?: string;
    /**
     * Provider-assigned transaction ID (e.g. WaaS cobo_tx_id).
     * @type {string}
     * @memberof ExternalTransactionRead
     */
    'external_id'?: string;
    /**
     * CAW-side idempotency key sent to the provider.
     * @type {string}
     * @memberof ExternalTransactionRead
     */
    'caw_request_id'?: string;
    /**
     * Downstream status string (provider-specific).
     * @type {string}
     * @memberof ExternalTransactionRead
     */
    'status': string;
    /**
     * On-chain transaction hash, if available.
     * @type {string}
     * @memberof ExternalTransactionRead
     */
    'transaction_hash'?: string;
    /**
     * Additional downstream metadata.
     * @type {{ [key: string]: any; }}
     * @memberof ExternalTransactionRead
     */
    'data'?: { [key: string]: any; };
    /**
     * Creation timestamp.
     * @type {string}
     * @memberof ExternalTransactionRead
     */
    'created_at': string;
    /**
     * Last-updated timestamp.
     * @type {string}
     * @memberof ExternalTransactionRead
     */
    'updated_at': string;
}

