/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * ExternalTransactionStage
 * @export
 * @enum {string}
 */
export const ExternalTransactionStage = {
    original: 'original' as const,
    sign: 'sign' as const,
    broadcast: 'broadcast' as const,
    drop: 'drop' as const,
    speedup: 'speedup' as const,
    delegation: 'delegation' as const,
    userop: 'userop' as const,
    provider_userop: 'provider_userop' as const,
} as const;

export type ExternalTransactionStage = typeof ExternalTransactionStage[keyof typeof ExternalTransactionStage];

