/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * FaucetDepositRequest
 * @export
 * @interface FaucetDepositRequest
 */
export interface FaucetDepositRequest {
    /**
     * Destination address to receive test tokens
     * @type {string}
     * @memberof FaucetDepositRequest
     */
    'address': string;
    /**
     * Token identifier, e.g. SETH_USDC
     * @type {string}
     * @memberof FaucetDepositRequest
     */
    'token_id': string;
}

