/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { FaucetTokenInfo } from './faucet-token-info';




/**
 * FaucetTokenItem
 * @export
 * @interface FaucetTokenItem
 */
export interface FaucetTokenItem {
    /**
     * The Cobo chain ID for this group of faucet tokens (for example, `SOL` or `SETH`). Call the List supported chains operation (`GET /metadata/chains`) to retrieve all supported chain IDs.
     * @type {string}
     * @memberof FaucetTokenItem
     */
    'chain_id': string;
    /**
     * A map of token IDs to their faucet configuration (for example, `{\"SETH_USDC\": {\"deposit_amount\": \"100\", \"daily_limit\": \"500\"}}`).
     * @type {{ [key: string]: FaucetTokenInfo; }}
     * @memberof FaucetTokenItem
     */
    'tokens'?: { [key: string]: FaucetTokenInfo; };
}

