/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * FaucetTokenInfo
 * @export
 * @interface FaucetTokenInfo
 */
export interface FaucetTokenInfo {
    /**
     * The amount of tokens transferred per faucet request, as a decimal string.
     * @type {string}
     * @memberof FaucetTokenInfo
     */
    'deposit_amount': string;
    /**
     * Max total deposit per day (global); null means unlimited
     * @type {string}
     * @memberof FaucetTokenInfo
     */
    'daily_limit'?: string;
}

