/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Standardized fee estimate view (supports both EVM and SOL fields).
 * @export
 * @interface FeeEstimateRead
 */
export interface FeeEstimateRead {
    /**
     * The maximum total fee per gas for EIP-1559 transactions, in wei.
     * @type {string}
     * @memberof FeeEstimateRead
     */
    'max_fee_per_gas'?: string;
    /**
     * The maximum priority fee (tip) per gas for EIP-1559 transactions, in wei.
     * @type {string}
     * @memberof FeeEstimateRead
     */
    'max_priority_fee_per_gas'?: string;
    /**
     * The estimated gas limit for EIP-1559 transactions.
     * @type {string}
     * @memberof FeeEstimateRead
     */
    'gas_limit'?: string;
    /**
     * The price per compute unit for Solana transactions, in microlamports.
     * @type {string}
     * @memberof FeeEstimateRead
     */
    'compute_unit_price'?: string;
    /**
     * The maximum compute units for Solana transactions.
     * @type {string}
     * @memberof FeeEstimateRead
     */
    'compute_unit_limit'?: string;
    /**
     * The total estimated fee amount as a decimal string.
     * @type {string}
     * @memberof FeeEstimateRead
     */
    'fee_amount'?: string;
}

