/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { EIP1559FeeRequest } from './eip1559-fee-request';

// @ts-ignore
import type { SOLFeeRequest } from './solfee-request';


// @ts-ignore
import type { EIP1559FeeRequest } from './EIP1559FeeRequest';
// @ts-ignore
import type { SOLFeeRequest } from './SOLFeeRequest';

/**
 * @type Fee
 * Optional fee parameters (EIP-1559 or SOL). If omitted, the network default is used.
 * @export
 */
export type Fee = EIP1559FeeRequest | SOLFeeRequest;


