/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Client review actions for a delivery.
 * @export
 * @enum {string}
 */
export const HireDeliveryReviewAction = {
    approve: 'approve' as const,
    request_revision: 'request_revision' as const,
    reject: 'reject' as const,
} as const;

export type HireDeliveryReviewAction = typeof HireDeliveryReviewAction[keyof typeof HireDeliveryReviewAction];

