/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Request cancellation before first delivery.
 * @export
 * @interface HireCancellationRequest
 */
export interface HireCancellationRequest {
    /**
     * 
     * @type {string}
     * @memberof HireCancellationRequest
     */
    'reason'?: string;
}

