/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Record one party\'s review acknowledgment or withdrawal.
 * @export
 * @interface HireAcknowledgeRequest
 */
export interface HireAcknowledgeRequest {
    /**
     * 
     * @type {string}
     * @memberof HireAcknowledgeRequest
     */
    'review_id': string;
    /**
     * 
     * @type {string}
     * @memberof HireAcknowledgeRequest
     */
    'action': HireAcknowledgeRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof HireAcknowledgeRequest
     */
    'message'?: string;
}

export const HireAcknowledgeRequestActionEnum = {
    acknowledge: 'acknowledge' as const,
    withdraw: 'withdraw' as const,
} as const;

export type HireAcknowledgeRequestActionEnum = typeof HireAcknowledgeRequestActionEnum[keyof typeof HireAcknowledgeRequestActionEnum];

