/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { HireSettlementRecord } from './hire-settlement-record';




/**
 * Settlement proposal snapshot returned from the API.
 * @export
 * @interface HireSettlementProposalRead
 */
export interface HireSettlementProposalRead {
    /**
     * 
     * @type {string}
     * @memberof HireSettlementProposalRead
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof HireSettlementProposalRead
     */
    'proposed_by': string;
    /**
     * 
     * @type {string}
     * @memberof HireSettlementProposalRead
     */
    'client_amount': string;
    /**
     * 
     * @type {string}
     * @memberof HireSettlementProposalRead
     */
    'service_amount': string;
    /**
     * 
     * @type {string}
     * @memberof HireSettlementProposalRead
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireSettlementProposalRead
     */
    'status': string;
    /**
     * 
     * @type {string}
     * @memberof HireSettlementProposalRead
     */
    'matched_with_proposal_id'?: string;
    /**
     * 
     * @type {HireSettlementRecord}
     * @memberof HireSettlementProposalRead
     */
    'applied_settlement'?: HireSettlementRecord;
    /**
     * 
     * @type {string}
     * @memberof HireSettlementProposalRead
     */
    'applied_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireSettlementProposalRead
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof HireSettlementProposalRead
     */
    'updated_at': string;
}

