/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { HireResolution } from './hire-resolution';

// @ts-ignore
import type { HireSettlementSplit } from './hire-settlement-split';




/**
 * Issue a pact-agent arbitration ruling.
 * @export
 * @interface HireArbitrationRulingCreateRequest
 */
export interface HireArbitrationRulingCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof HireArbitrationRulingCreateRequest
     */
    'dispute_id': string;
    /**
     * 
     * @type {HireResolution}
     * @memberof HireArbitrationRulingCreateRequest
     */
    'resolution'?: HireResolution;
    /**
     * 
     * @type {HireSettlementSplit}
     * @memberof HireArbitrationRulingCreateRequest
     */
    'custom_split'?: HireSettlementSplit;
    /**
     * 
     * @type {string}
     * @memberof HireArbitrationRulingCreateRequest
     */
    'message'?: string;
}

