/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { Artifact } from './artifact';

// @ts-ignore
import type { HireResolution } from './hire-resolution';

// @ts-ignore
import type { HireSettlementSplit } from './hire-settlement-split';




/**
 * Respond to an open dispute.
 * @export
 * @interface HireDisputeResponseCreateRequest
 */
export interface HireDisputeResponseCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof HireDisputeResponseCreateRequest
     */
    'dispute_id': string;
    /**
     * 
     * @type {Array<Artifact>}
     * @memberof HireDisputeResponseCreateRequest
     */
    'counter_evidence'?: Array<Artifact>;
    /**
     * 
     * @type {HireResolution}
     * @memberof HireDisputeResponseCreateRequest
     */
    'proposed_resolution'?: HireResolution;
    /**
     * 
     * @type {HireSettlementSplit}
     * @memberof HireDisputeResponseCreateRequest
     */
    'custom_split'?: HireSettlementSplit;
    /**
     * 
     * @type {string}
     * @memberof HireDisputeResponseCreateRequest
     */
    'message': string;
}

