/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Trigger Pact Service review for a submitted pact.
 * @export
 * @interface HireReviewRequest
 */
export interface HireReviewRequest {
    /**
     * 
     * @type {number}
     * @memberof HireReviewRequest
     */
    'review_expiry_seconds'?: number;
}

