/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { Artifact } from './artifact';

// @ts-ignore
import type { HireArbitrationRulingRecord } from './hire-arbitration-ruling-record';

// @ts-ignore
import type { HireDisputeResponseRecord } from './hire-dispute-response-record';




/**
 * Dispute snapshot returned from the API.
 * @export
 * @interface HireDisputeRead
 */
export interface HireDisputeRead {
    /**
     * 
     * @type {string}
     * @memberof HireDisputeRead
     */
    'dispute_id': string;
    /**
     * 
     * @type {string}
     * @memberof HireDisputeRead
     */
    'opened_by': string;
    /**
     * 
     * @type {string}
     * @memberof HireDisputeRead
     */
    'dispute_type': string;
    /**
     * 
     * @type {string}
     * @memberof HireDisputeRead
     */
    'requested_resolution': string;
    /**
     * 
     * @type {Array<Artifact>}
     * @memberof HireDisputeRead
     */
    'evidence'?: Array<Artifact>;
    /**
     * 
     * @type {string}
     * @memberof HireDisputeRead
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof HireDisputeRead
     */
    'status': string;
    /**
     * 
     * @type {HireDisputeResponseRecord}
     * @memberof HireDisputeRead
     */
    'response'?: HireDisputeResponseRecord;
    /**
     * 
     * @type {HireArbitrationRulingRecord}
     * @memberof HireDisputeRead
     */
    'ruling'?: HireArbitrationRulingRecord;
    /**
     * 
     * @type {string}
     * @memberof HireDisputeRead
     */
    'response_received_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireDisputeRead
     */
    'ruled_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireDisputeRead
     */
    'settled_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireDisputeRead
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof HireDisputeRead
     */
    'updated_at': string;
}

