/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Record a settlement proposal during execution.
 * @export
 * @interface HireSettlementProposalCreateRequest
 */
export interface HireSettlementProposalCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof HireSettlementProposalCreateRequest
     */
    'client_amount': string;
    /**
     * 
     * @type {string}
     * @memberof HireSettlementProposalCreateRequest
     */
    'service_amount': string;
    /**
     * 
     * @type {string}
     * @memberof HireSettlementProposalCreateRequest
     */
    'message'?: string;
}

