/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { DisputeResolutionSpec } from './dispute-resolution-spec';

// @ts-ignore
import type { ExecutionPlan } from './execution-plan';

// @ts-ignore
import type { MilestoneSpec } from './milestone-spec';

// @ts-ignore
import type { PaymentTerms } from './payment-terms';

// @ts-ignore
import type { VerificationSpec } from './verification-spec';

// @ts-ignore
import type { WorkScope } from './work-scope';




/**
 * Partial update representation for negotiated or reviewed changes.
 * @export
 * @interface HirePactSpecPatchInput
 */
export interface HirePactSpecPatchInput {
    /**
     * 
     * @type {WorkScope}
     * @memberof HirePactSpecPatchInput
     */
    'scope'?: WorkScope;
    /**
     * 
     * @type {ExecutionPlan}
     * @memberof HirePactSpecPatchInput
     */
    'execution_plan'?: ExecutionPlan;
    /**
     * 
     * @type {Array<MilestoneSpec>}
     * @memberof HirePactSpecPatchInput
     */
    'milestones'?: Array<MilestoneSpec>;
    /**
     * 
     * @type {PaymentTerms}
     * @memberof HirePactSpecPatchInput
     */
    'payment'?: PaymentTerms;
    /**
     * 
     * @type {VerificationSpec}
     * @memberof HirePactSpecPatchInput
     */
    'verification'?: VerificationSpec;
    /**
     * 
     * @type {DisputeResolutionSpec}
     * @memberof HirePactSpecPatchInput
     */
    'dispute_resolution'?: DisputeResolutionSpec;
    /**
     * 
     * @type {number}
     * @memberof HirePactSpecPatchInput
     */
    'duration_seconds'?: number;
    /**
     * 
     * @type {number}
     * @memberof HirePactSpecPatchInput
     */
    'funding_deadline_seconds'?: number;
    /**
     * 
     * @type {number}
     * @memberof HirePactSpecPatchInput
     */
    'revision_limit'?: number;
    /**
     * 
     * @type {number}
     * @memberof HirePactSpecPatchInput
     */
    'auto_approve_after_seconds'?: number;
}

