/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Compact list representation for hire pacts.
 * @export
 * @interface HireSummary
 */
export interface HireSummary {
    /**
     * 
     * @type {string}
     * @memberof HireSummary
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof HireSummary
     */
    'protocol_pact_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireSummary
     */
    'status': string;
    /**
     * 
     * @type {string}
     * @memberof HireSummary
     */
    'review_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireSummary
     */
    'review_action'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireSummary
     */
    'vault_state': string;
    /**
     * 
     * @type {string}
     * @memberof HireSummary
     */
    'vault_address'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireSummary
     */
    'client_principal_id': string;
    /**
     * 
     * @type {string}
     * @memberof HireSummary
     */
    'service_principal_id': string;
    /**
     * 
     * @type {string}
     * @memberof HireSummary
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof HireSummary
     */
    'updated_at': string;
}

