/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { HireResolution } from './hire-resolution';

// @ts-ignore
import type { HireSettlementSplit } from './hire-settlement-split';




/**
 * Structured arbitration ruling persisted on a dispute.
 * @export
 * @interface HireArbitrationRulingRecord
 */
export interface HireArbitrationRulingRecord {
    /**
     * 
     * @type {string}
     * @memberof HireArbitrationRulingRecord
     */
    'dispute_id': string;
    /**
     * 
     * @type {HireResolution}
     * @memberof HireArbitrationRulingRecord
     */
    'resolution': HireResolution;
    /**
     * 
     * @type {string}
     * @memberof HireArbitrationRulingRecord
     */
    'client_amount': string;
    /**
     * 
     * @type {string}
     * @memberof HireArbitrationRulingRecord
     */
    'service_amount': string;
    /**
     * 
     * @type {HireSettlementSplit}
     * @memberof HireArbitrationRulingRecord
     */
    'custom_split'?: HireSettlementSplit;
    /**
     * 
     * @type {string}
     * @memberof HireArbitrationRulingRecord
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireArbitrationRulingRecord
     */
    'ruled_at': string;
}

