/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { HireNotificationPreference } from './hire-notification-preference';




/**
 * Stored client submission metadata.
 * @export
 * @interface HireSubmissionRecord
 */
export interface HireSubmissionRecord {
    /**
     * 
     * @type {string}
     * @memberof HireSubmissionRecord
     */
    'service_agent_card_url': string;
    /**
     * 
     * @type {string}
     * @memberof HireSubmissionRecord
     */
    'client_refund_address': string;
    /**
     * 
     * @type {string}
     * @memberof HireSubmissionRecord
     */
    'service_payout_address': string;
    /**
     * 
     * @type {HireNotificationPreference}
     * @memberof HireSubmissionRecord
     */
    'notification_preference'?: HireNotificationPreference;
    /**
     * 
     * @type {string}
     * @memberof HireSubmissionRecord
     */
    'push_notification_url'?: string;
}

