/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Client notification preference for execution updates.
 * @export
 * @enum {string}
 */
export const HireNotificationPreference = {
    stream: 'stream' as const,
    push: 'push' as const,
    poll: 'poll' as const,
} as const;

export type HireNotificationPreference = typeof HireNotificationPreference[keyof typeof HireNotificationPreference];

