/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { HireSummary } from './hire-summary';




/**
 * Paginated hire list wrapper.
 * @export
 * @interface HireListResponse
 */
export interface HireListResponse {
    /**
     * 
     * @type {Array<HireSummary>}
     * @memberof HireListResponse
     */
    'pacts': Array<HireSummary>;
}

