/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { Artifact } from './artifact';

// @ts-ignore
import type { HireDisputeType } from './hire-dispute-type';

// @ts-ignore
import type { HireResolution } from './hire-resolution';




/**
 * Open a formal dispute for an active or disputed pact.
 * @export
 * @interface HireDisputeCreateRequest
 */
export interface HireDisputeCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof HireDisputeCreateRequest
     */
    'dispute_id': string;
    /**
     * 
     * @type {HireDisputeType}
     * @memberof HireDisputeCreateRequest
     */
    'dispute_type': HireDisputeType;
    /**
     * 
     * @type {HireResolution}
     * @memberof HireDisputeCreateRequest
     */
    'requested_resolution': HireResolution;
    /**
     * 
     * @type {Array<Artifact>}
     * @memberof HireDisputeCreateRequest
     */
    'evidence'?: Array<Artifact>;
    /**
     * 
     * @type {string}
     * @memberof HireDisputeCreateRequest
     */
    'message': string;
}

