/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Dispute categories from the Hire protocol.
 * @export
 * @enum {string}
 */
export const HireDisputeType = {
    non_delivery: 'non_delivery' as const,
    quality: 'quality' as const,
    scope_change: 'scope_change' as const,
    non_payment: 'non_payment' as const,
    non_review: 'non_review' as const,
} as const;

export type HireDisputeType = typeof HireDisputeType[keyof typeof HireDisputeType];

