/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Custom percentage split for a dispute response.
 * @export
 * @interface HireSettlementSplit
 */
export interface HireSettlementSplit {
    /**
     * 
     * @type {string}
     * @memberof HireSettlementSplit
     */
    'client_percent': string;
    /**
     * 
     * @type {string}
     * @memberof HireSettlementSplit
     */
    'service_percent': string;
}

