/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Settlement and dispute resolution outcomes.
 * @export
 * @enum {string}
 */
export const HireResolution = {
    full_refund: 'full_refund' as const,
    partial_refund: 'partial_refund' as const,
    full_payment: 'full_payment' as const,
    partial_payment: 'partial_payment' as const,
    custom_split: 'custom_split' as const,
} as const;

export type HireResolution = typeof HireResolution[keyof typeof HireResolution];

