/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { CustodyTerms } from './custody-terms';

// @ts-ignore
import type { HireDeliveryRead } from './hire-delivery-read';

// @ts-ignore
import type { HireDisputeRead } from './hire-dispute-read';

// @ts-ignore
import type { HireMilestoneRead } from './hire-milestone-read';

// @ts-ignore
import type { HirePactSpecOutput } from './hire-pact-spec-output';

// @ts-ignore
import type { HirePactSpecPatchOutput } from './hire-pact-spec-patch-output';

// @ts-ignore
import type { HireSettlementProposalRead } from './hire-settlement-proposal-read';

// @ts-ignore
import type { NegotiatedSpecPatchEntryOutput } from './negotiated-spec-patch-entry-output';




/**
 * Top-level hire pact representation returned from the API.
 * @export
 * @interface HireRead
 */
export interface HireRead {
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'client_principal_id': string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'service_principal_id': string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'pact_agent_principal_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'protocol_pact_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'status': string;
    /**
     * 
     * @type {HirePactSpecOutput}
     * @memberof HireRead
     */
    'negotiated_spec': HirePactSpecOutput;
    /**
     * 
     * @type {Array<NegotiatedSpecPatchEntryOutput>}
     * @memberof HireRead
     */
    'negotiated_patch_history': Array<NegotiatedSpecPatchEntryOutput>;
    /**
     * 
     * @type {HirePactSpecOutput}
     * @memberof HireRead
     */
    'reviewed_spec'?: HirePactSpecOutput;
    /**
     * 
     * @type {HirePactSpecPatchOutput}
     * @memberof HireRead
     */
    'review_modifications_patch'?: HirePactSpecPatchOutput;
    /**
     * 
     * @type {CustodyTerms}
     * @memberof HireRead
     */
    'reviewed_custody_terms'?: CustodyTerms;
    /**
     * 
     * @type {Array<string>}
     * @memberof HireRead
     */
    'review_concerns'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'review_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'review_action'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'enforceability_assessment'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'rejection_reason'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'service_agent_card_url': string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'service_agent_endpoint_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'client_refund_address': string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'service_payout_address': string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'notification_preference': string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'push_notification_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'client_ack_status': string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'service_ack_status': string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'client_acknowledged_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'service_acknowledged_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'review_expires_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'acknowledgment_deadline_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'funding_deadline_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'activated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'expires_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'completed_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'cancelled_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'first_delivery_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'last_delivery_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'vault_state': string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'vault_address'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'funding_tx_hash'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'total_funded'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'funding_token'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'funding_chain'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'current_dispute_id'?: string;
    /**
     * 
     * @type {Array<HireMilestoneRead>}
     * @memberof HireRead
     */
    'milestones'?: Array<HireMilestoneRead>;
    /**
     * 
     * @type {Array<HireDeliveryRead>}
     * @memberof HireRead
     */
    'deliveries'?: Array<HireDeliveryRead>;
    /**
     * 
     * @type {Array<HireDisputeRead>}
     * @memberof HireRead
     */
    'disputes'?: Array<HireDisputeRead>;
    /**
     * 
     * @type {Array<HireSettlementProposalRead>}
     * @memberof HireRead
     */
    'settlement_proposals'?: Array<HireSettlementProposalRead>;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof HireRead
     */
    'updated_at': string;
}

