/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Settlement kinds emitted by the Pact Service.
 * @export
 * @enum {string}
 */
export const HireSettlementType = {
    milestone_payment: 'milestone_payment' as const,
    final_payment: 'final_payment' as const,
    refund: 'refund' as const,
    dispute_resolution: 'dispute_resolution' as const,
} as const;

export type HireSettlementType = typeof HireSettlementType[keyof typeof HireSettlementType];

