/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { Artifact } from './artifact';




/**
 * Delivery snapshot returned from the API.
 * @export
 * @interface HireDeliveryRead
 */
export interface HireDeliveryRead {
    /**
     * 
     * @type {string}
     * @memberof HireDeliveryRead
     */
    'delivery_id': string;
    /**
     * 
     * @type {string}
     * @memberof HireDeliveryRead
     */
    'milestone_id': string;
    /**
     * 
     * @type {Array<Artifact>}
     * @memberof HireDeliveryRead
     */
    'artifacts': Array<Artifact>;
    /**
     * 
     * @type {string}
     * @memberof HireDeliveryRead
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireDeliveryRead
     */
    'delivered_at': string;
    /**
     * 
     * @type {string}
     * @memberof HireDeliveryRead
     */
    'received_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireDeliveryRead
     */
    'forwarded_to_client_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireDeliveryRead
     */
    'review_action'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireDeliveryRead
     */
    'revision_notes'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireDeliveryRead
     */
    'rejection_reason'?: string;
    /**
     * 
     * @type {string}
     * @memberof HireDeliveryRead
     */
    'reviewed_at'?: string;
}

