/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Immutable hire event row returned from the API.
 * @export
 * @interface HireEventRead
 */
export interface HireEventRead {
    /**
     * 
     * @type {string}
     * @memberof HireEventRead
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof HireEventRead
     */
    'event_type': string;
    /**
     * 
     * @type {string}
     * @memberof HireEventRead
     */
    'actor_role'?: string;
    /**
     * 
     * @type {object}
     * @memberof HireEventRead
     */
    'payload'?: object;
    /**
     * 
     * @type {string}
     * @memberof HireEventRead
     */
    'created_at': string;
}

