/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PolicyType } from './policy-type';




/**
 * Inline policy payload used during delegation/pact create.
 * @export
 * @interface InlinePolicyCreate
 */
export interface InlinePolicyCreate {
    /**
     * 
     * @type {string}
     * @memberof InlinePolicyCreate
     */
    'name': string;
    /**
     * 
     * @type {PolicyType}
     * @memberof InlinePolicyCreate
     */
    'type': PolicyType;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof InlinePolicyCreate
     */
    'rules'?: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof InlinePolicyCreate
     */
    'priority'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof InlinePolicyCreate
     */
    'is_active'?: boolean;
}

