/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { KeyExportStatus } from './key-export-status';

// @ts-ignore
import type { TssKeyShareGroupSnapshot } from './tss-key-share-group-snapshot';




/**
 * Full detail for a key export.
 * @export
 * @interface KeyExportRead
 */
export interface KeyExportRead {
    /**
     * Unique identifier for this key export request.
     * @type {string}
     * @memberof KeyExportRead
     */
    'export_id': string;
    /**
     * Identifier of the MPC wallet whose keys are being exported.
     * @type {string}
     * @memberof KeyExportRead
     */
    'wallet_id': string;
    /**
     * Identifier of the user or organization that owns the wallet.
     * @type {string}
     * @memberof KeyExportRead
     */
    'owner_id': string;
    /**
     * Identifier of the user who initiated the key export request.
     * @type {string}
     * @memberof KeyExportRead
     */
    'created_by': string;
    /**
     * Current state of the key export request (e.g. pending, approved, rejected, completed).
     * @type {KeyExportStatus}
     * @memberof KeyExportRead
     */
    'status': KeyExportStatus;
    /**
     * URL the wallet owner must visit to approve or reject the export. Null when no authorization step is pending.
     * @type {string}
     * @memberof KeyExportRead
     */
    'authorization_url'?: string;
    /**
     * Human-readable explanation provided when the export was rejected. Null if not rejected.
     * @type {string}
     * @memberof KeyExportRead
     */
    'rejection_reason'?: string;
    /**
     * List of temporary TSS node IDs involved in the reshare operation. Null until nodes are submitted.
     * @type {Array<string>}
     * @memberof KeyExportRead
     */
    'node_ids'?: Array<string>;
    /**
     * Identifier of the TSS key share group used for recovery. Null until the reshare completes.
     * @type {string}
     * @memberof KeyExportRead
     */
    'recovery_group_id'?: string;
    /**
     * Snapshots of the TSS key share groups produced after the reshare completes. Null until the reshare finishes.
     * @type {Array<TssKeyShareGroupSnapshot>}
     * @memberof KeyExportRead
     */
    'tss_key_share_groups'?: Array<TssKeyShareGroupSnapshot>;
    /**
     * Identifier of the underlying TSS reshare request. Null until the reshare is initiated.
     * @type {string}
     * @memberof KeyExportRead
     */
    'reshare_request_id'?: string;
    /**
     * Timestamp after which this key export request is no longer valid and cannot be approved or completed.
     * @type {string}
     * @memberof KeyExportRead
     */
    'expires_at': string;
    /**
     * Timestamp when the export was approved. Null if not yet approved.
     * @type {string}
     * @memberof KeyExportRead
     */
    'approved_at'?: string;
    /**
     * Timestamp when the key export was successfully completed. Null if still in progress.
     * @type {string}
     * @memberof KeyExportRead
     */
    'completed_at'?: string;
    /**
     * Description of any error that caused the export to fail. Null when no error has occurred.
     * @type {string}
     * @memberof KeyExportRead
     */
    'error_message'?: string;
    /**
     * Timestamp when the key export request was created.
     * @type {string}
     * @memberof KeyExportRead
     */
    'created_at': string;
    /**
     * Timestamp when the key export request was last updated.
     * @type {string}
     * @memberof KeyExportRead
     */
    'updated_at': string;
}

