/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Aligned with ``cobo_waas2.models.key_share_holder_group_status.KeyShareHolderGroupStatus``.
 * @export
 * @enum {string}
 */
export const KeyShareHolderGroupStatus = {
    New: 'New' as const,
    Valid: 'Valid' as const,
    Unavailable: 'Unavailable' as const,
} as const;

export type KeyShareHolderGroupStatus = typeof KeyShareHolderGroupStatus[keyof typeof KeyShareHolderGroupStatus];

