/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Aligned with ``cobo_waas2.models.key_share_holder_type.KeyShareHolderType``.
 * @export
 * @enum {string}
 */
export const KeyShareHolderType = {
    Cobo: 'Cobo' as const,
    Mobile: 'Mobile' as const,
    API: 'API' as const,
} as const;

export type KeyShareHolderType = typeof KeyShareHolderType[keyof typeof KeyShareHolderType];

