/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * KnowledgeSearchType
 * @export
 * @enum {string}
 */
export const KnowledgeSearchType = {
    vector: 'vector' as const,
    keyword: 'keyword' as const,
    hybrid: 'hybrid' as const,
} as const;

export type KnowledgeSearchType = typeof KnowledgeSearchType[keyof typeof KnowledgeSearchType];

