/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Supported message signing destination types.
 * @export
 * @enum {string}
 */
export const MessageSignDestType = {
    eip712: 'eip712' as const,
} as const;

export type MessageSignDestType = typeof MessageSignDestType[keyof typeof MessageSignDestType];

