/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { DeliverableSpec } from './deliverable-spec';




/**
 * Milestone and payment structure.
 * @export
 * @interface MilestoneSpec
 */
export interface MilestoneSpec {
    /**
     * 
     * @type {string}
     * @memberof MilestoneSpec
     */
    'milestone_id': string;
    /**
     * 
     * @type {string}
     * @memberof MilestoneSpec
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof MilestoneSpec
     */
    'description': string;
    /**
     * 
     * @type {Array<DeliverableSpec>}
     * @memberof MilestoneSpec
     */
    'deliverables': Array<DeliverableSpec>;
    /**
     * 
     * @type {string}
     * @memberof MilestoneSpec
     */
    'payment_amount': string;
    /**
     * 
     * @type {string}
     * @memberof MilestoneSpec
     */
    'payment_token': string;
    /**
     * 
     * @type {string}
     * @memberof MilestoneSpec
     */
    'payment_chain': string;
    /**
     * 
     * @type {number}
     * @memberof MilestoneSpec
     */
    'deadline_seconds'?: number;
    /**
     * 
     * @type {string}
     * @memberof MilestoneSpec
     */
    'deadline_mode'?: string;
    /**
     * 
     * @type {number}
     * @memberof MilestoneSpec
     */
    'review_deadline_seconds'?: number;
}

