/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * MPP session details returned by the backend after a successful channel open action.
 * @export
 * @interface MppSessionInfo
 */
export interface MppSessionInfo {
    /**
     * On-chain address of the payer who opened the payment channel.
     * @type {string}
     * @memberof MppSessionInfo
     */
    'payer_address': string;
    /**
     * Cobo chain ID on which the payment channel was opened (e.g. \'ETH\' for Ethereum mainnet). Call the List supported chains operation (GET /metadata/chains) to retrieve all supported chain IDs.
     * @type {string}
     * @memberof MppSessionInfo
     */
    'chain_id': string;
    /**
     * Unique identifier of the opened payment channel. May be absent if the channel is not yet confirmed on-chain.
     * @type {string}
     * @memberof MppSessionInfo
     */
    'channel_id'?: string;
}

