/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Parsed MPP Payment challenge from WWW-Authenticate header.
 * @export
 * @interface MppChallenge
 */
export interface MppChallenge {
    /**
     * 
     * @type {string}
     * @memberof MppChallenge
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof MppChallenge
     */
    'realm': string;
    /**
     * 
     * @type {string}
     * @memberof MppChallenge
     */
    'method': string;
    /**
     * 
     * @type {string}
     * @memberof MppChallenge
     */
    'intent': string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof MppChallenge
     */
    'request': { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof MppChallenge
     */
    'request_b64': string;
    /**
     * 
     * @type {string}
     * @memberof MppChallenge
     */
    'expires'?: string;
    /**
     * 
     * @type {string}
     * @memberof MppChallenge
     */
    'description'?: string;
}

