/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { HirePactSpecPatchOutput } from './hire-pact-spec-patch-output';

// @ts-ignore
import type { HireParticipantRole } from './hire-participant-role';




/**
 * Chronological record of negotiated spec changes.
 * @export
 * @interface NegotiatedSpecPatchEntryOutput
 */
export interface NegotiatedSpecPatchEntryOutput {
    /**
     * 
     * @type {HireParticipantRole}
     * @memberof NegotiatedSpecPatchEntryOutput
     */
    'actor_role': HireParticipantRole;
    /**
     * 
     * @type {HirePactSpecPatchOutput}
     * @memberof NegotiatedSpecPatchEntryOutput
     */
    'patch': HirePactSpecPatchOutput;
    /**
     * 
     * @type {string}
     * @memberof NegotiatedSpecPatchEntryOutput
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof NegotiatedSpecPatchEntryOutput
     */
    'created_at': string;
}

