/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PactRemaining } from './pact-remaining';

// @ts-ignore
import type { PactStatus } from './pact-status';

// @ts-ignore
import type { PrincipalRead } from './principal-read';




/**
 * Lightweight pact item for list responses.
 * @export
 * @interface PactSummary
 */
export interface PactSummary {
    /**
     * Pact ID.
     * @type {string}
     * @memberof PactSummary
     */
    'id': string;
    /**
     * Pact name.
     * @type {string}
     * @memberof PactSummary
     */
    'name': string;
    /**
     * Natural language intent.
     * @type {string}
     * @memberof PactSummary
     */
    'intent': string;
    /**
     * Raw user input that originated this pact request. For multi-turn conversations, messages are concatenated.
     * @type {string}
     * @memberof PactSummary
     */
    'original_intent'?: string;
    /**
     * Current pact status.
     * @type {PactStatus}
     * @memberof PactSummary
     */
    'status': PactStatus;
    /**
     * Target wallet ID.
     * @type {string}
     * @memberof PactSummary
     */
    'wallet_id': string;
    /**
     * Whether this is the default pact created during provisioning.
     * @type {boolean}
     * @memberof PactSummary
     */
    'is_default'?: boolean;
    /**
     * When the pact was submitted.
     * @type {string}
     * @memberof PactSummary
     */
    'created_at': string;
    /**
     * When the pact expires.
     * @type {string}
     * @memberof PactSummary
     */
    'expires_at': string;
    /**
     * Slugs of recipes associated with this pact.
     * @type {Array<string>}
     * @memberof PactSummary
     */
    'recipe_slugs'?: Array<string>;
    /**
     * Operator principal. Null if the principal row is missing (e.g. legacy data).
     * @type {PrincipalRead}
     * @memberof PactSummary
     */
    'operator'?: PrincipalRead;
    /**
     * Remaining quota for this active pact. Null for non-active pacts or when no measurable completion conditions are set.
     * @type {PactRemaining}
     * @memberof PactSummary
     */
    'remaining'?: PactRemaining;
}

