/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Language option for localized pact display fields.
 * @export
 * @enum {string}
 */
export const PactStatsLanguage = {
    zh: 'zh' as const,
    en: 'en' as const,
} as const;

export type PactStatsLanguage = typeof PactStatsLanguage[keyof typeof PactStatsLanguage];

