/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Response for a pact template.
 * @export
 * @interface PactTemplateRead
 */
export interface PactTemplateRead {
    /**
     * 
     * @type {string}
     * @memberof PactTemplateRead
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PactTemplateRead
     */
    'recipe_slug': string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PactTemplateRead
     */
    'template': { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof PactTemplateRead
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof PactTemplateRead
     */
    'updated_at': string;
}

