/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PactSummary } from './pact-summary';




/**
 * PactListResponse
 * @export
 * @interface PactListResponse
 */
export interface PactListResponse {
    /**
     * 
     * @type {Array<PactSummary>}
     * @memberof PactListResponse
     */
    'pacts': Array<PactSummary>;
}

