/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Types of events recorded for a Pact.
 * @export
 * @enum {string}
 */
export const PactEventType = {
    submitted: 'submitted' as const,
    activated: 'activated' as const,
    rejected: 'rejected' as const,
    completed: 'completed' as const,
    expired: 'expired' as const,
    revoked: 'revoked' as const,
    withdrawn: 'withdrawn' as const,
    completion_conditions_updated: 'completion_conditions_updated' as const,
    pact_policies_updated: 'pact_policies_updated' as const,
} as const;

export type PactEventType = typeof PactEventType[keyof typeof PactEventType];

