/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PactSpecOutput } from './pact-spec-output';

// @ts-ignore
import type { PactStatus } from './pact-status';

// @ts-ignore
import type { PrincipalRead } from './principal-read';




/**
 * Public pact detail response without delegation internals.
 * @export
 * @interface PactPublicRead
 */
export interface PactPublicRead {
    /**
     * Pact ID.
     * @type {string}
     * @memberof PactPublicRead
     */
    'id': string;
    /**
     * Wallet owner principal ID.
     * @type {string}
     * @memberof PactPublicRead
     */
    'owner_id': string;
    /**
     * Operator agent principal ID.
     * @type {string}
     * @memberof PactPublicRead
     */
    'operator_id': string;
    /**
     * Operator principal. Null if the principal row is missing (e.g. legacy data).
     * @type {PrincipalRead}
     * @memberof PactPublicRead
     */
    'operator'?: PrincipalRead;
    /**
     * Target wallet ID.
     * @type {string}
     * @memberof PactPublicRead
     */
    'wallet_id': string;
    /**
     * Pact name.
     * @type {string}
     * @memberof PactPublicRead
     */
    'name': string;
    /**
     * Natural language intent.
     * @type {string}
     * @memberof PactPublicRead
     */
    'intent': string;
    /**
     * Raw user input that originated this pact request. For multi-turn conversations, messages are concatenated.
     * @type {string}
     * @memberof PactPublicRead
     */
    'original_intent'?: string;
    /**
     * The pact specification.
     * @type {PactSpecOutput}
     * @memberof PactPublicRead
     */
    'spec': PactSpecOutput;
    /**
     * Current pact status.
     * @type {PactStatus}
     * @memberof PactPublicRead
     */
    'status': PactStatus;
    /**
     * Linked approval ID.
     * @type {string}
     * @memberof PactPublicRead
     */
    'approval_id'?: string;
    /**
     * Pact-scoped API key. Only visible to the operator.
     * @type {string}
     * @memberof PactPublicRead
     */
    'api_key'?: string;
    /**
     * When the pact became active.
     * @type {string}
     * @memberof PactPublicRead
     */
    'activated_at'?: string;
    /**
     * When the pact expires.
     * @type {string}
     * @memberof PactPublicRead
     */
    'expires_at'?: string;
    /**
     * Number of transactions completed under this pact.
     * @type {number}
     * @memberof PactPublicRead
     */
    'progress_tx_count'?: number;
    /**
     * Cumulative USD value of transactions executed under this pact, represented as a decimal string (e.g. \"12.50\").
     * @type {string}
     * @memberof PactPublicRead
     */
    'progress_usd_spent'?: string;
    /**
     * Whether this is the default pact created during provisioning.
     * @type {boolean}
     * @memberof PactPublicRead
     */
    'is_default'?: boolean;
    /**
     * Current effective delegation-scoped policies. Populated when policies have been updated after pact creation; null means spec.policies is still the effective set.
     * @type {Array<{ [key: string]: any; }>}
     * @memberof PactPublicRead
     */
    'effective_policies'?: Array<{ [key: string]: any; }>;
    /**
     * When the pact was submitted.
     * @type {string}
     * @memberof PactPublicRead
     */
    'created_at': string;
    /**
     * Last update timestamp.
     * @type {string}
     * @memberof PactPublicRead
     */
    'updated_at': string;
}

