/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PactSpecInput } from './pact-spec-input';




/**
 * Reviewer\'s response when resolving a pact approval.
 * @export
 * @interface PactApprovalResponseInput
 */
export interface PactApprovalResponseInput {
    /**
     * Optional revised pact spec. Replaces the pact\'s spec before activation.
     * @type {PactSpecInput}
     * @memberof PactApprovalResponseInput
     */
    'revised_pact'?: PactSpecInput;
    /**
     * Approval or rejection reason.
     * @type {string}
     * @memberof PactApprovalResponseInput
     */
    'reason'?: string;
}

