/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { InlinePolicyCreate } from './inline-policy-create';




/**
 * Request body for PATCH /pacts/{pact_id}/policies.  Full replacement of the pact\'s delegation-scoped policies. Old policies are deleted and new ones are created atomically.
 * @export
 * @interface PactUpdatePoliciesRequest
 */
export interface PactUpdatePoliciesRequest {
    /**
     * New policy list. Replaces all existing delegation policies.
     * @type {Array<InlinePolicyCreate>}
     * @memberof PactUpdatePoliciesRequest
     */
    'policies': Array<InlinePolicyCreate>;
}

