/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { CompletionCondition } from './completion-condition';

// @ts-ignore
import type { InlinePolicyCreate } from './inline-policy-create';




/**
 * The core pact specification — defines policies and completion conditions.
 * @export
 * @interface PactSpecOutput
 */
export interface PactSpecOutput {
    /**
     * Policy rules constraining the operator\'s actions.
     * @type {Array<InlinePolicyCreate>}
     * @memberof PactSpecOutput
     */
    'policies'?: Array<InlinePolicyCreate>;
    /**
     * Conditions that trigger automatic pact completion (any-of semantics).
     * @type {Array<CompletionCondition>}
     * @memberof PactSpecOutput
     */
    'completion_conditions'?: Array<CompletionCondition>;
    /**
     * Free-form execution plan derived from the intent, in markdown format. Presented to the owner during approval review so they can understand exactly what the operator will do. Suggested sections: # Summary, # Contract Operations, # Risk Controls, # Schedule.
     * @type {string}
     * @memberof PactSpecOutput
     */
    'execution_plan'?: string;
}

