/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Remaining quota for an active pact. Fields are null when the corresponding condition is not set.
 * @export
 * @interface PactRemaining
 */
export interface PactRemaining {
    /**
     * Transactions remaining before pact completes. Null if no TX_COUNT condition is set.
     * @type {number}
     * @memberof PactRemaining
     */
    'tx_count_remaining'?: number;
    /**
     * Remaining USD budget as a decimal string. Null if no AMOUNT_SPENT_USD condition is set.
     * @type {string}
     * @memberof PactRemaining
     */
    'usd_remaining'?: string;
    /**
     * Seconds until pact expires. Null if pact has no expiry.
     * @type {number}
     * @memberof PactRemaining
     */
    'time_remaining_seconds'?: number;
}

