/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Status of a pairing token lookup.
 * @export
 * @enum {string}
 */
export const PairTokenStatus = {
    valid: 'valid' as const,
    expired: 'expired' as const,
    paired: 'paired' as const,
    completed: 'completed' as const,
    not_found: 'not_found' as const,
} as const;

export type PairTokenStatus = typeof PairTokenStatus[keyof typeof PairTokenStatus];

