/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Aggregate payment terms.
 * @export
 * @interface PaymentTerms
 */
export interface PaymentTerms {
    /**
     * 
     * @type {string}
     * @memberof PaymentTerms
     */
    'total_amount': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentTerms
     */
    'token': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentTerms
     */
    'chain': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentTerms
     */
    'funding_model'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentTerms
     */
    'total_funded'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentTerms
     */
    'bonus_criteria'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentTerms
     */
    'bonus_amount'?: string;
}

