/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { MppSessionParams } from './mpp-session-params';

// @ts-ignore
import type { PaymentProtocol } from './payment-protocol';




/**
 * Unified payment request.  Protocol-specific fields are prefixed with protocol name (x402_ / mpp_).
 * @export
 * @interface PaymentCreate
 */
export interface PaymentCreate {
    /**
     * Payment protocol: \'x402\' or \'mpp\'
     * @type {PaymentProtocol}
     * @memberof PaymentCreate
     */
    'protocol': PaymentProtocol;
    /**
     * Idempotency key
     * @type {string}
     * @memberof PaymentCreate
     */
    'request_id'?: string;
    /**
     * Base64-encoded JSON from Payment-Required header
     * @type {string}
     * @memberof PaymentCreate
     */
    'x402_payment_required'?: string;
    /**
     * WWW-Authenticate header raw value
     * @type {string}
     * @memberof PaymentCreate
     */
    'mpp_www_authenticate'?: string;
    /**
     * Session parameters for MPP session actions (open/voucher/close)
     * @type {MppSessionParams}
     * @memberof PaymentCreate
     */
    'mpp_session'?: MppSessionParams;
}

