/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Supported payment protocols.
 * @export
 * @enum {string}
 */
export const PaymentProtocol = {
    x402: 'x402' as const,
    mpp: 'mpp' as const,
} as const;

export type PaymentProtocol = typeof PaymentProtocol[keyof typeof PaymentProtocol];

