/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PendingOperationStatus } from './pending-operation-status';

// @ts-ignore
import type { PendingOperationType } from './pending-operation-type';




/**
 * Pending operation response payload.
 * @export
 * @interface PendingOperationRead
 */
export interface PendingOperationRead {
    /**
     * The pending operation ID.
     * @type {string}
     * @memberof PendingOperationRead
     */
    'id': string;
    /**
     * The ID of the wallet owner who must approve this operation.
     * @type {string}
     * @memberof PendingOperationRead
     */
    'owner_id': string;
    /**
     * 
     * @type {string}
     * @memberof PendingOperationRead
     */
    'request_id': string | null;
    /**
     * The wallet ID associated with this pending operation.
     * @type {string}
     * @memberof PendingOperationRead
     */
    'wallet_id': string;
    /**
     * The ID of the principal that initiated this operation.
     * @type {string}
     * @memberof PendingOperationRead
     */
    'initiated_by': string;
    /**
     * 
     * @type {string}
     * @memberof PendingOperationRead
     */
    'delegation_id': string | null;
    /**
     * The type of operation awaiting approval. Possible values: `transfer`, `contract_call`.
     * @type {PendingOperationType}
     * @memberof PendingOperationRead
     */
    'operation_type': PendingOperationType;
    /**
     * The original operation parameters (transfer amount, destination address, contract call data, etc.).
     * @type {{ [key: string]: any; }}
     * @memberof PendingOperationRead
     */
    'operation_data': { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PendingOperationRead
     */
    'policy_decision': { [key: string]: any; } | null;
    /**
     * The pending operation status. Possible values: `pending`, `approved`, `rejected`, `expired`, `cancelled`.
     * @type {PendingOperationStatus}
     * @memberof PendingOperationRead
     */
    'status': PendingOperationStatus;
    /**
     * 
     * @type {string}
     * @memberof PendingOperationRead
     */
    'operation_token': string | null;
    /**
     * 
     * @type {string}
     * @memberof PendingOperationRead
     */
    'approved_by': string | null;
    /**
     * 
     * @type {string}
     * @memberof PendingOperationRead
     */
    'approved_at': string | null;
    /**
     * 
     * @type {string}
     * @memberof PendingOperationRead
     */
    'rejected_by': string | null;
    /**
     * 
     * @type {string}
     * @memberof PendingOperationRead
     */
    'rejected_at': string | null;
    /**
     * The timestamp when this pending operation expires, in ISO 8601 format.
     * @type {string}
     * @memberof PendingOperationRead
     */
    'expires_at': string;
    /**
     * The execution result after the operation was approved and submitted.
     * @type {{ [key: string]: any; }}
     * @memberof PendingOperationRead
     */
    'execution_result': { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof PendingOperationRead
     */
    'last_error': string | null;
    /**
     * The timestamp when this pending operation was created, in ISO 8601 format.
     * @type {string}
     * @memberof PendingOperationRead
     */
    'created_at': string;
    /**
     * The timestamp when this pending operation was last updated, in ISO 8601 format.
     * @type {string}
     * @memberof PendingOperationRead
     */
    'updated_at': string;
}

