/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PendingOperationRead } from './pending-operation-read';




/**
 * Paginated list response for pending operations.
 * @export
 * @interface PendingOperationListResponse
 */
export interface PendingOperationListResponse {
    /**
     * The list of pending operations.
     * @type {Array<PendingOperationRead>}
     * @memberof PendingOperationListResponse
     */
    'items': Array<PendingOperationRead>;
    /**
     * The total number of pending operations matching the filter when using offset-based pagination. When using cursor-based pagination (`after`/`before`), this field is `0` (the true total is not computed); see response `meta` for `has_more` and cursors.
     * @type {number}
     * @memberof PendingOperationListResponse
     */
    'total'?: number;
}

