/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PendingOperationType } from './pending-operation-type';




/**
 * PolicyDryRunRequest
 * @export
 * @interface PolicyDryRunRequest
 */
export interface PolicyDryRunRequest {
    /**
     * 
     * @type {string}
     * @memberof PolicyDryRunRequest
     */
    'wallet_id': string;
    /**
     * 
     * @type {string}
     * @memberof PolicyDryRunRequest
     */
    'delegation_id'?: string;
    /**
     * 
     * @type {PendingOperationType}
     * @memberof PolicyDryRunRequest
     */
    'operation_type': PendingOperationType;
    /**
     * 
     * @type {string}
     * @memberof PolicyDryRunRequest
     */
    'amount': string;
    /**
     * 
     * @type {string}
     * @memberof PolicyDryRunRequest
     */
    'chain_id': string;
    /**
     * 
     * @type {string}
     * @memberof PolicyDryRunRequest
     */
    'token_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PolicyDryRunRequest
     */
    'dst_addr'?: string;
    /**
     * EVM-only contract address.
     * @type {string}
     * @memberof PolicyDryRunRequest
     */
    'contract_addr'?: string;
    /**
     * EVM-only calldata payload.
     * @type {string}
     * @memberof PolicyDryRunRequest
     */
    'calldata'?: string;
    /**
     * Solana-only instruction payloads.
     * @type {Array<object>}
     * @memberof PolicyDryRunRequest
     */
    'instructions'?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof PolicyDryRunRequest
     */
    'principal_id'?: string;
}

