/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Supported policy categories.  Subset of ``caw_types.transaction.UserTransactionOperationType`` — values are shared so UT operation_type strings can be compared directly against PolicyType. Deposit is excluded because deposits are not policy-gated.
 * @export
 * @enum {string}
 */
export const PolicyType = {
    transfer: 'transfer' as const,
    contract_call: 'contract_call' as const,
    message_sign: 'message_sign' as const,
} as const;

export type PolicyType = typeof PolicyType[keyof typeof PolicyType];

