/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PolicyScope } from './policy-scope';

// @ts-ignore
import type { PolicyType } from './policy-type';




/**
 * PolicyCreate
 * @export
 * @interface PolicyCreate
 */
export interface PolicyCreate {
    /**
     * 
     * @type {PolicyScope}
     * @memberof PolicyCreate
     */
    'scope': PolicyScope;
    /**
     * 
     * @type {string}
     * @memberof PolicyCreate
     */
    'wallet_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PolicyCreate
     */
    'delegation_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PolicyCreate
     */
    'name': string;
    /**
     * 
     * @type {PolicyType}
     * @memberof PolicyCreate
     */
    'policy_type': PolicyType;
    /**
     * 
     * @type {object}
     * @memberof PolicyCreate
     */
    'rules': object;
    /**
     * 
     * @type {number}
     * @memberof PolicyCreate
     */
    'priority'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PolicyCreate
     */
    'is_active'?: boolean;
}

