/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PolicyScope } from './policy-scope';

// @ts-ignore
import type { PolicyType } from './policy-type';




/**
 * Policy response payload.
 * @export
 * @interface PolicyRead
 */
export interface PolicyRead {
    /**
     * The policy ID.
     * @type {string}
     * @memberof PolicyRead
     */
    'id': string;
    /**
     * The ID of the principal that owns this policy.
     * @type {string}
     * @memberof PolicyRead
     */
    'owner_id': string;
    /**
     * The policy scope. Possible values: `global`, `wallet`, `delegation`.
     * @type {PolicyScope}
     * @memberof PolicyRead
     */
    'scope': PolicyScope;
    /**
     * 
     * @type {string}
     * @memberof PolicyRead
     */
    'wallet_id': string | null;
    /**
     * 
     * @type {string}
     * @memberof PolicyRead
     */
    'delegation_id': string | null;
    /**
     * The policy name.
     * @type {string}
     * @memberof PolicyRead
     */
    'name': string;
    /**
     * The ID of the principal that created this policy.
     * @type {string}
     * @memberof PolicyRead
     */
    'created_by': string;
    /**
     * The policy type. Possible values: `transfer`, `contract_call`, `message_sign`.
     * @type {PolicyType}
     * @memberof PolicyRead
     */
    'policy_type': PolicyType;
    /**
     * The policy rule configuration.
     * @type {{ [key: string]: any; }}
     * @memberof PolicyRead
     */
    'rules': { [key: string]: any; };
    /**
     * The policy priority. Higher values take precedence.
     * @type {number}
     * @memberof PolicyRead
     */
    'priority': number;
    /**
     * Whether this policy is currently active. `true`: active. `false`: disabled.
     * @type {boolean}
     * @memberof PolicyRead
     */
    'is_active': boolean;
    /**
     * The timestamp when this policy was created, in ISO 8601 format.
     * @type {string}
     * @memberof PolicyRead
     */
    'created_at': string;
    /**
     * The timestamp when this policy was last updated, in ISO 8601 format.
     * @type {string}
     * @memberof PolicyRead
     */
    'updated_at': string;
}

