/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Principal types.
 * @export
 * @enum {string}
 */
export const PrincipalType = {
    human: 'human' as const,
    agent: 'agent' as const,
} as const;

export type PrincipalType = typeof PrincipalType[keyof typeof PrincipalType];

