/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PrincipalType } from './principal-type';




/**
 * Principal response payload.
 * @export
 * @interface PrincipalRead
 */
export interface PrincipalRead {
    /**
     * The principal ID.
     * @type {string}
     * @memberof PrincipalRead
     */
    'id': string;
    /**
     * The external identifier for this principal.
     * @type {string}
     * @memberof PrincipalRead
     */
    'external_id': string;
    /**
     * The principal type. Possible values: `human`, `agent`.
     * @type {PrincipalType}
     * @memberof PrincipalRead
     */
    'type': PrincipalType;
    /**
     * The display name of this principal.
     * @type {string}
     * @memberof PrincipalRead
     */
    'name': string;
    /**
     * Arbitrary key-value metadata associated with the principal.
     * @type {{ [key: string]: any; }}
     * @memberof PrincipalRead
     */
    'metadata'?: { [key: string]: any; };
    /**
     * Deprecated legacy field. Temporary-agent mode has been retired and this value is always `false` for newly provisioned agents.
     * @type {boolean}
     * @memberof PrincipalRead
     */
    'is_temporary'?: boolean;
    /**
     * The ID of the human principal that owns this agent. Only set for agent principals.
     * @type {string}
     * @memberof PrincipalRead
     */
    'owner_principal_id'?: string;
    /**
     * The onboarding session ID associated with this principal, if set.
     * @type {string}
     * @memberof PrincipalRead
     */
    'onboarding_session_id'?: string;
    /**
     * The timestamp when the principal was created, in ISO 8601 format.
     * @type {string}
     * @memberof PrincipalRead
     */
    'created_at': string;
    /**
     * The timestamp when the principal was last updated, in ISO 8601 format.
     * @type {string}
     * @memberof PrincipalRead
     */
    'updated_at': string;
}

