/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Request payload for updating a principal.
 * @export
 * @interface PrincipalUpdate
 */
export interface PrincipalUpdate {
    /**
     * The new display name for this principal. Max 255 characters.
     * @type {string}
     * @memberof PrincipalUpdate
     */
    'name': string;
}

