/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PrincipalType } from './principal-type';




/**
 * Request payload for creating a principal.
 * @export
 * @interface PrincipalCreate
 */
export interface PrincipalCreate {
    /**
     * Your system\'s identifier for this principal (for example, a user ID). Must be unique. Max 255 characters.
     * @type {string}
     * @memberof PrincipalCreate
     */
    'external_id': string;
    /**
     * The principal type. Possible values: `human`, `agent`.
     * @type {PrincipalType}
     * @memberof PrincipalCreate
     */
    'type': PrincipalType;
    /**
     * The display name for this principal. Max 255 characters.
     * @type {string}
     * @memberof PrincipalCreate
     */
    'name': string;
    /**
     * Arbitrary key-value metadata to associate with the principal.
     * @type {{ [key: string]: any; }}
     * @memberof PrincipalCreate
     */
    'metadata'?: { [key: string]: any; };
}

