/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Compact transaction record for recent-activity enrichment.
 * @export
 * @interface RecentTxSummary
 */
export interface RecentTxSummary {
    /**
     * Transaction UUID.
     * @type {string}
     * @memberof RecentTxSummary
     */
    'id': string;
    /**
     * Client-supplied request_id, if any.
     * @type {string}
     * @memberof RecentTxSummary
     */
    'request_id'?: string;
    /**
     * Transaction status label (e.g. success, processing, failed).
     * @type {string}
     * @memberof RecentTxSummary
     */
    'status': string;
    /**
     * Operation type (e.g. transfer, contract_call).
     * @type {string}
     * @memberof RecentTxSummary
     */
    'operation_type': string;
    /**
     * When the transaction was submitted.
     * @type {string}
     * @memberof RecentTxSummary
     */
    'created_at': string;
}

