/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Recent recipient address from transfer history.
 * @export
 * @interface RecentAddressRead
 */
export interface RecentAddressRead {
    /**
     * The recipient on-chain address.
     * @type {string}
     * @memberof RecentAddressRead
     */
    'address': string;
    /**
     * The chain ID associated with this address.
     * @type {string}
     * @memberof RecentAddressRead
     */
    'chain_id'?: string;
    /**
     * The token ID associated with the most recent transfer to this address.
     * @type {string}
     * @memberof RecentAddressRead
     */
    'token_id'?: string;
}

