/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * RecipeSearchSource
 * @export
 * @enum {string}
 */
export const RecipeSearchSource = {
    knowledge: 'knowledge' as const,
} as const;

export type RecipeSearchSource = typeof RecipeSearchSource[keyof typeof RecipeSearchSource];

