/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * RecipeReviewAction
 * @export
 * @enum {string}
 */
export const RecipeReviewAction = {
    approve: 'approve' as const,
    reject: 'reject' as const,
} as const;

export type RecipeReviewAction = typeof RecipeReviewAction[keyof typeof RecipeReviewAction];

