/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * RecipeCategoryRead
 * @export
 * @interface RecipeCategoryRead
 */
export interface RecipeCategoryRead {
    /**
     * 
     * @type {string}
     * @memberof RecipeCategoryRead
     */
    'category': string;
    /**
     * 
     * @type {number}
     * @memberof RecipeCategoryRead
     */
    'count': number;
}

