/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { RecipeSearchSource } from './recipe-search-source';




/**
 * Unified search response envelope.
 * @export
 * @interface RecipeSearchResponse
 */
export interface RecipeSearchResponse {
    /**
     * 
     * @type {RecipeSearchSource}
     * @memberof RecipeSearchResponse
     */
    'source': RecipeSearchSource;
    /**
     * Source-specific search payload
     * @type {{ [key: string]: any; }}
     * @memberof RecipeSearchResponse
     */
    'data': { [key: string]: any; };
}

