/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * RecipeCreate
 * @export
 * @interface RecipeCreate
 */
export interface RecipeCreate {
    /**
     * 
     * @type {string}
     * @memberof RecipeCreate
     */
    'slug': string;
    /**
     * 
     * @type {string}
     * @memberof RecipeCreate
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof RecipeCreate
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof RecipeCreate
     */
    'content_markdown'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecipeCreate
     */
    'chains'?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof RecipeCreate
     */
    'tokens'?: { [key: string]: { [key: string]: string; }; };
    /**
     * 
     * @type {Array<string>}
     * @memberof RecipeCreate
     */
    'tags'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecipeCreate
     */
    'category'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecipeCreate
     */
    'example_prompts'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RecipeCreate
     */
    'icon'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeCreate
     */
    'author_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeCreate
     */
    'sdk_example_path'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeCreate
     */
    'locale'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeCreate
     */
    'featured'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeCreate
     */
    'verified'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeCreate
     */
    'auto_publish'?: boolean;
}

