/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { RecipeStatus } from './recipe-status';




/**
 * RecipeUpdate
 * @export
 * @interface RecipeUpdate
 */
export interface RecipeUpdate {
    /**
     * 
     * @type {string}
     * @memberof RecipeUpdate
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeUpdate
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeUpdate
     */
    'content_markdown'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecipeUpdate
     */
    'chains'?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof RecipeUpdate
     */
    'tokens'?: { [key: string]: { [key: string]: string; }; };
    /**
     * 
     * @type {Array<string>}
     * @memberof RecipeUpdate
     */
    'tags'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecipeUpdate
     */
    'category'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecipeUpdate
     */
    'example_prompts'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RecipeUpdate
     */
    'icon'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeUpdate
     */
    'author_name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeUpdate
     */
    'featured'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeUpdate
     */
    'verified'?: boolean;
    /**
     * 
     * @type {RecipeStatus}
     * @memberof RecipeUpdate
     */
    'status'?: RecipeStatus;
    /**
     * 
     * @type {string}
     * @memberof RecipeUpdate
     */
    'sdk_example_path'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeUpdate
     */
    'locale'?: string;
}

