/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { RecipeSearchSource } from './recipe-search-source';




/**
 * Unified document response.
 * @export
 * @interface RecipeDocument
 */
export interface RecipeDocument {
    /**
     * 
     * @type {string}
     * @memberof RecipeDocument
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof RecipeDocument
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof RecipeDocument
     */
    'content': string;
    /**
     * 
     * @type {RecipeSearchSource}
     * @memberof RecipeDocument
     */
    'source': RecipeSearchSource;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof RecipeDocument
     */
    'metadata'?: { [key: string]: any; };
}

