/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * RecipeLibrarySortBy
 * @export
 * @enum {string}
 */
export const RecipeLibrarySortBy = {
    popular: 'popular' as const,
    newest: 'newest' as const,
    most_used: 'most_used' as const,
} as const;

export type RecipeLibrarySortBy = typeof RecipeLibrarySortBy[keyof typeof RecipeLibrarySortBy];

