/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Reject payload for pending operation.
 * @export
 * @interface RejectPendingOperationRequest
 */
export interface RejectPendingOperationRequest {
    /**
     * An optional reason for rejecting this operation. Max 500 characters.
     * @type {string}
     * @memberof RejectPendingOperationRequest
     */
    'reason'?: string;
}

