/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { ExternalTransactionRead } from './external-transaction-read';

// @ts-ignore
import type { PactRead } from './pact-read';

// @ts-ignore
import type { PactSpecOutput } from './pact-spec-output';

// @ts-ignore
import type { PrincipalRead } from './principal-read';

// @ts-ignore
import type { TransactionRecordExtra } from './transaction-record-extra';

// @ts-ignore
import type { TransactionRecordRead } from './transaction-record-read';

// @ts-ignore
import type { TransactionRecordType } from './transaction-record-type';



// @ts-ignore
import type { PactRead } from './PactRead';
// @ts-ignore
import type { TransactionRecordRead } from './TransactionRecordRead';

/**
 * @type Request
 * Request
 * @export
 */
export type Request = PactRead | TransactionRecordRead;

