/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { KeyExportStatus } from './key-export-status';




/**
 * Response after resolving an export.
 * @export
 * @interface ResolveExportResponse
 */
export interface ResolveExportResponse {
    /**
     * Updated state of the key export request after the approve or reject action has been applied.
     * @type {KeyExportStatus}
     * @memberof ResolveExportResponse
     */
    'status': KeyExportStatus;
}

