/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { ApprovalAction } from './approval-action';

// @ts-ignore
import type { Response1 } from './response1';




/**
 * ResolveApprovalRequest
 * @export
 * @interface ResolveApprovalRequest
 */
export interface ResolveApprovalRequest {
    /**
     * 
     * @type {ApprovalAction}
     * @memberof ResolveApprovalRequest
     */
    'action': ApprovalAction;
    /**
     * 
     * @type {Response1}
     * @memberof ResolveApprovalRequest
     */
    'response'?: Response1;
}

