/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Request body for approving or rejecting an export.
 * @export
 * @interface ResolveExportRequest
 */
export interface ResolveExportRequest {
    /**
     * Decision to apply to the export request. Use \'approve\' to authorize the export or \'reject\' to deny it.
     * @type {string}
     * @memberof ResolveExportRequest
     */
    'action': ResolveExportRequestActionEnum;
    /**
     * Human-readable explanation for the rejection. Required when action is \'reject\'; ignored when action is \'approve\'.
     * @type {string}
     * @memberof ResolveExportRequest
     */
    'rejection_reason'?: string;
}

export const ResolveExportRequestActionEnum = {
    approve: 'approve' as const,
    reject: 'reject' as const,
} as const;

export type ResolveExportRequestActionEnum = typeof ResolveExportRequestActionEnum[keyof typeof ResolveExportRequestActionEnum];

