/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PactApprovalResponseInput } from './pact-approval-response-input';

// @ts-ignore
import type { PactSpecInput } from './pact-spec-input';

// @ts-ignore
import type { TransactionApprovalResponse } from './transaction-approval-response';



// @ts-ignore
import type { PactApprovalResponseInput } from './PactApprovalResponseInput';
// @ts-ignore
import type { TransactionApprovalResponse } from './TransactionApprovalResponse';

/**
 * @type Response1
 * Reviewer\'s typed response data.
 * @export
 */
export type Response1 = PactApprovalResponseInput | TransactionApprovalResponse;

