/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Lightweight script info returned after reload.
 * @export
 * @interface ScriptBrief
 */
export interface ScriptBrief {
    /**
     * 
     * @type {string}
     * @memberof ScriptBrief
     */
    'brief': string;
    /**
     * 
     * @type {string}
     * @memberof ScriptBrief
     */
    'func_name': string;
    /**
     * 
     * @type {string}
     * @memberof ScriptBrief
     */
    'params': string;
    /**
     * 
     * @type {string}
     * @memberof ScriptBrief
     */
    'description': string;
}

