/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { KnowledgeSearchType } from './knowledge-search-type';

// @ts-ignore
import type { RecipeSearchSource } from './recipe-search-source';




/**
 * Request payload for recipe search across graph-based or knowledge-base sources.
 * @export
 * @interface SearchRecipesRequest
 */
export interface SearchRecipesRequest {
    /**
     * 
     * @type {string}
     * @memberof SearchRecipesRequest
     */
    'query': string;
    /**
     * Search source: \'graph\' for graph-based search, \'knowledge\' for knowledge base
     * @type {RecipeSearchSource}
     * @memberof SearchRecipesRequest
     */
    'source'?: RecipeSearchSource;
    /**
     * Search mode: local, global, or mix
     * @type {string}
     * @memberof SearchRecipesRequest
     */
    'mode'?: string;
    /**
     * Entities (local/mix) or relationships (global/mix) count
     * @type {number}
     * @memberof SearchRecipesRequest
     */
    'top_k'?: number;
    /**
     * Text chunks from vector search
     * @type {number}
     * @memberof SearchRecipesRequest
     */
    'chunk_top_k'?: number;
    /**
     * Token budget for entity context
     * @type {number}
     * @memberof SearchRecipesRequest
     */
    'max_entity_tokens'?: number;
    /**
     * Token budget for relation context
     * @type {number}
     * @memberof SearchRecipesRequest
     */
    'max_relation_tokens'?: number;
    /**
     * Overall token ceiling; chunks get whatever remains after KG context
     * @type {number}
     * @memberof SearchRecipesRequest
     */
    'max_total_tokens'?: number;
    /**
     * Max results for knowledge search
     * @type {number}
     * @memberof SearchRecipesRequest
     */
    'limit'?: number;
    /**
     * Filter recipes by chain symbol (e.g. \'ethereum\', \'solana\', \'bitcoin\')
     * @type {string}
     * @memberof SearchRecipesRequest
     */
    'chain'?: string;
    /**
     * Filter recipes by token symbol (e.g. \'ETH\', \'USDT\', \'BTC\')
     * @type {string}
     * @memberof SearchRecipesRequest
     */
    'token'?: string;
    /**
     * List of keywords for filtering documents during keyword search
     * @type {Array<string>}
     * @memberof SearchRecipesRequest
     */
    'keywords'?: Array<string>;
    /**
     * Search type: \'vector\', \'keyword\', or \'hybrid\'
     * @type {KnowledgeSearchType}
     * @memberof SearchRecipesRequest
     */
    'search_type'?: KnowledgeSearchType;
}

