/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { KnowledgeSearchType } from './knowledge-search-type';

// @ts-ignore
import type { RecipeSearchSource } from './recipe-search-source';




/**
 * Request payload for recipe knowledge-base search.
 * @export
 * @interface SearchRecipesRequest
 */
export interface SearchRecipesRequest {
    /**
     * 
     * @type {string}
     * @memberof SearchRecipesRequest
     */
    'query': string;
    /**
     * Search source (only \'knowledge\' is supported)
     * @type {RecipeSearchSource}
     * @memberof SearchRecipesRequest
     */
    'source'?: RecipeSearchSource;
    /**
     * Max results for knowledge search
     * @type {number}
     * @memberof SearchRecipesRequest
     */
    'limit'?: number;
    /**
     * Filter recipes by chain symbol (e.g. \'ethereum\', \'solana\', \'bitcoin\')
     * @type {string}
     * @memberof SearchRecipesRequest
     */
    'chain'?: string;
    /**
     * Filter recipes by token symbol (e.g. \'ETH\', \'USDT\', \'BTC\')
     * @type {string}
     * @memberof SearchRecipesRequest
     */
    'token'?: string;
    /**
     * List of keywords for filtering documents during keyword search
     * @type {Array<string>}
     * @memberof SearchRecipesRequest
     */
    'keywords'?: Array<string>;
    /**
     * Search type: \'vector\', \'keyword\', or \'hybrid\'
     * @type {KnowledgeSearchType}
     * @memberof SearchRecipesRequest
     */
    'search_type'?: KnowledgeSearchType;
}

