/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Solana address lookup table account.
 * @export
 * @interface SolAddressLookupTableAccount
 */
export interface SolAddressLookupTableAccount {
    /**
     * The address lookup table\'s public key.
     * @type {string}
     * @memberof SolAddressLookupTableAccount
     */
    'alt_account_key': string;
    /**
     * The list of addresses in this lookup table.
     * @type {Array<string>}
     * @memberof SolAddressLookupTableAccount
     */
    'addresses': Array<string>;
}

