/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Solana instruction account.
 * @export
 * @interface SolInstructionAccount
 */
export interface SolInstructionAccount {
    /**
     * The account\'s public key.
     * @type {string}
     * @memberof SolInstructionAccount
     */
    'pubkey': string;
    /**
     * Whether this account must sign the transaction.
     * @type {boolean}
     * @memberof SolInstructionAccount
     */
    'is_signer': boolean;
    /**
     * Whether this account will be modified by the instruction.
     * @type {boolean}
     * @memberof SolInstructionAccount
     */
    'is_writable': boolean;
}

