/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { SolInstructionAccount } from './sol-instruction-account';




/**
 * Solana contract call instruction.
 * @export
 * @interface SolInstruction
 */
export interface SolInstruction {
    /**
     * The Solana program ID to invoke.
     * @type {string}
     * @memberof SolInstruction
     */
    'program_id': string;
    /**
     * The accounts involved in this instruction.
     * @type {Array<SolInstructionAccount>}
     * @memberof SolInstruction
     */
    'accounts': Array<SolInstructionAccount>;
    /**
     * The instruction data as a base64-encoded string.
     * @type {string}
     * @memberof SolInstruction
     */
    'data': string;
}

