/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Optional Solana fee parameters for transfers.
 * @export
 * @interface SOLFeeRequest
 */
export interface SOLFeeRequest {
    /**
     * The fee type. Must be `SOL`.
     * @type {string}
     * @memberof SOLFeeRequest
     */
    'fee_type'?: string;
    /**
     * The price per compute unit, in microlamports.
     * @type {string}
     * @memberof SOLFeeRequest
     */
    'compute_unit_price': string;
    /**
     * The maximum number of compute units for this transaction.
     * @type {string}
     * @memberof SOLFeeRequest
     */
    'compute_unit_limit': string;
    /**
     * The token ID for fee payment.
     * @type {string}
     * @memberof SOLFeeRequest
     */
    'token_id': string;
}

