/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { FeeRequest } from './fee-request';




/**
 * Request payload for speeding up a broadcasting transaction via RBF.
 * @export
 * @interface SpeedupTransactionRequest
 */
export interface SpeedupTransactionRequest {
    /**
     * A client-supplied identifier for the replacement (speed-up) transaction, used for idempotency.
     * @type {string}
     * @memberof SpeedupTransactionRequest
     */
    'request_id'?: string;
    /**
     * Custom fee parameters for the replacement (speed-up) transaction. Must specify a higher fee than the original transaction to satisfy RBF requirements.
     * @type {FeeRequest}
     * @memberof SpeedupTransactionRequest
     */
    'fee': FeeRequest;
    /**
     * The provider-side transaction ID of the transaction to speed up. Retrieve this from the original transfer or contract call response.
     * @type {string}
     * @memberof SpeedupTransactionRequest
     */
    'cobo_transaction_id'?: string;
}

