/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PactEventListResponse } from './pact-event-list-response';

// @ts-ignore
import type { PaginationMeta } from './pagination-meta';




/**
 * StandardResponsePactEventListResponse
 * @export
 * @interface StandardResponsePactEventListResponse
 */
export interface StandardResponsePactEventListResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponsePactEventListResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {PactEventListResponse}
     * @memberof StandardResponsePactEventListResponse
     */
    'result': PactEventListResponse;
    /**
     * 
     * @type {string}
     * @memberof StandardResponsePactEventListResponse
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponsePactEventListResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponsePactEventListResponse
     */
    'meta'?: PaginationMeta;
}

