/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { TokenCandidate } from './token-candidate';




/**
 * StandardResponseListTokenCandidate
 * @export
 * @interface StandardResponseListTokenCandidate
 */
export interface StandardResponseListTokenCandidate {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseListTokenCandidate
     */
    'success'?: boolean;
    /**
     * 
     * @type {Array<TokenCandidate>}
     * @memberof StandardResponseListTokenCandidate
     */
    'result': Array<TokenCandidate>;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListTokenCandidate
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListTokenCandidate
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseListTokenCandidate
     */
    'meta'?: PaginationMeta;
}

