/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { WaasPaginatedResponseChainMetadata } from './waas-paginated-response-chain-metadata';




/**
 * StandardResponseWaasPaginatedResponseChainMetadata
 * @export
 * @interface StandardResponseWaasPaginatedResponseChainMetadata
 */
export interface StandardResponseWaasPaginatedResponseChainMetadata {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseWaasPaginatedResponseChainMetadata
     */
    'success'?: boolean;
    /**
     * 
     * @type {WaasPaginatedResponseChainMetadata}
     * @memberof StandardResponseWaasPaginatedResponseChainMetadata
     */
    'result': WaasPaginatedResponseChainMetadata;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWaasPaginatedResponseChainMetadata
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWaasPaginatedResponseChainMetadata
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseWaasPaginatedResponseChainMetadata
     */
    'meta'?: PaginationMeta;
}

