/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { TransactionRecordRead } from './transaction-record-read';




/**
 * StandardResponseTransactionRecordRead
 * @export
 * @interface StandardResponseTransactionRecordRead
 */
export interface StandardResponseTransactionRecordRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseTransactionRecordRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {TransactionRecordRead}
     * @memberof StandardResponseTransactionRecordRead
     */
    'result': TransactionRecordRead;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseTransactionRecordRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseTransactionRecordRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseTransactionRecordRead
     */
    'meta'?: PaginationMeta;
}

