/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { ResolveExportResponse } from './resolve-export-response';




/**
 * StandardResponseResolveExportResponse
 * @export
 * @interface StandardResponseResolveExportResponse
 */
export interface StandardResponseResolveExportResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseResolveExportResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {ResolveExportResponse}
     * @memberof StandardResponseResolveExportResponse
     */
    'result': ResolveExportResponse;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseResolveExportResponse
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseResolveExportResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseResolveExportResponse
     */
    'meta'?: PaginationMeta;
}

