/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { WalletTssCallbackResponse } from './wallet-tss-callback-response';




/**
 * StandardResponseWalletTssCallbackResponse
 * @export
 * @interface StandardResponseWalletTssCallbackResponse
 */
export interface StandardResponseWalletTssCallbackResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseWalletTssCallbackResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {WalletTssCallbackResponse}
     * @memberof StandardResponseWalletTssCallbackResponse
     */
    'result': WalletTssCallbackResponse;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletTssCallbackResponse
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletTssCallbackResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseWalletTssCallbackResponse
     */
    'meta'?: PaginationMeta;
}

