/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { RecipeSearchResponse } from './recipe-search-response';




/**
 * StandardResponseRecipeSearchResponse
 * @export
 * @interface StandardResponseRecipeSearchResponse
 */
export interface StandardResponseRecipeSearchResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseRecipeSearchResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {RecipeSearchResponse}
     * @memberof StandardResponseRecipeSearchResponse
     */
    'result': RecipeSearchResponse;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseRecipeSearchResponse
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseRecipeSearchResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseRecipeSearchResponse
     */
    'meta'?: PaginationMeta;
}

