/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { HireListResponse } from './hire-list-response';

// @ts-ignore
import type { PaginationMeta } from './pagination-meta';




/**
 * StandardResponseHireListResponse
 * @export
 * @interface StandardResponseHireListResponse
 */
export interface StandardResponseHireListResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseHireListResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {HireListResponse}
     * @memberof StandardResponseHireListResponse
     */
    'result': HireListResponse;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseHireListResponse
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseHireListResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseHireListResponse
     */
    'meta'?: PaginationMeta;
}

