/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { CreateExportResponse } from './create-export-response';

// @ts-ignore
import type { PaginationMeta } from './pagination-meta';




/**
 * StandardResponseCreateExportResponse
 * @export
 * @interface StandardResponseCreateExportResponse
 */
export interface StandardResponseCreateExportResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseCreateExportResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {CreateExportResponse}
     * @memberof StandardResponseCreateExportResponse
     */
    'result': CreateExportResponse;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseCreateExportResponse
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseCreateExportResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseCreateExportResponse
     */
    'meta'?: PaginationMeta;
}

