/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { AuditLogPage } from './audit-log-page';

// @ts-ignore
import type { PaginationMeta } from './pagination-meta';




/**
 * StandardResponseAuditLogPage
 * @export
 * @interface StandardResponseAuditLogPage
 */
export interface StandardResponseAuditLogPage {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseAuditLogPage
     */
    'success'?: boolean;
    /**
     * 
     * @type {AuditLogPage}
     * @memberof StandardResponseAuditLogPage
     */
    'result': AuditLogPage;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseAuditLogPage
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseAuditLogPage
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseAuditLogPage
     */
    'meta'?: PaginationMeta;
}

