/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { ChainInfo } from './chain-info';

// @ts-ignore
import type { PaginationMeta } from './pagination-meta';




/**
 * StandardResponseChainInfo
 * @export
 * @interface StandardResponseChainInfo
 */
export interface StandardResponseChainInfo {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseChainInfo
     */
    'success'?: boolean;
    /**
     * 
     * @type {ChainInfo}
     * @memberof StandardResponseChainInfo
     */
    'result': ChainInfo;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseChainInfo
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseChainInfo
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseChainInfo
     */
    'meta'?: PaginationMeta;
}

