/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { WalletPairInitiateRead } from './wallet-pair-initiate-read';




/**
 * StandardResponseWalletPairInitiateRead
 * @export
 * @interface StandardResponseWalletPairInitiateRead
 */
export interface StandardResponseWalletPairInitiateRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseWalletPairInitiateRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {WalletPairInitiateRead}
     * @memberof StandardResponseWalletPairInitiateRead
     */
    'result': WalletPairInitiateRead;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletPairInitiateRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletPairInitiateRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseWalletPairInitiateRead
     */
    'meta'?: PaginationMeta;
}

