/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { WalletAddressRead } from './wallet-address-read';




/**
 * StandardResponseWalletAddressRead
 * @export
 * @interface StandardResponseWalletAddressRead
 */
export interface StandardResponseWalletAddressRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseWalletAddressRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {WalletAddressRead}
     * @memberof StandardResponseWalletAddressRead
     */
    'result': WalletAddressRead;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletAddressRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletAddressRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseWalletAddressRead
     */
    'meta'?: PaginationMeta;
}

