/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { WalletRead } from './wallet-read';




/**
 * StandardResponseListWalletRead
 * @export
 * @interface StandardResponseListWalletRead
 */
export interface StandardResponseListWalletRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseListWalletRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {Array<WalletRead>}
     * @memberof StandardResponseListWalletRead
     */
    'result': Array<WalletRead>;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListWalletRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListWalletRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseListWalletRead
     */
    'meta'?: PaginationMeta;
}

