/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { RecipeDetailRead } from './recipe-detail-read';




/**
 * StandardResponseRecipeDetailRead
 * @export
 * @interface StandardResponseRecipeDetailRead
 */
export interface StandardResponseRecipeDetailRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseRecipeDetailRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {RecipeDetailRead}
     * @memberof StandardResponseRecipeDetailRead
     */
    'result': RecipeDetailRead;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseRecipeDetailRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseRecipeDetailRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseRecipeDetailRead
     */
    'meta'?: PaginationMeta;
}

