/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { HireRead } from './hire-read';

// @ts-ignore
import type { PaginationMeta } from './pagination-meta';




/**
 * StandardResponseHireRead
 * @export
 * @interface StandardResponseHireRead
 */
export interface StandardResponseHireRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseHireRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {HireRead}
     * @memberof StandardResponseHireRead
     */
    'result': HireRead;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseHireRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseHireRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseHireRead
     */
    'meta'?: PaginationMeta;
}

