/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';




/**
 * StandardResponseDictStrBool
 * @export
 * @interface StandardResponseDictStrBool
 */
export interface StandardResponseDictStrBool {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseDictStrBool
     */
    'success'?: boolean;
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof StandardResponseDictStrBool
     */
    'result': { [key: string]: boolean; };
    /**
     * 
     * @type {string}
     * @memberof StandardResponseDictStrBool
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseDictStrBool
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseDictStrBool
     */
    'meta'?: PaginationMeta;
}

