/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { AgentStatusResponse } from './agent-status-response';

// @ts-ignore
import type { PaginationMeta } from './pagination-meta';




/**
 * StandardResponseAgentStatusResponse
 * @export
 * @interface StandardResponseAgentStatusResponse
 */
export interface StandardResponseAgentStatusResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseAgentStatusResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {AgentStatusResponse}
     * @memberof StandardResponseAgentStatusResponse
     */
    'result': AgentStatusResponse;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseAgentStatusResponse
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseAgentStatusResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseAgentStatusResponse
     */
    'meta'?: PaginationMeta;
}

