/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { WalletPairInfoRead } from './wallet-pair-info-read';




/**
 * StandardResponseWalletPairInfoRead
 * @export
 * @interface StandardResponseWalletPairInfoRead
 */
export interface StandardResponseWalletPairInfoRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseWalletPairInfoRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {WalletPairInfoRead}
     * @memberof StandardResponseWalletPairInfoRead
     */
    'result': WalletPairInfoRead;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletPairInfoRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletPairInfoRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseWalletPairInfoRead
     */
    'meta'?: PaginationMeta;
}

