/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { WalletAddressInfo } from './wallet-address-info';




/**
 * StandardResponseListWalletAddressInfo
 * @export
 * @interface StandardResponseListWalletAddressInfo
 */
export interface StandardResponseListWalletAddressInfo {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseListWalletAddressInfo
     */
    'success'?: boolean;
    /**
     * 
     * @type {Array<WalletAddressInfo>}
     * @memberof StandardResponseListWalletAddressInfo
     */
    'result': Array<WalletAddressInfo>;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListWalletAddressInfo
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListWalletAddressInfo
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseListWalletAddressInfo
     */
    'meta'?: PaginationMeta;
}

