/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { PrincipalRead } from './principal-read';




/**
 * StandardResponseListPrincipalRead
 * @export
 * @interface StandardResponseListPrincipalRead
 */
export interface StandardResponseListPrincipalRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseListPrincipalRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {Array<PrincipalRead>}
     * @memberof StandardResponseListPrincipalRead
     */
    'result': Array<PrincipalRead>;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListPrincipalRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListPrincipalRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseListPrincipalRead
     */
    'meta'?: PaginationMeta;
}

