/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { WalletDetailRead } from './wallet-detail-read';




/**
 * StandardResponseWalletDetailRead
 * @export
 * @interface StandardResponseWalletDetailRead
 */
export interface StandardResponseWalletDetailRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseWalletDetailRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {WalletDetailRead}
     * @memberof StandardResponseWalletDetailRead
     */
    'result': WalletDetailRead;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletDetailRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletDetailRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseWalletDetailRead
     */
    'meta'?: PaginationMeta;
}

