/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { WalletPairRead } from './wallet-pair-read';




/**
 * StandardResponseWalletPairRead
 * @export
 * @interface StandardResponseWalletPairRead
 */
export interface StandardResponseWalletPairRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseWalletPairRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {WalletPairRead}
     * @memberof StandardResponseWalletPairRead
     */
    'result': WalletPairRead;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletPairRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletPairRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseWalletPairRead
     */
    'meta'?: PaginationMeta;
}

