/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { DelegationRead } from './delegation-read';

// @ts-ignore
import type { PaginationMeta } from './pagination-meta';




/**
 * StandardResponseDelegationRead
 * @export
 * @interface StandardResponseDelegationRead
 */
export interface StandardResponseDelegationRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseDelegationRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {DelegationRead}
     * @memberof StandardResponseDelegationRead
     */
    'result': DelegationRead;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseDelegationRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseDelegationRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseDelegationRead
     */
    'meta'?: PaginationMeta;
}

