/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { WalletRead } from './wallet-read';




/**
 * StandardResponseWalletRead
 * @export
 * @interface StandardResponseWalletRead
 */
export interface StandardResponseWalletRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseWalletRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {WalletRead}
     * @memberof StandardResponseWalletRead
     */
    'result': WalletRead;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseWalletRead
     */
    'meta'?: PaginationMeta;
}

