/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { PolicyRead } from './policy-read';




/**
 * StandardResponseListPolicyRead
 * @export
 * @interface StandardResponseListPolicyRead
 */
export interface StandardResponseListPolicyRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseListPolicyRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {Array<PolicyRead>}
     * @memberof StandardResponseListPolicyRead
     */
    'result': Array<PolicyRead>;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListPolicyRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListPolicyRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseListPolicyRead
     */
    'meta'?: PaginationMeta;
}

