/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { FaucetTokenItem } from './faucet-token-item';

// @ts-ignore
import type { PaginationMeta } from './pagination-meta';




/**
 * StandardResponseListFaucetTokenItem
 * @export
 * @interface StandardResponseListFaucetTokenItem
 */
export interface StandardResponseListFaucetTokenItem {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseListFaucetTokenItem
     */
    'success'?: boolean;
    /**
     * 
     * @type {Array<FaucetTokenItem>}
     * @memberof StandardResponseListFaucetTokenItem
     */
    'result': Array<FaucetTokenItem>;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListFaucetTokenItem
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListFaucetTokenItem
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseListFaucetTokenItem
     */
    'meta'?: PaginationMeta;
}

