/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { WalletPactHistoryRead } from './wallet-pact-history-read';




/**
 * StandardResponseWalletPactHistoryRead
 * @export
 * @interface StandardResponseWalletPactHistoryRead
 */
export interface StandardResponseWalletPactHistoryRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseWalletPactHistoryRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {WalletPactHistoryRead}
     * @memberof StandardResponseWalletPactHistoryRead
     */
    'result': WalletPactHistoryRead;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletPactHistoryRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletPactHistoryRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseWalletPactHistoryRead
     */
    'meta'?: PaginationMeta;
}

