/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PactTemplateRead } from './pact-template-read';

// @ts-ignore
import type { PaginationMeta } from './pagination-meta';




/**
 * StandardResponseListPactTemplateRead
 * @export
 * @interface StandardResponseListPactTemplateRead
 */
export interface StandardResponseListPactTemplateRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseListPactTemplateRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {Array<PactTemplateRead>}
     * @memberof StandardResponseListPactTemplateRead
     */
    'result': Array<PactTemplateRead>;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListPactTemplateRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListPactTemplateRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseListPactTemplateRead
     */
    'meta'?: PaginationMeta;
}

