/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { MerchantInfo } from './merchant-info';

// @ts-ignore
import type { PaginationMeta } from './pagination-meta';




/**
 * StandardResponseListMerchantInfo
 * @export
 * @interface StandardResponseListMerchantInfo
 */
export interface StandardResponseListMerchantInfo {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseListMerchantInfo
     */
    'success'?: boolean;
    /**
     * 
     * @type {Array<MerchantInfo>}
     * @memberof StandardResponseListMerchantInfo
     */
    'result': Array<MerchantInfo>;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListMerchantInfo
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListMerchantInfo
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseListMerchantInfo
     */
    'meta'?: PaginationMeta;
}

