/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { SuggestionResponse } from './suggestion-response';




/**
 * StandardResponseSuggestionResponse
 * @export
 * @interface StandardResponseSuggestionResponse
 */
export interface StandardResponseSuggestionResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseSuggestionResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {SuggestionResponse}
     * @memberof StandardResponseSuggestionResponse
     */
    'result': SuggestionResponse;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseSuggestionResponse
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseSuggestionResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseSuggestionResponse
     */
    'meta'?: PaginationMeta;
}

