/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PactPublicRead } from './pact-public-read';

// @ts-ignore
import type { PaginationMeta } from './pagination-meta';




/**
 * StandardResponsePactPublicRead
 * @export
 * @interface StandardResponsePactPublicRead
 */
export interface StandardResponsePactPublicRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponsePactPublicRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {PactPublicRead}
     * @memberof StandardResponsePactPublicRead
     */
    'result': PactPublicRead;
    /**
     * 
     * @type {string}
     * @memberof StandardResponsePactPublicRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponsePactPublicRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponsePactPublicRead
     */
    'meta'?: PaginationMeta;
}

