/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { UserTransactionRead } from './user-transaction-read';




/**
 * StandardResponseUserTransactionRead
 * @export
 * @interface StandardResponseUserTransactionRead
 */
export interface StandardResponseUserTransactionRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseUserTransactionRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {UserTransactionRead}
     * @memberof StandardResponseUserTransactionRead
     */
    'result': UserTransactionRead;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseUserTransactionRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseUserTransactionRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseUserTransactionRead
     */
    'meta'?: PaginationMeta;
}

