/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { RecentAddressRead } from './recent-address-read';




/**
 * StandardResponseListRecentAddressRead
 * @export
 * @interface StandardResponseListRecentAddressRead
 */
export interface StandardResponseListRecentAddressRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseListRecentAddressRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {Array<RecentAddressRead>}
     * @memberof StandardResponseListRecentAddressRead
     */
    'result': Array<RecentAddressRead>;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListRecentAddressRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseListRecentAddressRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseListRecentAddressRead
     */
    'meta'?: PaginationMeta;
}

