/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { SystemConfigRead } from './system-config-read';




/**
 * StandardResponseSystemConfigRead
 * @export
 * @interface StandardResponseSystemConfigRead
 */
export interface StandardResponseSystemConfigRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseSystemConfigRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {SystemConfigRead}
     * @memberof StandardResponseSystemConfigRead
     */
    'result': SystemConfigRead;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseSystemConfigRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseSystemConfigRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseSystemConfigRead
     */
    'meta'?: PaginationMeta;
}

