/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { WalletReshareResponse } from './wallet-reshare-response';




/**
 * StandardResponseWalletReshareResponse
 * @export
 * @interface StandardResponseWalletReshareResponse
 */
export interface StandardResponseWalletReshareResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseWalletReshareResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {WalletReshareResponse}
     * @memberof StandardResponseWalletReshareResponse
     */
    'result': WalletReshareResponse;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletReshareResponse
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWalletReshareResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseWalletReshareResponse
     */
    'meta'?: PaginationMeta;
}

