/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { NodeStatusRead } from './node-status-read';

// @ts-ignore
import type { PaginationMeta } from './pagination-meta';




/**
 * StandardResponseNodeStatusRead
 * @export
 * @interface StandardResponseNodeStatusRead
 */
export interface StandardResponseNodeStatusRead {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseNodeStatusRead
     */
    'success'?: boolean;
    /**
     * 
     * @type {NodeStatusRead}
     * @memberof StandardResponseNodeStatusRead
     */
    'result': NodeStatusRead;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseNodeStatusRead
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseNodeStatusRead
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseNodeStatusRead
     */
    'meta'?: PaginationMeta;
}

