/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { ResolveApprovalResponse } from './resolve-approval-response';




/**
 * StandardResponseResolveApprovalResponse
 * @export
 * @interface StandardResponseResolveApprovalResponse
 */
export interface StandardResponseResolveApprovalResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseResolveApprovalResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {ResolveApprovalResponse}
     * @memberof StandardResponseResolveApprovalResponse
     */
    'result': ResolveApprovalResponse;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseResolveApprovalResponse
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseResolveApprovalResponse
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseResolveApprovalResponse
     */
    'meta'?: PaginationMeta;
}

