/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

// @ts-ignore
import type { WaasPaginatedResponseTokenMetadata } from './waas-paginated-response-token-metadata';




/**
 * StandardResponseWaasPaginatedResponseTokenMetadata
 * @export
 * @interface StandardResponseWaasPaginatedResponseTokenMetadata
 */
export interface StandardResponseWaasPaginatedResponseTokenMetadata {
    /**
     * 
     * @type {boolean}
     * @memberof StandardResponseWaasPaginatedResponseTokenMetadata
     */
    'success'?: boolean;
    /**
     * 
     * @type {WaasPaginatedResponseTokenMetadata}
     * @memberof StandardResponseWaasPaginatedResponseTokenMetadata
     */
    'result': WaasPaginatedResponseTokenMetadata;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWaasPaginatedResponseTokenMetadata
     */
    'suggestion'?: string;
    /**
     * 
     * @type {string}
     * @memberof StandardResponseWaasPaginatedResponseTokenMetadata
     */
    'message'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof StandardResponseWaasPaginatedResponseTokenMetadata
     */
    'meta'?: PaginationMeta;
}

