/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Request body for submitting TSS node IDs to trigger reshare.
 * @export
 * @interface SubmitReshareNodesRequest
 */
export interface SubmitReshareNodesRequest {
    /**
     * List of temporary TSS node IDs to participate in the reshare operation. At least two node IDs are required.
     * @type {Array<string>}
     * @memberof SubmitReshareNodesRequest
     */
    'node_ids': Array<string>;
}

