/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * SuggestionKey
 * @export
 * @enum {string}
 */
export const SuggestionKey = {
    ONBOARD_COMPLETE: 'ONBOARD_COMPLETE' as const,
    PAIR_SUBMIT_SUCCESS: 'PAIR_SUBMIT_SUCCESS' as const,
    PACT_SUBMIT_SUCCESS_UNPAIRED: 'PACT_SUBMIT_SUCCESS_UNPAIRED' as const,
    PACT_SUBMIT_SUCCESS_PAIRED: 'PACT_SUBMIT_SUCCESS_PAIRED' as const,
    WALLET_NOT_FOUND: 'WALLET_NOT_FOUND' as const,
    WALLET_NOT_READY: 'WALLET_NOT_READY' as const,
    WALLET_MISSING_COBO_ID: 'WALLET_MISSING_COBO_ID' as const,
    WALLET_UNSUPPORTED_CHAIN: 'WALLET_UNSUPPORTED_CHAIN' as const,
    WALLET_PAIR_WALLET_NOT_FOUND: 'WALLET_PAIR_WALLET_NOT_FOUND' as const,
    WALLET_PAIR_TOKEN_EXPIRED: 'WALLET_PAIR_TOKEN_EXPIRED' as const,
    WALLET_PAIR_AGENT_NOT_FOUND: 'WALLET_PAIR_AGENT_NOT_FOUND' as const,
    WALLET_PAIR_CONFLICT: 'WALLET_PAIR_CONFLICT' as const,
    WALLET_PAIR_CODE_EXHAUSTED: 'WALLET_PAIR_CODE_EXHAUSTED' as const,
    WALLET_PAIR_ALREADY_PAIRED: 'WALLET_PAIR_ALREADY_PAIRED' as const,
    INSUFFICIENT_PERMISSION: 'INSUFFICIENT_PERMISSION' as const,
    APPROVAL_REQUIRED: 'APPROVAL_REQUIRED' as const,
    APPROVAL_REQUIRED_UNPAIRED: 'APPROVAL_REQUIRED_UNPAIRED' as const,
    PACT_NOT_FOUND: 'PACT_NOT_FOUND' as const,
    PACT_WALLET_NOT_FOUND: 'PACT_WALLET_NOT_FOUND' as const,
    PACT_WRONG_STATUS: 'PACT_WRONG_STATUS' as const,
    METADATA_CHAIN_NOT_FOUND: 'METADATA_CHAIN_NOT_FOUND' as const,
} as const;

export type SuggestionKey = typeof SuggestionKey[keyof typeof SuggestionKey];

