/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Read representation of a system config entry.
 * @export
 * @interface SystemConfigRead
 */
export interface SystemConfigRead {
    /**
     * 
     * @type {string}
     * @memberof SystemConfigRead
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof SystemConfigRead
     */
    'key': string;
    /**
     * 
     * @type {string}
     * @memberof SystemConfigRead
     */
    'value': string;
    /**
     * 
     * @type {string}
     * @memberof SystemConfigRead
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof SystemConfigRead
     */
    'updated_at': string;
}

