/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Token and asset metadata returned by the Cobo WaaS API. Describes a supported token, including its chain, decimals, deposit/withdrawal eligibility, and fee token.
 * @export
 * @interface TokenMetadata
 */
export interface TokenMetadata {
    /**
     * 
     * @type {string}
     * @memberof TokenMetadata
     */
    'token_id': string;
    /**
     * 
     * @type {string}
     * @memberof TokenMetadata
     */
    'chain_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenMetadata
     */
    'asset_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenMetadata
     */
    'symbol'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenMetadata
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof TokenMetadata
     */
    'decimal'?: number;
    /**
     * 
     * @type {string}
     * @memberof TokenMetadata
     */
    'icon_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenMetadata
     */
    'token_address'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenMetadata
     */
    'fee_token_id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TokenMetadata
     */
    'can_deposit'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TokenMetadata
     */
    'can_withdraw'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TokenMetadata
     */
    'dust_threshold'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenMetadata
     */
    'custodial_minimum_deposit_threshold'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenMetadata
     */
    'asset_model_type'?: string;
}

