/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { FeeRequest } from './fee-request';




/**
 * Request payload for token transfer.
 * @export
 * @interface TransferCreate
 */
export interface TransferCreate {
    /**
     * The destination on-chain address.
     * @type {string}
     * @memberof TransferCreate
     */
    'dst_addr': string;
    /**
     * The transfer amount as a decimal string (for example, `1.5`).
     * @type {string}
     * @memberof TransferCreate
     */
    'amount': string;
    /**
     * The Cobo token ID to transfer (for example, `SETH`, `SETH_USDC`, `SOLDEV_SOL_USDC`). Use the List supported assets operation to retrieve all supported token IDs. Defaults to `SETH`.
     * @type {string}
     * @memberof TransferCreate
     */
    'token_id'?: string;
    /**
     * The chain ID. Automatically resolved from `token_id` if omitted.
     * @type {string}
     * @memberof TransferCreate
     */
    'chain_id'?: string;
    /**
     * A client-supplied identifier for idempotency. If a transfer with the same `request_id` already exists for the same principal, the existing record is returned.
     * @type {string}
     * @memberof TransferCreate
     */
    'request_id'?: string;
    /**
     * 
     * @type {FeeRequest}
     * @memberof TransferCreate
     */
    'fee'?: FeeRequest | null;
    /**
     * The source address to transfer from. If omitted, the server auto-selects the wallet address on this chain with the highest available `token_id` balance (explicit `src_addr` always takes precedence).
     * @type {string}
     * @memberof TransferCreate
     */
    'src_addr'?: string;
    /**
     * Whether to use Cobo Gasless (Fee Station) to cover gas fees. `true`: gas fees are sponsored. `false`: gas fees are paid from the wallet. Defaults to `true` for human-owned wallets, `false` for agent-owned wallets.
     * @type {boolean}
     * @memberof TransferCreate
     */
    'sponsor'?: boolean;
    /**
     * The gas provider to use for sponsored transactions. If omitted, the server default is used.
     * @type {string}
     * @memberof TransferCreate
     */
    'gas_provider'?: string;
    /**
     * Optional note stored locally and sent to WaaS as the transaction `description` (transfer).
     * @type {string}
     * @memberof TransferCreate
     */
    'description'?: string;
}

