/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Reviewer\'s response when resolving a transaction approval.
 * @export
 * @interface TransactionApprovalResponse
 */
export interface TransactionApprovalResponse {
    /**
     * Approval or rejection reason.
     * @type {string}
     * @memberof TransactionApprovalResponse
     */
    'reason'?: string;
}

