/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * TransactionProvider
 * @export
 * @enum {string}
 */
export const TransactionProvider = {
    waas: 'waas' as const,
    alchemy: 'alchemy' as const,
    pimlico: 'pimlico' as const,
    node_rpc: 'node_rpc' as const,
} as const;

export type TransactionProvider = typeof TransactionProvider[keyof typeof TransactionProvider];

