/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Activity types stored in the unified record table.
 * @export
 * @enum {string}
 */
export const TransactionRecordType = {
    transfer: 'transfer' as const,
    contract_call: 'contract_call' as const,
    deposit: 'deposit' as const,
    message_sign: 'message_sign' as const,
} as const;

export type TransactionRecordType = typeof TransactionRecordType[keyof typeof TransactionRecordType];

