/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { UcwSharePublicDataCallback } from './ucw-share-public-data-callback';




/**
 * UCW SDK ``TSSKeyShareGroup`` in TSS callback payloads.
 * @export
 * @interface UcwTssKeyShareGroupCallback
 */
export interface UcwTssKeyShareGroupCallback {
    /**
     * 
     * @type {string}
     * @memberof UcwTssKeyShareGroupCallback
     */
    'id': string;
    /**
     * 
     * @type {number}
     * @memberof UcwTssKeyShareGroupCallback
     */
    'created_timestamp'?: number;
    /**
     * UCW GroupType enum value (ECDSA=1, EdDSA=2).
     * @type {number}
     * @memberof UcwTssKeyShareGroupCallback
     */
    'type': number;
    /**
     * 
     * @type {string}
     * @memberof UcwTssKeyShareGroupCallback
     */
    'root_extended_public_key'?: string;
    /**
     * 
     * @type {string}
     * @memberof UcwTssKeyShareGroupCallback
     */
    'chaincode'?: string;
    /**
     * 
     * @type {string}
     * @memberof UcwTssKeyShareGroupCallback
     */
    'curve'?: string;
    /**
     * 
     * @type {number}
     * @memberof UcwTssKeyShareGroupCallback
     */
    'threshold'?: number;
    /**
     * 
     * @type {Array<UcwSharePublicDataCallback>}
     * @memberof UcwTssKeyShareGroupCallback
     */
    'participants'?: Array<UcwSharePublicDataCallback>;
}

