/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * UCW SDK ``SharePublicData`` in TSS callback payloads.
 * @export
 * @interface UcwSharePublicDataCallback
 */
export interface UcwSharePublicDataCallback {
    /**
     * 
     * @type {string}
     * @memberof UcwSharePublicDataCallback
     */
    'node_id': string;
    /**
     * 
     * @type {string}
     * @memberof UcwSharePublicDataCallback
     */
    'share_id': string;
    /**
     * 
     * @type {string}
     * @memberof UcwSharePublicDataCallback
     */
    'share_public_key': string;
}

