/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { ExternalTransactionRead } from './external-transaction-read';

// @ts-ignore
import type { UserTransactionData } from './user-transaction-data';

// @ts-ignore
import type { UserTransactionOperationType } from './user-transaction-operation-type';

// @ts-ignore
import type { UserTransactionRequestType } from './user-transaction-request-type';




/**
 * Public representation of a user transaction.
 * @export
 * @interface UserTransactionRead
 */
export interface UserTransactionRead {
    /**
     * The transaction record ID.
     * @type {string}
     * @memberof UserTransactionRead
     */
    'id': string;
    /**
     * The wallet ID this transaction belongs to.
     * @type {string}
     * @memberof UserTransactionRead
     */
    'wallet_id': string;
    /**
     * When the originating request used a pact-scoped API key, the pact UUID (mirrors `data.pact_id` when set).
     * @type {string}
     * @memberof UserTransactionRead
     */
    'pact_id'?: string;
    /**
     * The operation type. Possible values: `transfer`, `contract_call`, `message_sign`, `deposit`.
     * @type {UserTransactionOperationType}
     * @memberof UserTransactionRead
     */
    'type': UserTransactionOperationType;
    /**
     * The originating request type. Possible values: `transfer`, `contract_call`, `deposit`, `message_sign`, `x402_payment`, `mpp_payment`. When multiple request_types share the same operation type (e.g. x402_payment → transfer), this field distinguishes the source.
     * @type {UserTransactionRequestType}
     * @memberof UserTransactionRead
     */
    'request_type'?: UserTransactionRequestType;
    /**
     * The Cobo chain ID for this transaction (for example, `SETH`, `BASE_ETH`, `SOL`).
     * @type {string}
     * @memberof UserTransactionRead
     */
    'chain_id': string;
    /**
     * The Cobo token ID for this transaction (for example, `SETH`, `SETH_USDC`).
     * @type {string}
     * @memberof UserTransactionRead
     */
    'token_id': string;
    /**
     * The source on-chain address.
     * @type {string}
     * @memberof UserTransactionRead
     */
    'src_address': string;
    /**
     * The destination on-chain address.
     * @type {string}
     * @memberof UserTransactionRead
     */
    'dst_address': string;
    /**
     * The transaction amount as a decimal string.
     * @type {string}
     * @memberof UserTransactionRead
     */
    'amount': string;
    /**
     * The transaction status code.
     * @type {number}
     * @memberof UserTransactionRead
     */
    'status': number;
    /**
     * The human-readable transaction status (for example, `success`, `failed`, `broadcasting`).
     * @type {string}
     * @memberof UserTransactionRead
     */
    'status_display'?: string;
    /**
     * The fine-grained transaction sub-status (for example, `broadcasting`, `pendingscreening`). Mirrors `UserTransaction.sub_status`.
     * @type {string}
     * @memberof UserTransactionRead
     */
    'sub_status'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTransactionRead
     */
    'transaction_hash': string | null;
    /**
     * The client-supplied request identifier, if set.
     * @type {string}
     * @memberof UserTransactionRead
     */
    'request_id'?: string;
    /**
     * Optional note from submission; duplicated from `data.description` when present.
     * @type {string}
     * @memberof UserTransactionRead
     */
    'description'?: string;
    /**
     * Additional transaction metadata.
     * @type {UserTransactionData}
     * @memberof UserTransactionRead
     */
    'data': UserTransactionData;
    /**
     * The timestamp when this record was created, in ISO 8601 format.
     * @type {string}
     * @memberof UserTransactionRead
     */
    'created_at': string;
    /**
     * The timestamp when this record was last updated, in ISO 8601 format.
     * @type {string}
     * @memberof UserTransactionRead
     */
    'updated_at': string;
    /**
     * Associated external (downstream) transactions. Only populated when the request includes `ext=true`.
     * @type {Array<ExternalTransactionRead>}
     * @memberof UserTransactionRead
     */
    'ext_transactions'?: Array<ExternalTransactionRead>;
}

