/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Structured extra data stored in the JSON ``data`` column.  All fields are optional so the same schema covers transfer, contract_call, deposit, and x402 payment records.
 * @export
 * @interface UserTransactionData
 */
export interface UserTransactionData {
    /**
     * 
     * @type {string}
     * @memberof UserTransactionData
     */
    'sub_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTransactionData
     */
    'contract_addr'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTransactionData
     */
    'value'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTransactionData
     */
    'calldata'?: string;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof UserTransactionData
     */
    'instructions'?: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UserTransactionData
     */
    'fee'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof UserTransactionData
     */
    'failed_reason'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTransactionData
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTransactionData
     */
    'signature'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTransactionData
     */
    'destination_type'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UserTransactionData
     */
    'eip712_typed_data'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof UserTransactionData
     */
    'payment_required_raw'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTransactionData
     */
    'payment_signature_raw'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTransactionData
     */
    'siwx_header_value'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTransactionData
     */
    'mpp_authorization_header'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTransactionData
     */
    'pact_id'?: string;
}

