/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * UserTransactionRequestType
 * @export
 * @enum {string}
 */
export const UserTransactionRequestType = {
    transfer: 'transfer' as const,
    contract_call: 'contract_call' as const,
    deposit: 'deposit' as const,
    message_sign: 'message_sign' as const,
    x402_payment: 'x402_payment' as const,
    mpp_payment: 'mpp_payment' as const,
} as const;

export type UserTransactionRequestType = typeof UserTransactionRequestType[keyof typeof UserTransactionRequestType];

