/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * MPC Vault Group 类型  均为 2/2 配置 (User 1 片 + Cobo 1 片)。  AGENT: Agent 持有密钥分片，用于服务端自动签名（CLI 发起） HUMAN: Human 持有密钥分片，用于 UCW 移动端签名（Mobile App 发起）  当 Agent 钱包被 Human 认领后，同一个 Wallet 会同时拥有 AGENT 和 HUMAN 两个 VaultGroup，分别对应不同的签名参与方。
 * @export
 * @enum {string}
 */
export const VaultGroupType = {
    agent: 'agent' as const,
    human: 'human' as const,
} as const;

export type VaultGroupType = typeof VaultGroupType[keyof typeof VaultGroupType];

