/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { AutomatedCheck } from './automated-check';




/**
 * Verification settings for the pact.
 * @export
 * @interface VerificationSpec
 */
export interface VerificationSpec {
    /**
     * 
     * @type {string}
     * @memberof VerificationSpec
     */
    'method': string;
    /**
     * 
     * @type {Array<AutomatedCheck>}
     * @memberof VerificationSpec
     */
    'automated_checks'?: Array<AutomatedCheck>;
    /**
     * 
     * @type {Array<string>}
     * @memberof VerificationSpec
     */
    'review_rubric'?: Array<string>;
}

