/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { TokenMetadata } from './token-metadata';

// @ts-ignore
import type { WaasPagination } from './waas-pagination';




/**
 * WaasPaginatedResponseTokenMetadata
 * @export
 * @interface WaasPaginatedResponseTokenMetadata
 */
export interface WaasPaginatedResponseTokenMetadata {
    /**
     * 
     * @type {Array<TokenMetadata>}
     * @memberof WaasPaginatedResponseTokenMetadata
     */
    'data'?: Array<TokenMetadata>;
    /**
     * 
     * @type {WaasPagination}
     * @memberof WaasPaginatedResponseTokenMetadata
     */
    'pagination'?: WaasPagination;
}

