/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Cursor-based pagination metadata returned by the Cobo WaaS API.
 * @export
 * @interface WaasPagination
 */
export interface WaasPagination {
    /**
     * 
     * @type {string}
     * @memberof WaasPagination
     */
    'before'?: string;
    /**
     * 
     * @type {string}
     * @memberof WaasPagination
     */
    'after'?: string;
    /**
     * 
     * @type {number}
     * @memberof WaasPagination
     */
    'total_count'?: number;
}

