/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * TSS row after syncing from WaaS.
 * @export
 * @interface WalletTssCallbackResponse
 */
export interface WalletTssCallbackResponse {
    /**
     * 
     * @type {string}
     * @memberof WalletTssCallbackResponse
     */
    'tss_request_id': string;
    /**
     * TssRequestStatus string aligned with WaaS.
     * @type {string}
     * @memberof WalletTssCallbackResponse
     */
    'status': string;
    /**
     * 
     * @type {string}
     * @memberof WalletTssCallbackResponse
     */
    'waas_status_snapshot'?: string;
}

