/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { DelegationSpendSummary } from './delegation-spend-summary';

// @ts-ignore
import type { WalletGroupRead } from './wallet-group-read';

// @ts-ignore
import type { WalletStatus } from './wallet-status';

// @ts-ignore
import type { WalletType } from './wallet-type';




/**
 * WalletDetailRead
 * @export
 * @interface WalletDetailRead
 */
export interface WalletDetailRead {
    /**
     * The wallet ID.
     * @type {string}
     * @memberof WalletDetailRead
     */
    'uuid': string;
    /**
     * The wallet type (for example, `MPC`).
     * @type {WalletType}
     * @memberof WalletDetailRead
     */
    'wallet_type': WalletType;
    /**
     * The wallet name.
     * @type {string}
     * @memberof WalletDetailRead
     */
    'name': string;
    /**
     * The ID of the principal that owns this wallet.
     * @type {string}
     * @memberof WalletDetailRead
     */
    'owner_id': string;
    /**
     * 
     * @type {string}
     * @memberof WalletDetailRead
     */
    'cobo_wallet_id': string | null;
    /**
     * The wallet status. Possible values: `preparing`, `active`, `archived`.
     * @type {WalletStatus}
     * @memberof WalletDetailRead
     */
    'status': WalletStatus;
    /**
     * Arbitrary key-value metadata associated with the wallet.
     * @type {{ [key: string]: any; }}
     * @memberof WalletDetailRead
     */
    'metadata': { [key: string]: any; };
    /**
     * The timestamp when the wallet was created, in ISO 8601 format.
     * @type {string}
     * @memberof WalletDetailRead
     */
    'created_at': string;
    /**
     * The timestamp when the wallet was last updated, in ISO 8601 format.
     * @type {string}
     * @memberof WalletDetailRead
     */
    'updated_at': string;
    /**
     * TSS node ID of the wallet owner\'s main device. Only set for MPC wallets.
     * @type {string}
     * @memberof WalletDetailRead
     */
    'main_node_id'?: string;
    /**
     * 
     * @type {Array<DelegationSpendSummary>}
     * @memberof WalletDetailRead
     */
    'spend_summary'?: Array<DelegationSpendSummary>;
    /**
     * Key share holder groups and nodes for MPC-UCW wallets (empty for non-MPC).
     * @type {Array<WalletGroupRead>}
     * @memberof WalletDetailRead
     */
    'groups'?: Array<WalletGroupRead>;
}

