/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Wallet address response payload.
 * @export
 * @interface WalletAddressRead
 */
export interface WalletAddressRead {
    /**
     * The wallet ID.
     * @type {string}
     * @memberof WalletAddressRead
     */
    'wallet_id': string;
    /**
     * The address standard shared across chains — chains with the same chain_type share one wallet address. E.g. ETH, BASE, ARB, OP, BSC, MATIC, AVAXC, and SETH are all chain_type: ETH, so they all use the same 0x... address.
     * @type {string}
     * @memberof WalletAddressRead
     */
    'chain_type'?: string;
    /**
     * Supported chain IDs that share the same address under this chain_type.
     * @type {Array<string>}
     * @memberof WalletAddressRead
     */
    'compatible_chains'?: Array<string>;
    /**
     * The on-chain address.
     * @type {string}
     * @memberof WalletAddressRead
     */
    'address': string;
    /**
     * The timestamp when the address was created, in ISO 8601 format.
     * @type {string}
     * @memberof WalletAddressRead
     */
    'created_at': string;
    /**
     * The timestamp when the address was last updated, in ISO 8601 format.
     * @type {string}
     * @memberof WalletAddressRead
     */
    'updated_at': string;
}

