/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Agent principal summary for pair info.
 * @export
 * @interface WalletPairAgentInfo
 */
export interface WalletPairAgentInfo {
    /**
     * 
     * @type {string}
     * @memberof WalletPairAgentInfo
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof WalletPairAgentInfo
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof WalletPairAgentInfo
     */
    'external_id': string;
}

