/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Per-pact contribution within one history bucket.
 * @export
 * @interface WalletPactHistoryBucketPactRead
 */
export interface WalletPactHistoryBucketPactRead {
    /**
     * Pact UUID. Null for synthetic rows.
     * @type {string}
     * @memberof WalletPactHistoryBucketPactRead
     */
    'pact_id'?: string;
    /**
     * Localized pact title for display.
     * @type {string}
     * @memberof WalletPactHistoryBucketPactRead
     */
    'title': string;
    /**
     * Pact tx count in this bucket.
     * @type {number}
     * @memberof WalletPactHistoryBucketPactRead
     */
    'tx_count': number;
    /**
     * Pact tx amount in this bucket, decimal string.
     * @type {string}
     * @memberof WalletPactHistoryBucketPactRead
     */
    'tx_amount': string;
}

