/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Request payload for an agent to generate a wallet pairing token.
 * @export
 * @interface WalletPairInitiate
 */
export interface WalletPairInitiate {
    /**
     * The ID of the wallet to pair.
     * @type {string}
     * @memberof WalletPairInitiate
     */
    'wallet_id': string;
}

