/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Request payload for updating wallet metadata.
 * @export
 * @interface WalletUpdate
 */
export interface WalletUpdate {
    /**
     * The new wallet name. Max 255 characters.
     * @type {string}
     * @memberof WalletUpdate
     */
    'name'?: string;
    /**
     * Arbitrary key-value metadata to update on the wallet. Replaces the existing metadata.
     * @type {{ [key: string]: any; }}
     * @memberof WalletUpdate
     */
    'metadata'?: { [key: string]: any; };
}

