/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Summary metrics for the selected history window.
 * @export
 * @interface WalletPactHistorySummaryRead
 */
export interface WalletPactHistorySummaryRead {
    /**
     * Total tx count across all buckets in the range.
     * @type {number}
     * @memberof WalletPactHistorySummaryRead
     */
    'total_tx_count': number;
    /**
     * Total tx amount across all buckets in the range, decimal string.
     * @type {string}
     * @memberof WalletPactHistorySummaryRead
     */
    'total_tx_amount': string;
}

