/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Currency code for pact statistics.
 * @export
 * @enum {string}
 */
export const WalletPactCurrency = {
    USD: 'USD' as const,
} as const;

export type WalletPactCurrency = typeof WalletPactCurrency[keyof typeof WalletPactCurrency];

