/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { KeyShareHolderType } from './key-share-holder-type';




/**
 * One TSS node in a key share holder group.
 * @export
 * @interface WalletGroupNodeRead
 */
export interface WalletGroupNodeRead {
    /**
     * TSS node id (WaaS).
     * @type {string}
     * @memberof WalletGroupNodeRead
     */
    'node_id': string;
    /**
     * WaaS KeyShareHolderType: Cobo, Mobile, API.
     * @type {KeyShareHolderType}
     * @memberof WalletGroupNodeRead
     */
    'node_type': KeyShareHolderType;
    /**
     * Display name or account id when available; null for Cobo-operated nodes.
     * @type {string}
     * @memberof WalletGroupNodeRead
     */
    'node_owner'?: string;
}

