/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Supported history windows for pact charting.
 * @export
 * @enum {string}
 */
export const WalletPactHistoryRange = {
    _1d: '1d' as const,
    _7d: '7d' as const,
    _30d: '30d' as const,
} as const;

export type WalletPactHistoryRange = typeof WalletPactHistoryRange[keyof typeof WalletPactHistoryRange];

