/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { WalletPactCurrency } from './wallet-pact-currency';




/**
 * Wallet-level pact statistics for the banner.
 * @export
 * @interface WalletPactStatsRead
 */
export interface WalletPactStatsRead {
    /**
     * Wallet UUID.
     * @type {string}
     * @memberof WalletPactStatsRead
     */
    'wallet_id': string;
    /**
     * Total number of pacts ever created for this wallet.
     * @type {number}
     * @memberof WalletPactStatsRead
     */
    'total_pacts': number;
    /**
     * Currently active pacts for this wallet.
     * @type {number}
     * @memberof WalletPactStatsRead
     */
    'total_active_pacts': number;
    /**
     * Total completed transaction count under pact scope.
     * @type {number}
     * @memberof WalletPactStatsRead
     */
    'total_tx_count': number;
    /**
     * Total completed transaction volume in USD, decimal string.
     * @type {string}
     * @memberof WalletPactStatsRead
     */
    'total_volume_usd': string;
    /**
     * Display currency code.
     * @type {WalletPactCurrency}
     * @memberof WalletPactStatsRead
     */
    'currency': WalletPactCurrency;
    /**
     * Start time of statistics accumulation.
     * @type {string}
     * @memberof WalletPactStatsRead
     */
    'since': string;
    /**
     * Timestamp when this payload was generated.
     * @type {string}
     * @memberof WalletPactStatsRead
     */
    'as_of': string;
}

