/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { KeyShareHolderGroupStatus } from './key-share-holder-group-status';

// @ts-ignore
import type { KeyShareHolderGroupType } from './key-share-holder-group-type';

// @ts-ignore
import type { VaultGroupType } from './vault-group-type';

// @ts-ignore
import type { WalletGroupNodeRead } from './wallet-group-node-read';




/**
 * Cached key share holder group for an MPC wallet.
 * @export
 * @interface WalletGroupRead
 */
export interface WalletGroupRead {
    /**
     * Cobo group id.
     * @type {string}
     * @memberof WalletGroupRead
     */
    'group_id': string;
    /**
     * WaaS KeyShareHolderGroupType: MainGroup, SigningGroup, RecoveryGroup.
     * @type {KeyShareHolderGroupType}
     * @memberof WalletGroupRead
     */
    'group_type': KeyShareHolderGroupType;
    /**
     * MPC user-side holder: `agent` (CLI/server) or `human` (mobile).
     * @type {VaultGroupType}
     * @memberof WalletGroupRead
     */
    'holder_role': VaultGroupType;
    /**
     * WaaS KeyShareHolderGroupStatus: New, Valid, Unavailable.
     * @type {KeyShareHolderGroupStatus}
     * @memberof WalletGroupRead
     */
    'group_status': KeyShareHolderGroupStatus;
    /**
     * 
     * @type {Array<WalletGroupNodeRead>}
     * @memberof WalletGroupRead
     */
    'nodes'?: Array<WalletGroupNodeRead>;
}

