/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { WalletPairAgentInfo } from './wallet-pair-agent-info';

// @ts-ignore
import type { WalletPairStatus } from './wallet-pair-status';

// @ts-ignore
import type { WalletPairTokenPurpose } from './wallet-pair-token-purpose';

// @ts-ignore
import type { WalletPairWalletInfo } from './wallet-pair-wallet-info';




/**
 * Wallet pairing response payload.
 * @export
 * @interface WalletPairRead
 */
export interface WalletPairRead {
    /**
     * The pairing record ID.
     * @type {string}
     * @memberof WalletPairRead
     */
    'id': string;
    /**
     * The wallet being paired.
     * @type {string}
     * @memberof WalletPairRead
     */
    'wallet_id': string;
    /**
     * 
     * @type {string}
     * @memberof WalletPairRead
     */
    'claimer_principal_id': string | null;
    /**
     * The ID of the agent principal that initiated pairing.
     * @type {string}
     * @memberof WalletPairRead
     */
    'agent_principal_id': string;
    /**
     * The 8-digit numeric code used to authorize pairing.
     * @type {string}
     * @memberof WalletPairRead
     */
    'token': string;
    /**
     * The pairing status. Possible values: `pending`, `paired`, `completed`.
     * @type {WalletPairStatus}
     * @memberof WalletPairRead
     */
    'status': WalletPairStatus;
    /**
     * `pair` = initial claim flow; `restore` = post-completion recovery code.
     * @type {WalletPairTokenPurpose}
     * @memberof WalletPairRead
     */
    'token_purpose': WalletPairTokenPurpose;
    /**
     * The timestamp when the pairing token expires, in ISO 8601 format.
     * @type {string}
     * @memberof WalletPairRead
     */
    'expires_at': string;
    /**
     * The timestamp when the pairing record was created, in ISO 8601 format.
     * @type {string}
     * @memberof WalletPairRead
     */
    'created_at': string;
    /**
     * The timestamp when the pairing record was last updated, in ISO 8601 format.
     * @type {string}
     * @memberof WalletPairRead
     */
    'updated_at': string;
    /**
     * The agent principal that initiated pairing. Included on initiate and confirm responses.
     * @type {WalletPairAgentInfo}
     * @memberof WalletPairRead
     */
    'agent'?: WalletPairAgentInfo;
    /**
     * The wallet being paired. Included on initiate and confirm responses.
     * @type {WalletPairWalletInfo}
     * @memberof WalletPairRead
     */
    'wallet'?: WalletPairWalletInfo;
}

