/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Owner\'s TSS node for creating a Signing group, then KeyGenFromKeyGroup TSS from main group.
 * @export
 * @interface WalletReshareRequest
 */
export interface WalletReshareRequest {
    /**
     * The human principal\'s TSS node id (bound to the wallet owner).
     * @type {string}
     * @memberof WalletReshareRequest
     */
    'node_id': string;
}

