/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { VaultGroupType } from './vault-group-type';

// @ts-ignore
import type { WalletType } from './wallet-type';




/**
 * Request payload for creating a wallet.  Ownership can be selected via `for_owner`: - for_owner=False: create for current principal (Agent)     - for_owner=True: create for current principal\'s owner (Human),         or fallback to current principal when no owner is linked
 * @export
 * @interface WalletCreate
 */
export interface WalletCreate {
    /**
     * The wallet type. Use `MPC`.
     * @type {WalletType}
     * @memberof WalletCreate
     */
    'wallet_type': WalletType;
    /**
     * The wallet name. Max 255 characters.
     * @type {string}
     * @memberof WalletCreate
     */
    'name': string;
    /**
     * The MPC key share scheme. `AGENT` (2-of-2): agent TSS node + Cobo, suitable for automated wallets. `HUMAN` (2-of-2): mobile TSS node + Cobo, suitable for human-controlled wallets. Defaults to `AGENT`.
     * @type {VaultGroupType}
     * @memberof WalletCreate
     */
    'group_type'?: VaultGroupType;
    /**
     * The TSS node ID of the agent\'s main device. Required when `wallet_type=MPC`.
     * @type {string}
     * @memberof WalletCreate
     */
    'main_node_id'?: string;
    /**
     * Arbitrary key-value metadata to associate with the wallet.
     * @type {{ [key: string]: any; }}
     * @memberof WalletCreate
     */
    'metadata'?: { [key: string]: any; };
    /**
     * Whether to create the wallet for the principal\'s linked owner (`true`) or for the principal itself (`false`). Defaults to `false`.
     * @type {boolean}
     * @memberof WalletCreate
     */
    'for_owner'?: boolean;
}

