/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Request payload for a human to confirm wallet pairing using a token.
 * @export
 * @interface WalletPairConfirm
 */
export interface WalletPairConfirm {
    /**
     * Optional wallet ID to bind the confirmation token to. When provided, the token must belong to this wallet.
     * @type {string}
     * @memberof WalletPairConfirm
     */
    'wallet_id'?: string;
    /**
     * 8-digit numeric pairing code from the agent.
     * @type {string}
     * @memberof WalletPairConfirm
     */
    'token': string;
}

