/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * A single wallet address with derivation info.
 * @export
 * @interface WalletAddressInfo
 */
export interface WalletAddressInfo {
    /**
     * Identifier of the blockchain network this address belongs to (e.g. \'ETH\', \'BTC\').
     * @type {string}
     * @memberof WalletAddressInfo
     */
    'chain_id': string;
    /**
     * Blockchain address string in the format native to the specified chain (e.g. \'0x…\' for EVM chains, \'bc1…\' for Bitcoin bech32).
     * @type {string}
     * @memberof WalletAddressInfo
     */
    'address': string;
    /**
     * BIP-32 derivation path used to derive this address from the root key (e.g. \'m/44\'/60\'/0\'/0/0\'). Empty string if not applicable.
     * @type {string}
     * @memberof WalletAddressInfo
     */
    'path'?: string;
    /**
     * Compressed public key corresponding to this address, hex-encoded. Empty string if not yet populated.
     * @type {string}
     * @memberof WalletAddressInfo
     */
    'pubkey'?: string;
    /**
     * Address encoding format applied to the public key (e.g. \'bech32\', \'base58\'). Empty string if not applicable.
     * @type {string}
     * @memberof WalletAddressInfo
     */
    'encoding'?: string;
    /**
     * Hex-encoded root public key from which this address is derived. Empty string if not yet populated.
     * @type {string}
     * @memberof WalletAddressInfo
     */
    'root_pubkey'?: string;
}

