/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Which flow this claim row represents (pair claim vs post-completion restore).
 * @export
 * @enum {string}
 */
export const WalletPairTokenPurpose = {
    pair: 'pair' as const,
    restore: 'restore' as const,
} as const;

export type WalletPairTokenPurpose = typeof WalletPairTokenPurpose[keyof typeof WalletPairTokenPurpose];

