/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */






/**
 * Wallet pairing lifecycle statuses.
 * @export
 * @enum {string}
 */
export const WalletPairStatus = {
    pending: 'pending' as const,
    paired: 'paired' as const,
    completed: 'completed' as const,
} as const;

export type WalletPairStatus = typeof WalletPairStatus[keyof typeof WalletPairStatus];

