/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { WalletPactCurrency } from './wallet-pact-currency';

// @ts-ignore
import type { WalletPactHistoryBucketRead } from './wallet-pact-history-bucket-read';

// @ts-ignore
import type { WalletPactHistoryRange } from './wallet-pact-history-range';

// @ts-ignore
import type { WalletPactHistorySummaryRead } from './wallet-pact-history-summary-read';




/**
 * Wallet pact history payload for chart rendering.
 * @export
 * @interface WalletPactHistoryRead
 */
export interface WalletPactHistoryRead {
    /**
     * Wallet UUID.
     * @type {string}
     * @memberof WalletPactHistoryRead
     */
    'wallet_id': string;
    /**
     * Echoed query range.
     * @type {WalletPactHistoryRange}
     * @memberof WalletPactHistoryRead
     */
    'range': WalletPactHistoryRange;
    /**
     * Display currency code.
     * @type {WalletPactCurrency}
     * @memberof WalletPactHistoryRead
     */
    'currency': WalletPactCurrency;
    /**
     * Range summary metrics.
     * @type {WalletPactHistorySummaryRead}
     * @memberof WalletPactHistoryRead
     */
    'summary': WalletPactHistorySummaryRead;
    /**
     * Time-ordered buckets covering the full requested range.
     * @type {Array<WalletPactHistoryBucketRead>}
     * @memberof WalletPactHistoryRead
     */
    'buckets': Array<WalletPactHistoryBucketRead>;
    /**
     * Timestamp when this payload was generated.
     * @type {string}
     * @memberof WalletPactHistoryRead
     */
    'as_of': string;
}

