/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





// @ts-ignore
import type { PairTokenStatus } from './pair-token-status';

// @ts-ignore
import type { WalletPairAgentInfo } from './wallet-pair-agent-info';

// @ts-ignore
import type { WalletPairTokenPurpose } from './wallet-pair-token-purpose';

// @ts-ignore
import type { WalletPairWalletInfo } from './wallet-pair-wallet-info';




/**
 * Pair info response. Agent and wallet are only present when token is valid.
 * @export
 * @interface WalletPairInfoRead
 */
export interface WalletPairInfoRead {
    /**
     * The status of the pairing token. Possible values: `valid` (code not yet used), `expired`, `paired` (human confirmed; first reshare still required), `completed` (first pair or restore reshare has consumed this code), `not_found`.
     * @type {PairTokenStatus}
     * @memberof WalletPairInfoRead
     */
    'token_status': PairTokenStatus;
    /**
     * Which flow this token belongs to. `pair` = initial agent→human ownership claim; `restore` = post-completion recovery code that re-shares to a new human key share. `null` only when `token_status=not_found`.
     * @type {WalletPairTokenPurpose}
     * @memberof WalletPairInfoRead
     */
    'token_purpose'?: WalletPairTokenPurpose;
    /**
     * Pending pairing token when `token_status=valid` (e.g. from authenticated pair-info by wallet).
     * @type {string}
     * @memberof WalletPairInfoRead
     */
    'token'?: string;
    /**
     * The agent principal that initiated pairing. Only present when `token_status=valid`.
     * @type {WalletPairAgentInfo}
     * @memberof WalletPairInfoRead
     */
    'agent'?: WalletPairAgentInfo;
    /**
     * The wallet being paired. Only present when `token_status=valid`.
     * @type {WalletPairWalletInfo}
     * @memberof WalletPairInfoRead
     */
    'wallet'?: WalletPairWalletInfo;
}

