/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Owner\'s TSS node for creating a Signing group, then KeyGenFromKeyGroup TSS from main group.
 * @export
 * @interface WalletReshareRequest
 */
export interface WalletReshareRequest {
    /**
     * The human principal\'s TSS node id (bound to the wallet owner).
     * @type {string}
     * @memberof WalletReshareRequest
     */
    'node_id': string;
    /**
     * Optional 8-digit code. The backend resolves the token\'s purpose (`pair` vs `restore`) from the matching claim row: `pair` requires a **post-confirm (paired) claim** row; `restore` requires a **confirmed (paired) restore** code and must be used before it expires. Omit in older app versions.
     * @type {string}
     * @memberof WalletReshareRequest
     */
    'token'?: string;
}

