/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Webhook registration response.
 * @export
 * @interface WebhookRegistrationRead
 */
export interface WebhookRegistrationRead {
    /**
     * Unique identifier of the webhook registration.
     * @type {string}
     * @memberof WebhookRegistrationRead
     */
    'id': string;
    /**
     * The HTTPS URL that receives webhook POST requests.
     * @type {string}
     * @memberof WebhookRegistrationRead
     */
    'callback_url': string;
    /**
     * UUID of the owner associated with this registration, if any.
     * @type {string}
     * @memberof WebhookRegistrationRead
     */
    'owner_id'?: string;
    /**
     * List of subscribed event type strings.
     * @type {Array<string>}
     * @memberof WebhookRegistrationRead
     */
    'event_types'?: Array<string>;
    /**
     * Whether this webhook registration is currently active and will receive events.
     * @type {boolean}
     * @memberof WebhookRegistrationRead
     */
    'is_active': boolean;
    /**
     * Timestamp when the webhook registration was created.
     * @type {string}
     * @memberof WebhookRegistrationRead
     */
    'created_at': string;
}

