/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * Structured work definition for the pact.
 * @export
 * @interface WorkScope
 */
export interface WorkScope {
    /**
     * 
     * @type {string}
     * @memberof WorkScope
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof WorkScope
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof WorkScope
     */
    'category'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkScope
     */
    'in_scope': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkScope
     */
    'out_of_scope'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkScope
     */
    'acceptance_criteria': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkScope
     */
    'technology_stack'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkScope
     */
    'references'?: Array<string>;
}

