/**
 * Cobo Agentic Wallet Service
 *
 * The version of the OpenAPI document: 1.2.4
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */








/**
 * WrappedValidationError
 * @export
 * @interface WrappedValidationError
 */
export interface WrappedValidationError {
    /**
     * 
     * @type {boolean}
     * @memberof WrappedValidationError
     */
    'success': boolean;
    /**
     * 
     * @type {Error}
     * @memberof WrappedValidationError
     */
    'error': Error;
}

